/* A recursive-descent parser generated by peg 0.1.2 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 67

#include <stdio.h>
#include <signal.h>
#include <time.h>
#include <stdarg.h>
#include <stdbool.h>
#include <ctype.h>
#include "bstrlib.h"
#include "list.h"

#define YY_noDEBUG 1
#define KBYTE 1024
#define MBYTE KBYTE * 1024
#define STR_BUFFER_LEN 1024

#define IMAGE_FRAME 1
#define IMAGE_THUMB ( 1 << 1 )

#define TOC_NOTOC ( 1 << 1 )
#define TOC_FORCETOC ( 1 << 2 )
#define TOC_RELOC ( 1 << 3 )

int read_from_buffer = 0;

#define YY_INPUT(buf, result, max_size) handle_input(buf, &result, max_size)

int current_header_level = 0;
int current_bullet_list_level;
int current_numbered_list_level;

int start_of_line = 1;
char protocol[5];

int image_attributes = 0;
bstring image_url;
bstring image_variables;

bstring link_path;
bstring link_text;

int toc_attributes = 0;

int in_tag = 0;
bstring tag_content;
unsigned int tag_content_size = 2 * MBYTE;

bstring output_buffer = NULL;
bstring input_buffer = NULL;
long input_buffer_pos = 0;

struct list list;

// Buffer printf, buffer output until we're ready
void bprintf(const char *fmt, ...) {
  int ret;
  bvformata(ret, output_buffer, fmt, fmt);
}

// Read from a string buffer rather than a file when requested by leg code.
// Could be made faster by reading more than a byte at a time... (up to max_size)
void handle_input(char *buf, int *result, size_t max_size) {
  if(input_buffer_pos > input_buffer->slen) {
    *result = 0;
  return;
  }
  *buf = input_buffer->data[input_buffer_pos++];
  *result = 1;
}

// Read a file into a bstring buffer 
void file_get_contents(bstring buffer, char *filename) {
  if(!buffer) {
    printf("Invalid buffer supplied to buffer_from_file.\n");
  }

  FILE *infile;
  if(!(infile = fopen(filename, "r"))) {
     printf("Can't open %s to read.\n", filename);
  }
  breada(buffer, (bNread)fread, infile);
  fclose(infile);
}

// Read from stdin until EOF, buffering to a bstring (destructive)
void stdin_get_contents(bstring buffer) {
  int c;
  ballocmin(buffer, 100 * KBYTE);
  buffer->slen = 0;
  while(EOF != (c = getchar())) {
    if(buffer->slen == buffer->mlen) {
      ballocmin(buffer, buffer->mlen * 2); // Just double the buffer
    buffer->mlen = buffer->mlen * 2;
  }
    buffer->data[buffer->slen] = c;
  buffer->slen++;
  }
  buffer->slen--; // Move the pointer back on the very last pass
}

// Append a character to a buffer a repeat number of times
void repeat_append(bstring buffer, char chr, int count) {
  int i;
  bstring tmp = bfromcstr("");
  ballocmin(tmp, count);
  for(i = 0; i <= count; i++) {
      tmp->data[i] = chr;
    tmp->slen++;
  }
  bconcat(buffer, tmp);
  bdestroy(tmp);
}

// Render the ToC from a list, output to buffer
void assemble_toc(struct node *item, bstring toc_buffer) {
  if(!item) {
    printf("Bad list passed to assemble_toc\n");
    return;
  }

  struct node *next;
  int previous_level = item->level;
  int total_layers = 0;
  int i;
  bformata(toc_buffer, "%s", "<div id=\"toc\" class=\"toc\">\n<div id=\"toctitle\">Contents</div>\n<ol>\n");
  while(item != NULL) {
    next = item->next;

    // Layer the list deeper as necessary
    if(item->level > previous_level) {
      repeat_append(toc_buffer, ' ', (total_layers + 1) * 2);
      for(i = previous_level; i < item->level; i++) {
        bformata(toc_buffer, "%s", "<ol>\n");
        total_layers++;
      }
    } else if((item->level < previous_level) && (total_layers > 1)) {
      for(i = previous_level; i > item->level; i--) {
        repeat_append(toc_buffer, ' ', (total_layers) * 2);
        bformata(toc_buffer, "%s", "</ol>\n");
        total_layers--;
      }
    }

    // Add the item
    if(item->name && item->content) {
      repeat_append(toc_buffer, ' ', (total_layers + 1) * 2);
      bformata(toc_buffer, "  <li><a href=\"#%s\">%s</a></li>\n", bdata(item->name), bdata(item->content));
    }
    previous_level = item->level;
    item = next;
  }

  // Clean up lists left open
  while(total_layers > 0) {
    bformata(toc_buffer, "%s", "</ol>\n");
    total_layers--;
  }
  bformata(toc_buffer, "%s", "</ol>\n</div>\n");
}

// Insert the ToC into the output buffer in place of the __TOC__ tag
void insert_reloc_toc(bstring toc_buffer) {
  bstring find = bfromcstr("__TOC__");
  if(bfindreplace(output_buffer, find, toc_buffer, 0) == BSTR_ERR) {
    printf("Error inserting toc_buffer into output_buffer\n");
  }
  bdestroy(find);
}

// Main ToC routine
void handle_toc() {
  if(toc_attributes & TOC_NOTOC) {
    return;
  }

  if((list.size > 3) || (toc_attributes & TOC_FORCETOC)) {
    bstring toc_buffer = bfromcstr("");
    assemble_toc(list.head->next, toc_buffer);

    if(toc_attributes & TOC_RELOC) {
      insert_reloc_toc(toc_buffer);
      bdestroy(toc_buffer);
      return;
    }

    if(binsert(output_buffer, 0, toc_buffer, ' ') != BSTR_OK) {
      printf("Error prepending toc_buffer to output_buffer\n");
    }
    bdestroy(toc_buffer);
  }
}

void remove_parentheticals(bstring str) {
  char *temp = bstr2cstr(str, '\0');

  int i, index = 0;
  int in_tag = 0;
  for(i = 0; i < blength(str); i++) {
    if((bdata(str))[i] == '(') {
      in_tag++;
      continue;
    } else if((bdata(str))[i] == ')') {
      in_tag--;
      continue;
    }
    if(in_tag < 1) temp[index++] = (bdata(str))[i];
  }
  temp[index] = '\0';
  bdestroy(str);
  str = bfromcstr(temp);
  bcstrfree(temp);
}

void strip_tags(bstring str) {
  char *temp = bstr2cstr(str, '\0');

  int i, index = 0;
  int in_tag = 0;
  for(i = 0; i < blength(str); i++) {
    if((bdata(str))[i] == '<') {
      in_tag++;
      continue;
    } else if((bdata(str))[i] == '>') {
      in_tag--;
      continue;
    }
    if(in_tag < 1) temp[index++] = (bdata(str))[i];
  }
  temp[index] = '\0';
  bdestroy(str);
  str = bfromcstr(temp);
  bcstrfree(temp);
}

void urlencode(bstring b) {
  char *p;
  int c, e;
  bstring target = bfromcstr("");

  int whitelist[] = {
    /* reserved characters */
    [36] '$',
    [38] '&',
    [43] '+',
    [44] ',',
    [46] '.',
    [47] '/',
    [58] ':',
    [59] ';',
    [61] '=',
    [63] '?',
    [64] '@',
    [95] '_'
  };

  p = bdata(b);
  while ((c = *p++)) { // Double parens to make gcc shut up
    /* [0-9A-Za-z] */
    if (('0' <= c && c <= '9') ||
        ('A' <= c && c <= 'Z') ||
        ('a' <= c && c <= 'z')) {
      bformata(target, "%c", c);
      continue;
    }
    e = whitelist[c];
    if (e) {
      bformata(target, "%c", c);
      continue;
    }
    bformata(target, "%%%02x", c);
  }
  bassign(b, target);
  bdestroy(target);
}

void strip_html_markup(bstring str) {
  strip_tags(str);
  brtrimws(str);
  bstring find = bfromcstr(" ");
  bstring replace = bfromcstr("_");
  bfindreplace(str, find, replace, 0);
  bdestroy(find);
  bdestroy(replace);
}

void open_tag(char *tag, char *args) {
  if(args) {
    bprintf("<%s %s>", tag, args);
  } else {
    bprintf("<%s>", tag);
  }

  in_tag = 1;
  if(tag_content) {
    btrunc(tag_content,0 );
  }
}

void close_tag(char *tag) {
  bprintf("</%s>", tag);
  in_tag = 0;
}

void append_to_tag_content(char *fmt, ...) {
  int ret;

  if(!in_tag) {
    bvformata(ret, output_buffer, fmt, fmt);
    return;
  }

  bvformata(ret, tag_content, fmt, fmt);
}

// Number of entries on one line of the valid tag lookup table
#define HTML_MAX_TAG_ENTRIES 13
// Longest allowed tag length
#define HTML_MAX_LENGTH 11

// Validate whether or not a specific HTML tag is allowed.
bool valid_html_tag(char *html_tag, size_t orig_len) {

  // Lookup table based on tag length
  static const char valid_tags[HTML_MAX_LENGTH][HTML_MAX_TAG_ENTRIES][10] = {
    [1]  { "b", "i", "p", "s" },
    [2]  { "br", "dd", "dl", "dt", "em", "hr", "li", "ol", "td", "th", "tr", "tt", "ul" },
    [3]  { "big", "del", "div", "ins", "pre", "sub", "sup" },
    [4]  { "abbr", "cite", "code", "font", "span" },
    [5]  { "small", "table" }, 
    [6]  { "strong", "strike", "center" },
    [7]  { "caption" },
    [10] { "blockquote" }
  };

  char *tag = html_tag;
  int len = orig_len;

  if((tag[0] == '/') && (len > 1)) {
    tag++;
    len--;
  }

  if(len == 0) {
    return false;
  }

  // If there are no allowed tags this length
  if(!valid_tags[len]) {
    return false;
  }

  int i;
  char c = tolower(tag[0]);
  for(i = 0; i < HTML_MAX_TAG_ENTRIES; i++) {
    if(tolower(valid_tags[len][i][0]) == c) { // Integer comparison on first character
      if(!strncasecmp(tag, valid_tags[len][i], len)) {
        return true;
      }
    }
  }

  return false;
}


#ifndef YY_VARIABLE
#define YY_VARIABLE(T)	static T
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yybegin= yypos, 1)
#endif
#ifndef YY_END
#define YY_END		( yyend= yypos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif

#ifndef YY_PART

typedef void (*yyaction)(char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

YY_VARIABLE(char *   ) yybuf= 0;
YY_VARIABLE(int	     ) yybuflen= 0;
YY_VARIABLE(int	     ) yypos= 0;
YY_VARIABLE(int	     ) yylimit= 0;
YY_VARIABLE(char *   ) yytext= 0;
YY_VARIABLE(int	     ) yytextlen= 0;
YY_VARIABLE(int	     ) yybegin= 0;
YY_VARIABLE(int	     ) yyend= 0;
YY_VARIABLE(int	     ) yytextmax= 0;
YY_VARIABLE(yythunk *) yythunks= 0;
YY_VARIABLE(int	     ) yythunkslen= 0;
YY_VARIABLE(int      ) yythunkpos= 0;
YY_VARIABLE(YYSTYPE  ) yy;
YY_VARIABLE(YYSTYPE *) yyval= 0;
YY_VARIABLE(YYSTYPE *) yyvals= 0;
YY_VARIABLE(int      ) yyvalslen= 0;

YY_LOCAL(int) yyrefill(void)
{
  int yyn;
  while (yybuflen - yypos < 512)
    {
      yybuflen *= 2;
      yybuf= realloc(yybuf, yybuflen);
    }
  YY_INPUT((yybuf + yypos), yyn, (yybuflen - yypos));
  if (!yyn) return 0;
  yylimit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(void)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  ++yypos;
  return 1;
}

YY_LOCAL(int) yymatchChar(int c)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  if (yybuf[yypos] == c)
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchChar(%c) @ %s\n", c, yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(%c) @ %s\n", c, yybuf+yypos));
  return 0;
}

YY_LOCAL(int) yymatchString(char *s)
{
  int yysav= yypos;
  while (*s)
    {
      if (yypos >= yylimit && !yyrefill()) return 0;
      if (yybuf[yypos] != *s)
        {
          yypos= yysav;
          return 0;
        }
      ++s;
      ++yypos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(unsigned char *bits)
{
  int c;
  if (yypos >= yylimit && !yyrefill()) return 0;
  c= yybuf[yypos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yybuf+yypos));
  return 0;
}

YY_LOCAL(void) yyDo(yyaction action, int begin, int end)
{
  while (yythunkpos >= yythunkslen)
    {
      yythunkslen *= 2;
      yythunks= realloc(yythunks, sizeof(yythunk) * yythunkslen);
    }
  yythunks[yythunkpos].begin=  begin;
  yythunks[yythunkpos].end=    end;
  yythunks[yythunkpos].action= action;
  ++yythunkpos;
}

YY_LOCAL(int) yyText(int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yytextlen < (yyleng - 1))
	{
	  yytextlen *= 2;
	  yytext= realloc(yytext, yytextlen);
	}
      memcpy(yytext, yybuf + begin, yyleng);
    }
  yytext[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(void)
{
  int pos;
  for (pos= 0;  pos < yythunkpos;  ++pos)
    {
      yythunk *thunk= &yythunks[pos];
      int yyleng= thunk->end ? yyText(thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yytext));
      thunk->action(yytext, yyleng);
    }
  yythunkpos= 0;
}

YY_LOCAL(void) yyCommit()
{
  if ((yylimit -= yypos))
    {
      memmove(yybuf, yybuf + yypos, yylimit);
    }
  yybegin -= yypos;
  yyend -= yypos;
  yypos= yythunkpos= 0;
}

YY_LOCAL(int) yyAccept(int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone();
      yyCommit();
    }
  return 1;
}

YY_LOCAL(void) yyPush(char *text, int count)	{ yyval += count; }
YY_LOCAL(void) yyPop(char *text, int count)	{ yyval -= count; }
YY_LOCAL(void) yySet(char *text, int count)	{ yyval[count]= yy; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yythunkpos0)

YY_RULE(int) yy_forcetoc(); /* 67 */
YY_RULE(int) yy_toc(); /* 66 */
YY_RULE(int) yy_notoc(); /* 65 */
YY_RULE(int) yy_table_cell(); /* 64 */
YY_RULE(int) yy_table_heading(); /* 63 */
YY_RULE(int) yy_table_row(); /* 62 */
YY_RULE(int) yy_table_header(); /* 61 */
YY_RULE(int) yy_table_caption(); /* 60 */
YY_RULE(int) yy_table_body(); /* 59 */
YY_RULE(int) yy_thumb(); /* 58 */
YY_RULE(int) yy_frame(); /* 57 */
YY_RULE(int) yy_float(); /* 56 */
YY_RULE(int) yy_image_type(); /* 55 */
YY_RULE(int) yy_generic_variable(); /* 54 */
YY_RULE(int) yy_special_image_variables(); /* 53 */
YY_RULE(int) yy_value(); /* 52 */
YY_RULE(int) yy_variable(); /* 51 */
YY_RULE(int) yy_close_image(); /* 50 */
YY_RULE(int) yy_arguments(); /* 49 */
YY_RULE(int) yy_file_indicator(); /* 48 */
YY_RULE(int) yy_open_image(); /* 47 */
YY_RULE(int) yy_link_name(); /* 46 */
YY_RULE(int) yy_link_url(); /* 45 */
YY_RULE(int) yy_url(); /* 44 */
YY_RULE(int) yy_unnamed_link(); /* 43 */
YY_RULE(int) yy_named_link(); /* 42 */
YY_RULE(int) yy_blend(); /* 41 */
YY_RULE(int) yy_link_close(); /* 40 */
YY_RULE(int) yy_rename(); /* 39 */
YY_RULE(int) yy_link_path(); /* 38 */
YY_RULE(int) yy_namespace(); /* 37 */
YY_RULE(int) yy_link_open(); /* 36 */
YY_RULE(int) yy_external_link(); /* 35 */
YY_RULE(int) yy_local_link(); /* 34 */
YY_RULE(int) yy_pre_line(); /* 33 */
YY_RULE(int) yy_italic(); /* 32 */
YY_RULE(int) yy_bold(); /* 31 */
YY_RULE(int) yy_bold_italic(); /* 30 */
YY_RULE(int) yy_numbered(); /* 29 */
YY_RULE(int) yy_numbered_list_entry(); /* 28 */
YY_RULE(int) yy_bullet(); /* 27 */
YY_RULE(int) yy_bullet_list_entry(); /* 26 */
YY_RULE(int) yy_numbered_list(); /* 25 */
YY_RULE(int) yy_bullet_list(); /* 24 */
YY_RULE(int) yy_heading_text(); /* 23 */
YY_RULE(int) yy_heading_marker(); /* 22 */
YY_RULE(int) yy_space(); /* 21 */
YY_RULE(int) yy_eof(); /* 20 */
YY_RULE(int) yy_eol(); /* 19 */
YY_RULE(int) yy_anything_else(); /* 18 */
YY_RULE(int) yy_table(); /* 17 */
YY_RULE(int) yy_link(); /* 16 */
YY_RULE(int) yy_image(); /* 15 */
YY_RULE(int) yy_formatting(); /* 14 */
YY_RULE(int) yy_list(); /* 13 */
YY_RULE(int) yy_indentation(); /* 12 */
YY_RULE(int) yy_heading(); /* 11 */
YY_RULE(int) yy_template(); /* 10 */
YY_RULE(int) yy_table_of_contents(); /* 9 */
YY_RULE(int) yy_horizontal_line(); /* 8 */
YY_RULE(int) yy_paragraph(); /* 7 */
YY_RULE(int) yy_wikitext(); /* 6 */
YY_RULE(int) yy_wikitext_line(); /* 5 */
YY_RULE(int) yy_pre_block(); /* 4 */
YY_RULE(int) yy_html(); /* 3 */
YY_RULE(int) yy_nowiki(); /* 2 */
YY_RULE(int) yy_page(); /* 1 */

YY_ACTION(void) yy_1_anything_else(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_anything_else\n"));
   start_of_line = 0; append_to_tag_content(yytext); ;
}
YY_ACTION(void) yy_1_html(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_html\n"));
   
  if(valid_html_tag(yytext, yyleng)) { 
    bstring b = bfromcstr(yytext);
    btolower(b);
    bprintf("<%s>", bdata(b));
    bdestroy(b);
  } else {
    bprintf("&lt;%s&gt;", yytext); 
  }
  start_of_line = 0;
;
}
YY_ACTION(void) yy_1_toc(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_toc\n"));
   toc_attributes |= TOC_RELOC; bprintf("__TOC__"); // pass-through for later replacement ;
}
YY_ACTION(void) yy_1_forcetoc(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_forcetoc\n"));
   toc_attributes |= TOC_FORCETOC; ;
}
YY_ACTION(void) yy_1_notoc(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_notoc\n"));
   toc_attributes |= TOC_NOTOC; ;
}
YY_ACTION(void) yy_1_template(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_template\n"));
   start_of_line = 0; ;
}
YY_ACTION(void) yy_3_table_heading(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_3_table_heading\n"));
  bprintf("%s</th>", yytext); ;
}
YY_ACTION(void) yy_2_table_heading(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_table_heading\n"));
   bprintf(" %s>", yytext); ;
}
YY_ACTION(void) yy_1_table_heading(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_table_heading\n"));
   bprintf("<th"); ;
}
YY_ACTION(void) yy_2_table_header(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_table_header\n"));
   bprintf("</tr>"); ;
}
YY_ACTION(void) yy_1_table_header(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_table_header\n"));
   bprintf("<tr>"); ;
}
YY_ACTION(void) yy_2_table_cell(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_table_cell\n"));
   bprintf("%s</td>", yytext); ;
}
YY_ACTION(void) yy_1_table_cell(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_table_cell\n"));
   bprintf("<td>"); ;
}
YY_ACTION(void) yy_2_table_row(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_table_row\n"));
   bprintf("</tr>"); ;
}
YY_ACTION(void) yy_1_table_row(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_table_row\n"));
   bprintf("<tr>"); ;
}
YY_ACTION(void) yy_1_table_caption(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_table_caption\n"));
   bprintf("<caption>%s</caption>", yytext); ;
}
YY_ACTION(void) yy_2_table(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_table\n"));
   bprintf("</table>"); ;
}
YY_ACTION(void) yy_1_table(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_table\n"));
   bprintf("<table>"); ;
}
YY_ACTION(void) yy_1_value(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_value\n"));
   
  bformata(image_variables, "=\"%s\"", yytext);
;
}
YY_ACTION(void) yy_1_generic_variable(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_generic_variable\n"));
   
  bformata(image_variables, "%s", yytext);
;
}
YY_ACTION(void) yy_1_float(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_float\n"));
   
  bformata(image_variables, " class=\"float%s\"", yytext);
;
}
YY_ACTION(void) yy_1_thumb(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_thumb\n"));
   image_attributes |= IMAGE_THUMB; ;
}
YY_ACTION(void) yy_1_frame(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_frame\n"));
   image_attributes |= IMAGE_FRAME; ;
}
YY_ACTION(void) yy_1_file_indicator(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_file_indicator\n"));
   bassignformat(image_url, "%s", yytext); ;
}
YY_ACTION(void) yy_2_image(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_image\n"));
  
  if(image_attributes & IMAGE_FRAME) {
    bprintf("<div class=\"thumb tright\"><div class=\"thumbinner\">");
  }

  if(image_attributes & IMAGE_THUMB) {
    bprintf("<a href=\"File:%s\" class=\"image\"><img src=\"%s\" width=\"220\" height=\"30\" class=\"thumbimage\"/></a>", bdata(image_url), bdata(image_url));
  } else if(image_attributes & IMAGE_FRAME) {
    bprintf("<a href=\"File:%s\" class=\"image\"><img src=\"%s\" class=\"thumbimage\"/></a>", bdata(image_url), bdata(image_url));
  } else {
    bprintf("<a href=\"File:%s\" class=\"image\"><img src=\"%s\" %s/></a>", bdata(image_url), bdata(image_url), bdata(image_variables));
  }

  if(image_attributes & IMAGE_FRAME) {
    bprintf("<div class=\"thumbcaption\"></div></div>");
  }
;
}
YY_ACTION(void) yy_1_image(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_image\n"));
   btrunc(image_variables, 0); ;
}
YY_ACTION(void) yy_2_url(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_url\n"));
   append_to_tag_content("<a href=\"%s://%s\">%s://%s</a>", protocol, yytext, protocol, yytext); ;
}
YY_ACTION(void) yy_1_url(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_url\n"));
   strcpy(protocol, yytext); ;
}
YY_ACTION(void) yy_1_unnamed_link(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_unnamed_link\n"));
   append_to_tag_content("<a href=\"%s\">%s</a>", yytext, yytext);;
}
YY_ACTION(void) yy_1_link_name(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_link_name\n"));
   append_to_tag_content(yytext); ;
}
YY_ACTION(void) yy_1_link_url(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_link_url\n"));
   append_to_tag_content(yytext); ;
}
YY_ACTION(void) yy_3_named_link(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_3_named_link\n"));
  append_to_tag_content("</a>"); ;
}
YY_ACTION(void) yy_2_named_link(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_named_link\n"));
   append_to_tag_content("\">");;
}
YY_ACTION(void) yy_1_named_link(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_named_link\n"));
   append_to_tag_content("<a href=\""); ;
}
YY_ACTION(void) yy_1_blend(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_blend\n"));
   bcatcstr(link_text, yytext); ;
}
YY_ACTION(void) yy_1_rename(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_rename\n"));
   link_text = bfromcstr(yytext); ;
}
YY_ACTION(void) yy_1_link_path(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_link_path\n"));
   bcatcstr(link_path, yytext); link_text = bfromcstr(yytext); ;
}
YY_ACTION(void) yy_1_namespace(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_namespace\n"));
   link_path = bfromcstr(yytext); bconchar(link_path, ':'); ;
}
YY_ACTION(void) yy_1_local_link(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_local_link\n"));
  
  strip_html_markup(link_path);
  urlencode(link_path);
  remove_parentheticals(link_text);
  btrimws(link_text);
  append_to_tag_content("<a href=\"/%s\">%s</a>", bdata(link_path), bdata(link_text));
  link_path = bfromcstr(""); link_text = bfromcstr("");
  ;
}
YY_ACTION(void) yy_1_link(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_link\n"));
   start_of_line = 0; ;
}
YY_ACTION(void) yy_1_pre_line(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_pre_line\n"));
   bprintf("%s", yytext); ;
}
YY_ACTION(void) yy_2_pre_block(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_pre_block\n"));
   bprintf("</pre>"); ;
}
YY_ACTION(void) yy_1_pre_block(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_pre_block\n"));
   bprintf("<pre>"); ;
}
YY_ACTION(void) yy_2_italic(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_italic\n"));
  append_to_tag_content("</i>");;
}
YY_ACTION(void) yy_1_italic(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_italic\n"));
  append_to_tag_content("<i>");;
}
YY_ACTION(void) yy_2_bold(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_bold\n"));
  append_to_tag_content("</b>");;
}
YY_ACTION(void) yy_1_bold(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_bold\n"));
  append_to_tag_content("<b>");;
}
YY_ACTION(void) yy_2_bold_italic(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_bold_italic\n"));
  append_to_tag_content("</i></b>");;
}
YY_ACTION(void) yy_1_bold_italic(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_bold_italic\n"));
  append_to_tag_content("<b><i>");;
}
YY_ACTION(void) yy_1_numbered(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_numbered\n"));
  
  start_of_line = 0;
  if(current_numbered_list_level < yyleng && current_numbered_list_level != 0) {
    bprintf("<ol>");
  } else if(current_numbered_list_level > yyleng) {
    bprintf("</ol>");
  }
  current_numbered_list_level = yyleng; 
  bprintf("<li>"); 
;
}
YY_ACTION(void) yy_1_numbered_list_entry(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_numbered_list_entry\n"));
   bprintf("</li>"); ;
}
YY_ACTION(void) yy_2_numbered_list(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_numbered_list\n"));
   while(current_numbered_list_level--) { bprintf("</ol>"); } ;
}
YY_ACTION(void) yy_1_numbered_list(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_numbered_list\n"));
   bprintf("<ol>"); ;
}
YY_ACTION(void) yy_1_bullet(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_bullet\n"));
  
  start_of_line = 0;
  if(current_bullet_list_level < yyleng && current_bullet_list_level != 0) {
    bprintf("<ul>");
  } else if(current_bullet_list_level > yyleng) {
    bprintf("</ul>");
  }
  current_bullet_list_level = yyleng; 
  bprintf("<li>"); 
;
}
YY_ACTION(void) yy_1_bullet_list_entry(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_bullet_list_entry\n"));
   bprintf("</li>"); ;
}
YY_ACTION(void) yy_2_bullet_list(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_bullet_list\n"));
   
  while((current_bullet_list_level > 0) && current_bullet_list_level--) { 
    bprintf("</ul>"); 
  }
;
}
YY_ACTION(void) yy_1_bullet_list(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_bullet_list\n"));
   bprintf("<ul>"); ;
}
YY_ACTION(void) yy_1_indentation(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_indentation\n"));
   bprintf("&nbsp;&nbsp;"); ;
}
YY_ACTION(void) yy_1_horizontal_line(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_horizontal_line\n"));
   bprintf("<hr/>"); ;
}
YY_ACTION(void) yy_1_paragraph(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_paragraph\n"));
   bprintf("</p><p>"); ;
}
YY_ACTION(void) yy_1_heading_marker(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_heading_marker\n"));
   if(current_header_level == 0) current_header_level = (yyleng > 5) ? 5 : yyleng; ;
}
YY_ACTION(void) yy_2_heading(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_heading\n"));
  
    brtrimws(tag_content);
    bstring tmp = bstrcpy(tag_content);
    strip_html_markup(tmp);
    urlencode(tmp);
    bprintf("<span class=\"editsection\">[<a href=\"edit\">edit</a>]</span><span class=\"mw-headline\" id=\"%s\">", bdata(tmp));
    bdestroy(tmp);

    bprintf("%s</span>", bdata(tag_content));
    char tag[4];
    sprintf(tag, "h%d", current_header_level);
    close_tag(tag);

    struct node *current = list_get_new_tail(&list);

    tmp = bstrcpy(tag_content);
    strip_html_markup(tmp);
    urlencode(tmp);
    bprintf("<a name=\"%s\" />", bdata(tmp));
    bassign(current->name, tmp);

    bstring human_name = bstrcpy(tag_content);
    strip_tags(human_name);
    brtrimws(human_name);
    bassign(current->content, human_name);
    current->level = current_header_level;

    bdestroy(tmp);
    bdestroy(human_name);

    btrunc(tag_content, 0);
    current_header_level = 0;
  ;
}
YY_ACTION(void) yy_1_heading(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_heading\n"));
  
    char tag[4];
    sprintf(tag, "h%d", current_header_level);
    open_tag(tag, NULL);
  ;
}
YY_ACTION(void) yy_1_eol(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_eol\n"));
   start_of_line = 1; ;
}

YY_RULE(int) yy_forcetoc()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "forcetoc"));  if (!yymatchString("__FORCETOC__")) goto l1;  yyDo(yy_1_forcetoc, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "forcetoc", yybuf+yypos));
  return 1;
  l1:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "forcetoc", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_toc()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "toc"));  if (!yymatchString("__TOC__")) goto l2;  yyDo(yy_1_toc, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "toc", yybuf+yypos));
  return 1;
  l2:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "toc", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_notoc()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "notoc"));  if (!yymatchString("__NOTOC__")) goto l3;  yyDo(yy_1_notoc, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "notoc", yybuf+yypos));
  return 1;
  l3:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "notoc", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_table_cell()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "table_cell"));
  {  int yypos5= yypos, yythunkpos5= yythunkpos;  if (!yymatchChar('|')) goto l5;  goto l6;
  l5:;	  yypos= yypos5; yythunkpos= yythunkpos5;
  }
  l6:;	  yyDo(yy_1_table_cell, yybegin, yyend);  if (!yymatchChar(' ')) goto l4;
  l7:;	
  {  int yypos8= yypos, yythunkpos8= yythunkpos;  if (!yymatchChar(' ')) goto l8;  goto l7;
  l8:;	  yypos= yypos8; yythunkpos= yythunkpos8;
  }  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l4;
  l9:;	
  {  int yypos10= yypos, yythunkpos10= yythunkpos;
  {  int yypos11= yypos, yythunkpos11= yythunkpos;  if (!yymatchString("||")) goto l11;  goto l10;
  l11:;	  yypos= yypos11; yythunkpos= yythunkpos11;
  }
  {  int yypos12= yypos, yythunkpos12= yythunkpos;  if (!yy_eol()) goto l12;  goto l10;
  l12:;	  yypos= yypos12; yythunkpos= yythunkpos12;
  }  if (!yymatchDot()) goto l10;  goto l9;
  l10:;	  yypos= yypos10; yythunkpos= yythunkpos10;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l4;
  {  int yypos13= yypos, yythunkpos13= yythunkpos;  if (!yy_eol()) goto l14;  goto l13;
  l14:;	  yypos= yypos13; yythunkpos= yythunkpos13;  if (!yymatchString("||")) goto l4;
  }
  l13:;	  yyDo(yy_2_table_cell, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "table_cell", yybuf+yypos));
  return 1;
  l4:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "table_cell", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_table_heading()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "table_heading"));  yyDo(yy_1_table_heading, yybegin, yyend);  if (!yymatchChar('!')) goto l15;  if (!yymatchChar(' ')) goto l15;
  l16:;	
  {  int yypos17= yypos, yythunkpos17= yythunkpos;  if (!yymatchChar(' ')) goto l17;  goto l16;
  l17:;	  yypos= yypos17; yythunkpos= yythunkpos17;
  }  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l15;
  l18:;	
  {  int yypos19= yypos, yythunkpos19= yythunkpos;
  {  int yypos20= yypos, yythunkpos20= yythunkpos;  if (!yymatchString(" |")) goto l20;  goto l19;
  l20:;	  yypos= yypos20; yythunkpos= yythunkpos20;
  }  if (!yymatchDot()) goto l19;  goto l18;
  l19:;	  yypos= yypos19; yythunkpos= yythunkpos19;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l15;  yyDo(yy_2_table_heading, yybegin, yyend);  if (!yymatchString(" |")) goto l15;
  l21:;	
  {  int yypos22= yypos, yythunkpos22= yythunkpos;  if (!yy_space()) goto l22;  goto l21;
  l22:;	  yypos= yypos22; yythunkpos= yythunkpos22;
  }  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l15;
  l23:;	
  {  int yypos24= yypos, yythunkpos24= yythunkpos;
  {  int yypos25= yypos, yythunkpos25= yythunkpos;  if (!yy_eol()) goto l25;  goto l24;
  l25:;	  yypos= yypos25; yythunkpos= yythunkpos25;
  }  if (!yymatchDot()) goto l24;  goto l23;
  l24:;	  yypos= yypos24; yythunkpos= yythunkpos24;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l15;  if (!yy_eol()) goto l15;  yyDo(yy_3_table_heading, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "table_heading", yybuf+yypos));
  return 1;
  l15:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "table_heading", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_table_row()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "table_row"));  if (!yymatchString("|-")) goto l26;  yyDo(yy_1_table_row, yybegin, yyend);
  l27:;	
  {  int yypos28= yypos, yythunkpos28= yythunkpos;  if (!yy_space()) goto l28;  goto l27;
  l28:;	  yypos= yypos28; yythunkpos= yythunkpos28;
  }  if (!yy_eol()) goto l26;
  l29:;	
  {  int yypos30= yypos, yythunkpos30= yythunkpos;  if (!yy_table_heading()) goto l30;  goto l29;
  l30:;	  yypos= yypos30; yythunkpos= yythunkpos30;
  }
  l31:;	
  {  int yypos32= yypos, yythunkpos32= yythunkpos;  if (!yy_table_cell()) goto l32;  goto l31;
  l32:;	  yypos= yypos32; yythunkpos= yythunkpos32;
  }  yyDo(yy_2_table_row, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "table_row", yybuf+yypos));
  return 1;
  l26:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "table_row", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_table_header()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "table_header"));  yyDo(yy_1_table_header, yybegin, yyend);  if (!yy_table_heading()) goto l33;
  l34:;	
  {  int yypos35= yypos, yythunkpos35= yythunkpos;  if (!yy_table_heading()) goto l35;  goto l34;
  l35:;	  yypos= yypos35; yythunkpos= yythunkpos35;
  }  yyDo(yy_2_table_header, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "table_header", yybuf+yypos));
  return 1;
  l33:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "table_header", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_table_caption()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "table_caption"));  if (!yymatchString("|+")) goto l36;  if (!yymatchChar(' ')) goto l36;
  l37:;	
  {  int yypos38= yypos, yythunkpos38= yythunkpos;  if (!yymatchChar(' ')) goto l38;  goto l37;
  l38:;	  yypos= yypos38; yythunkpos= yythunkpos38;
  }  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l36;
  l39:;	
  {  int yypos40= yypos, yythunkpos40= yythunkpos;
  {  int yypos41= yypos, yythunkpos41= yythunkpos;  if (!yy_eol()) goto l41;  goto l40;
  l41:;	  yypos= yypos41; yythunkpos= yythunkpos41;
  }  if (!yymatchDot()) goto l40;  goto l39;
  l40:;	  yypos= yypos40; yythunkpos= yythunkpos40;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l36;  if (!yy_eol()) goto l36;  yyDo(yy_1_table_caption, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "table_caption", yybuf+yypos));
  return 1;
  l36:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "table_caption", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_table_body()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "table_body"));
  {  int yypos43= yypos, yythunkpos43= yythunkpos;  if (!yy_table_caption()) goto l43;  goto l44;
  l43:;	  yypos= yypos43; yythunkpos= yythunkpos43;
  }
  l44:;	
  {  int yypos45= yypos, yythunkpos45= yythunkpos;  if (!yy_table_header()) goto l45;  goto l46;
  l45:;	  yypos= yypos45; yythunkpos= yythunkpos45;
  }
  l46:;	  if (!yy_table_row()) goto l42;
  l47:;	
  {  int yypos48= yypos, yythunkpos48= yythunkpos;  if (!yy_table_row()) goto l48;  goto l47;
  l48:;	  yypos= yypos48; yythunkpos= yythunkpos48;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "table_body", yybuf+yypos));
  return 1;
  l42:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "table_body", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_thumb()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "thumb"));
  {  int yypos50= yypos, yythunkpos50= yythunkpos;  if (!yymatchString("thumbnail")) goto l51;  goto l50;
  l51:;	  yypos= yypos50; yythunkpos= yythunkpos50;  if (!yymatchString("thumb")) goto l49;
  }
  l50:;	  yyDo(yy_1_thumb, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "thumb", yybuf+yypos));
  return 1;
  l49:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "thumb", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_frame()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "frame"));  if (!yymatchString("frame")) goto l52;  yyDo(yy_1_frame, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "frame", yybuf+yypos));
  return 1;
  l52:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "frame", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_float()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "float"));
  {  int yypos54= yypos, yythunkpos54= yythunkpos;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l55;
  {  int yypos56= yypos, yythunkpos56= yythunkpos;  if (!yymatchString("left")) goto l57;  goto l56;
  l57:;	  yypos= yypos56; yythunkpos= yythunkpos56;  if (!yymatchString("right")) goto l58;  goto l56;
  l58:;	  yypos= yypos56; yythunkpos= yythunkpos56;  if (!yymatchString("center")) goto l55;
  }
  l56:;	  yyText(yybegin, yyend);  if (!(YY_END)) goto l55;  yyDo(yy_1_float, yybegin, yyend);  goto l54;
  l55:;	  yypos= yypos54; yythunkpos= yythunkpos54;  if (!yymatchString("none")) goto l53;
  }
  l54:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "float", yybuf+yypos));
  return 1;
  l53:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "float", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_image_type()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "image_type"));
  {  int yypos60= yypos, yythunkpos60= yythunkpos;  if (!yy_frame()) goto l61;  goto l60;
  l61:;	  yypos= yypos60; yythunkpos= yythunkpos60;  if (!yy_thumb()) goto l59;
  }
  l60:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "image_type", yybuf+yypos));
  return 1;
  l59:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "image_type", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_generic_variable()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "generic_variable"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l62;
  l63:;	
  {  int yypos64= yypos, yythunkpos64= yythunkpos;
  {  int yypos65= yypos, yythunkpos65= yythunkpos;  if (!yymatchChar('|')) goto l65;  goto l64;
  l65:;	  yypos= yypos65; yythunkpos= yythunkpos65;
  }
  {  int yypos66= yypos, yythunkpos66= yythunkpos;  if (!yymatchChar('=')) goto l66;  goto l64;
  l66:;	  yypos= yypos66; yythunkpos= yythunkpos66;
  }
  {  int yypos67= yypos, yythunkpos67= yythunkpos;  if (!yy_close_image()) goto l67;  goto l64;
  l67:;	  yypos= yypos67; yythunkpos= yythunkpos67;
  }  if (!yymatchDot()) goto l64;  goto l63;
  l64:;	  yypos= yypos64; yythunkpos= yythunkpos64;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l62;  yyDo(yy_1_generic_variable, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "generic_variable", yybuf+yypos));
  return 1;
  l62:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "generic_variable", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_special_image_variables()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "special_image_variables"));
  {  int yypos69= yypos, yythunkpos69= yythunkpos;  if (!yy_image_type()) goto l70;  goto l69;
  l70:;	  yypos= yypos69; yythunkpos= yythunkpos69;  if (!yy_float()) goto l68;
  }
  l69:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "special_image_variables", yybuf+yypos));
  return 1;
  l68:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "special_image_variables", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_value()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "value"));  if (!yymatchChar('=')) goto l71;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l71;
  l72:;	
  {  int yypos73= yypos, yythunkpos73= yythunkpos;
  {  int yypos74= yypos, yythunkpos74= yythunkpos;  if (!yymatchChar('|')) goto l74;  goto l73;
  l74:;	  yypos= yypos74; yythunkpos= yythunkpos74;
  }
  {  int yypos75= yypos, yythunkpos75= yythunkpos;  if (!yy_close_image()) goto l75;  goto l73;
  l75:;	  yypos= yypos75; yythunkpos= yythunkpos75;
  }  if (!yymatchDot()) goto l73;  goto l72;
  l73:;	  yypos= yypos73; yythunkpos= yythunkpos73;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l71;  yyDo(yy_1_value, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "value", yybuf+yypos));
  return 1;
  l71:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "value", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_variable()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "variable"));
  {  int yypos77= yypos, yythunkpos77= yythunkpos;  if (!yy_special_image_variables()) goto l78;  goto l77;
  l78:;	  yypos= yypos77; yythunkpos= yythunkpos77;  if (!yy_generic_variable()) goto l76;
  }
  l77:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "variable", yybuf+yypos));
  return 1;
  l76:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "variable", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_close_image()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "close_image"));
  l80:;	
  {  int yypos81= yypos, yythunkpos81= yythunkpos;  if (!yy_space()) goto l81;  goto l80;
  l81:;	  yypos= yypos81; yythunkpos= yythunkpos81;
  }  if (!yymatchString("]]")) goto l79;
  yyprintf((stderr, "  ok   %s @ %s\n", "close_image", yybuf+yypos));
  return 1;
  l79:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "close_image", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_arguments()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "arguments"));  if (!yymatchChar('|')) goto l82;  if (!yy_variable()) goto l82;
  {  int yypos83= yypos, yythunkpos83= yythunkpos;  if (!yy_value()) goto l83;  goto l84;
  l83:;	  yypos= yypos83; yythunkpos= yythunkpos83;
  }
  l84:;	
  {  int yypos85= yypos, yythunkpos85= yythunkpos;  if (!yy_arguments()) goto l85;  goto l86;
  l85:;	  yypos= yypos85; yythunkpos= yythunkpos85;
  }
  l86:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "arguments", yybuf+yypos));
  return 1;
  l82:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "arguments", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_file_indicator()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "file_indicator"));
  {  int yypos88= yypos, yythunkpos88= yythunkpos;  if (!yymatchString("File:")) goto l89;  goto l88;
  l89:;	  yypos= yypos88; yythunkpos= yythunkpos88;  if (!yymatchString("Image:")) goto l87;
  }
  l88:;	  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l87;
  l90:;	
  {  int yypos91= yypos, yythunkpos91= yythunkpos;
  {  int yypos92= yypos, yythunkpos92= yythunkpos;  if (!yymatchChar('|')) goto l92;  goto l91;
  l92:;	  yypos= yypos92; yythunkpos= yythunkpos92;
  }
  {  int yypos93= yypos, yythunkpos93= yythunkpos;  if (!yy_close_image()) goto l93;  goto l91;
  l93:;	  yypos= yypos93; yythunkpos= yythunkpos93;
  }  if (!yymatchDot()) goto l91;  goto l90;
  l91:;	  yypos= yypos91; yythunkpos= yythunkpos91;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l87;  yyDo(yy_1_file_indicator, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "file_indicator", yybuf+yypos));
  return 1;
  l87:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "file_indicator", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_open_image()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "open_image"));  if (!yymatchString("[[")) goto l94;
  l95:;	
  {  int yypos96= yypos, yythunkpos96= yythunkpos;  if (!yy_space()) goto l96;  goto l95;
  l96:;	  yypos= yypos96; yythunkpos= yythunkpos96;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "open_image", yybuf+yypos));
  return 1;
  l94:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "open_image", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_link_name()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "link_name"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l97;
  {  int yypos100= yypos, yythunkpos100= yythunkpos;  if (!yymatchChar(']')) goto l100;  goto l97;
  l100:;	  yypos= yypos100; yythunkpos= yythunkpos100;
  }  if (!yymatchDot()) goto l97;
  l98:;	
  {  int yypos99= yypos, yythunkpos99= yythunkpos;
  {  int yypos101= yypos, yythunkpos101= yythunkpos;  if (!yymatchChar(']')) goto l101;  goto l99;
  l101:;	  yypos= yypos101; yythunkpos= yythunkpos101;
  }  if (!yymatchDot()) goto l99;  goto l98;
  l99:;	  yypos= yypos99; yythunkpos= yythunkpos99;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l97;  yyDo(yy_1_link_name, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "link_name", yybuf+yypos));
  return 1;
  l97:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "link_name", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_link_url()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "link_url"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l102;
  {  int yypos105= yypos, yythunkpos105= yythunkpos;  if (!yymatchChar(' ')) goto l105;  goto l102;
  l105:;	  yypos= yypos105; yythunkpos= yythunkpos105;
  }
  {  int yypos106= yypos, yythunkpos106= yythunkpos;  if (!yymatchChar(']')) goto l106;  goto l102;
  l106:;	  yypos= yypos106; yythunkpos= yythunkpos106;
  }  if (!yymatchDot()) goto l102;
  l103:;	
  {  int yypos104= yypos, yythunkpos104= yythunkpos;
  {  int yypos107= yypos, yythunkpos107= yythunkpos;  if (!yymatchChar(' ')) goto l107;  goto l104;
  l107:;	  yypos= yypos107; yythunkpos= yythunkpos107;
  }
  {  int yypos108= yypos, yythunkpos108= yythunkpos;  if (!yymatchChar(']')) goto l108;  goto l104;
  l108:;	  yypos= yypos108; yythunkpos= yythunkpos108;
  }  if (!yymatchDot()) goto l104;  goto l103;
  l104:;	  yypos= yypos104; yythunkpos= yythunkpos104;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l102;  yyDo(yy_1_link_url, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "link_url", yybuf+yypos));
  return 1;
  l102:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "link_url", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_url()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "url"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l109;
  {  int yypos110= yypos, yythunkpos110= yythunkpos;  if (!yymatchString("http")) goto l111;  goto l110;
  l111:;	  yypos= yypos110; yythunkpos= yythunkpos110;  if (!yymatchString("https")) goto l112;  goto l110;
  l112:;	  yypos= yypos110; yythunkpos= yythunkpos110;  if (!yymatchString("ftp")) goto l109;
  }
  l110:;	  yyText(yybegin, yyend);  if (!(YY_END)) goto l109;  yyDo(yy_1_url, yybegin, yyend);  if (!yymatchString("://")) goto l109;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l109;
  l113:;	
  {  int yypos114= yypos, yythunkpos114= yythunkpos;
  {  int yypos115= yypos, yythunkpos115= yythunkpos;  if (!yy_eol()) goto l115;  goto l114;
  l115:;	  yypos= yypos115; yythunkpos= yythunkpos115;
  }
  {  int yypos116= yypos, yythunkpos116= yythunkpos;  if (!yymatchChar(' ')) goto l116;  goto l114;
  l116:;	  yypos= yypos116; yythunkpos= yythunkpos116;
  }  if (!yymatchDot()) goto l114;  goto l113;
  l114:;	  yypos= yypos114; yythunkpos= yythunkpos114;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l109;  yyDo(yy_2_url, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "url", yybuf+yypos));
  return 1;
  l109:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "url", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_unnamed_link()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "unnamed_link"));  if (!yymatchChar('[')) goto l117;
  {  int yypos118= yypos, yythunkpos118= yythunkpos;  if (!yymatchString("javascript:")) goto l118;  goto l117;
  l118:;	  yypos= yypos118; yythunkpos= yythunkpos118;
  }  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l117;
  l119:;	
  {  int yypos120= yypos, yythunkpos120= yythunkpos;
  {  int yypos121= yypos, yythunkpos121= yythunkpos;  if (!yymatchChar(']')) goto l121;  goto l120;
  l121:;	  yypos= yypos121; yythunkpos= yythunkpos121;
  }  if (!yymatchDot()) goto l120;  goto l119;
  l120:;	  yypos= yypos120; yythunkpos= yythunkpos120;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l117;  if (!yymatchChar(']')) goto l117;  yyDo(yy_1_unnamed_link, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "unnamed_link", yybuf+yypos));
  return 1;
  l117:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "unnamed_link", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_named_link()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "named_link"));  if (!yymatchChar('[')) goto l122;
  {  int yypos123= yypos, yythunkpos123= yythunkpos;  if (!yymatchString("javascript:")) goto l123;  goto l122;
  l123:;	  yypos= yypos123; yythunkpos= yythunkpos123;
  }  yyDo(yy_1_named_link, yybegin, yyend);  if (!yy_link_url()) goto l122;  yyDo(yy_2_named_link, yybegin, yyend);  if (!yymatchChar(' ')) goto l122;
  l124:;	
  {  int yypos125= yypos, yythunkpos125= yythunkpos;  if (!yymatchChar(' ')) goto l125;  goto l124;
  l125:;	  yypos= yypos125; yythunkpos= yythunkpos125;
  }  if (!yy_link_name()) goto l122;
  l126:;	
  {  int yypos127= yypos, yythunkpos127= yythunkpos;  if (!yy_link_name()) goto l127;  goto l126;
  l127:;	  yypos= yypos127; yythunkpos= yythunkpos127;
  }
  l128:;	
  {  int yypos129= yypos, yythunkpos129= yythunkpos;  if (!yy_space()) goto l129;  goto l128;
  l129:;	  yypos= yypos129; yythunkpos= yythunkpos129;
  }  if (!yymatchChar(']')) goto l122;  yyDo(yy_3_named_link, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "named_link", yybuf+yypos));
  return 1;
  l122:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "named_link", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_blend()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "blend"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l130;
  l131:;	
  {  int yypos132= yypos, yythunkpos132= yythunkpos;
  {  int yypos133= yypos, yythunkpos133= yythunkpos;  if (!yy_space()) goto l133;  goto l132;
  l133:;	  yypos= yypos133; yythunkpos= yythunkpos133;
  }
  {  int yypos134= yypos, yythunkpos134= yythunkpos;  if (!yymatchChar('=')) goto l134;  if (!yymatchChar('=')) goto l134;
  l135:;	
  {  int yypos136= yypos, yythunkpos136= yythunkpos;  if (!yymatchChar('=')) goto l136;  goto l135;
  l136:;	  yypos= yypos136; yythunkpos= yythunkpos136;
  }  goto l132;
  l134:;	  yypos= yypos134; yythunkpos= yythunkpos134;
  }
  {  int yypos137= yypos, yythunkpos137= yythunkpos;  if (!yymatchChar('[')) goto l137;  goto l132;
  l137:;	  yypos= yypos137; yythunkpos= yythunkpos137;
  }
  {  int yypos138= yypos, yythunkpos138= yythunkpos;  if (!yy_eol()) goto l138;  goto l132;
  l138:;	  yypos= yypos138; yythunkpos= yythunkpos138;
  }
  {  int yypos139= yypos, yythunkpos139= yythunkpos;  if (!yy_eof()) goto l139;  goto l132;
  l139:;	  yypos= yypos139; yythunkpos= yythunkpos139;
  }  if (!yymatchDot()) goto l132;  goto l131;
  l132:;	  yypos= yypos132; yythunkpos= yythunkpos132;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l130;  yyDo(yy_1_blend, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "blend", yybuf+yypos));
  return 1;
  l130:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "blend", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_link_close()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "link_close"));  if (!yymatchString("]]")) goto l140;
  yyprintf((stderr, "  ok   %s @ %s\n", "link_close", yybuf+yypos));
  return 1;
  l140:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "link_close", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_rename()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "rename"));  if (!yymatchChar('|')) goto l141;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l141;
  l142:;	
  {  int yypos143= yypos, yythunkpos143= yythunkpos;
  {  int yypos144= yypos, yythunkpos144= yythunkpos;  if (!yy_link_close()) goto l144;  goto l143;
  l144:;	  yypos= yypos144; yythunkpos= yythunkpos144;
  }  if (!yymatchDot()) goto l143;  goto l142;
  l143:;	  yypos= yypos143; yythunkpos= yythunkpos143;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l141;  yyDo(yy_1_rename, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "rename", yybuf+yypos));
  return 1;
  l141:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "rename", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_link_path()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "link_path"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l145;
  l146:;	
  {  int yypos147= yypos, yythunkpos147= yythunkpos;
  {  int yypos148= yypos, yythunkpos148= yythunkpos;  if (!yy_link_close()) goto l148;  goto l147;
  l148:;	  yypos= yypos148; yythunkpos= yythunkpos148;
  }
  {  int yypos149= yypos, yythunkpos149= yythunkpos;  if (!yymatchChar('|')) goto l149;  goto l147;
  l149:;	  yypos= yypos149; yythunkpos= yythunkpos149;
  }  if (!yymatchDot()) goto l147;  goto l146;
  l147:;	  yypos= yypos147; yythunkpos= yythunkpos147;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l145;  yyDo(yy_1_link_path, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "link_path", yybuf+yypos));
  return 1;
  l145:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "link_path", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_namespace()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "namespace"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l150;
  l151:;	
  {  int yypos152= yypos, yythunkpos152= yythunkpos;
  {  int yypos153= yypos, yythunkpos153= yythunkpos;  if (!yymatchChar(':')) goto l153;  goto l152;
  l153:;	  yypos= yypos153; yythunkpos= yythunkpos153;
  }
  {  int yypos154= yypos, yythunkpos154= yythunkpos;  if (!yy_link_close()) goto l154;  goto l152;
  l154:;	  yypos= yypos154; yythunkpos= yythunkpos154;
  }  if (!yymatchDot()) goto l152;  goto l151;
  l152:;	  yypos= yypos152; yythunkpos= yythunkpos152;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l150;  if (!yymatchChar(':')) goto l150;  yyDo(yy_1_namespace, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "namespace", yybuf+yypos));
  return 1;
  l150:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "namespace", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_link_open()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "link_open"));  if (!yymatchString("[[")) goto l155;
  yyprintf((stderr, "  ok   %s @ %s\n", "link_open", yybuf+yypos));
  return 1;
  l155:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "link_open", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_external_link()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "external_link"));
  {  int yypos157= yypos, yythunkpos157= yythunkpos;  if (!yy_named_link()) goto l158;  goto l157;
  l158:;	  yypos= yypos157; yythunkpos= yythunkpos157;  if (!yy_unnamed_link()) goto l159;  goto l157;
  l159:;	  yypos= yypos157; yythunkpos= yythunkpos157;  if (!yy_url()) goto l156;
  }
  l157:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "external_link", yybuf+yypos));
  return 1;
  l156:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "external_link", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_local_link()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "local_link"));  if (!yy_link_open()) goto l160;
  {  int yypos161= yypos, yythunkpos161= yythunkpos;  if (!yymatchChar(':')) goto l161;  goto l162;
  l161:;	  yypos= yypos161; yythunkpos= yythunkpos161;
  }
  l162:;	
  {  int yypos163= yypos, yythunkpos163= yythunkpos;  if (!yy_namespace()) goto l163;  goto l164;
  l163:;	  yypos= yypos163; yythunkpos= yythunkpos163;
  }
  l164:;	  if (!yy_link_path()) goto l160;
  {  int yypos165= yypos, yythunkpos165= yythunkpos;  if (!yy_rename()) goto l165;  goto l166;
  l165:;	  yypos= yypos165; yythunkpos= yythunkpos165;
  }
  l166:;	  if (!yy_link_close()) goto l160;  if (!yy_blend()) goto l160;  yyDo(yy_1_local_link, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "local_link", yybuf+yypos));
  return 1;
  l160:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "local_link", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_pre_line()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "pre_line"));  if (!yymatchChar(' ')) goto l167;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l167;
  l168:;	
  {  int yypos169= yypos, yythunkpos169= yythunkpos;
  {  int yypos170= yypos, yythunkpos170= yythunkpos;  if (!yy_eol()) goto l170;  goto l169;
  l170:;	  yypos= yypos170; yythunkpos= yythunkpos170;
  }  if (!yymatchDot()) goto l169;  goto l168;
  l169:;	  yypos= yypos169; yythunkpos= yythunkpos169;
  }
  {  int yypos171= yypos, yythunkpos171= yythunkpos;  if (!yy_eol()) goto l172;  goto l171;
  l172:;	  yypos= yypos171; yythunkpos= yythunkpos171;  if (!yy_eof()) goto l167;
  }
  l171:;	  yyText(yybegin, yyend);  if (!(YY_END)) goto l167;  yyDo(yy_1_pre_line, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "pre_line", yybuf+yypos));
  return 1;
  l167:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "pre_line", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_italic()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "italic"));  if (!yymatchString("''")) goto l173;  yyDo(yy_1_italic, yybegin, yyend);
  l174:;	
  {  int yypos175= yypos, yythunkpos175= yythunkpos;
  {  int yypos176= yypos, yythunkpos176= yythunkpos;  if (!yymatchString("''")) goto l176;  goto l175;
  l176:;	  yypos= yypos176; yythunkpos= yythunkpos176;
  }  if (!yy_wikitext()) goto l175;  goto l174;
  l175:;	  yypos= yypos175; yythunkpos= yythunkpos175;
  }  if (!yymatchString("''")) goto l173;  yyDo(yy_2_italic, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "italic", yybuf+yypos));
  return 1;
  l173:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "italic", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_bold()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "bold"));  if (!yymatchString("'''")) goto l177;  yyDo(yy_1_bold, yybegin, yyend);
  l178:;	
  {  int yypos179= yypos, yythunkpos179= yythunkpos;
  {  int yypos180= yypos, yythunkpos180= yythunkpos;  if (!yymatchString("'''")) goto l180;  goto l179;
  l180:;	  yypos= yypos180; yythunkpos= yythunkpos180;
  }  if (!yy_wikitext()) goto l179;  goto l178;
  l179:;	  yypos= yypos179; yythunkpos= yythunkpos179;
  }  if (!yymatchString("'''")) goto l177;  yyDo(yy_2_bold, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "bold", yybuf+yypos));
  return 1;
  l177:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bold", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_bold_italic()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "bold_italic"));  if (!yymatchString("'''''")) goto l181;  yyDo(yy_1_bold_italic, yybegin, yyend);
  l182:;	
  {  int yypos183= yypos, yythunkpos183= yythunkpos;
  {  int yypos184= yypos, yythunkpos184= yythunkpos;  if (!yymatchString("'''''")) goto l184;  goto l183;
  l184:;	  yypos= yypos184; yythunkpos= yythunkpos184;
  }  if (!yy_wikitext()) goto l183;  goto l182;
  l183:;	  yypos= yypos183; yythunkpos= yythunkpos183;
  }  if (!yymatchString("'''''")) goto l181;  yyDo(yy_2_bold_italic, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "bold_italic", yybuf+yypos));
  return 1;
  l181:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bold_italic", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_numbered()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "numbered"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l185;  if (!yymatchChar('#')) goto l185;
  l186:;	
  {  int yypos187= yypos, yythunkpos187= yythunkpos;  if (!yymatchChar('#')) goto l187;  goto l186;
  l187:;	  yypos= yypos187; yythunkpos= yythunkpos187;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l185;  yyDo(yy_1_numbered, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "numbered", yybuf+yypos));
  return 1;
  l185:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "numbered", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_numbered_list_entry()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "numbered_list_entry"));  if (!yy_numbered()) goto l188;
  l189:;	
  {  int yypos190= yypos, yythunkpos190= yythunkpos;  if (!yy_space()) goto l190;  goto l189;
  l190:;	  yypos= yypos190; yythunkpos= yythunkpos190;
  }
  l191:;	
  {  int yypos192= yypos, yythunkpos192= yythunkpos;
  {  int yypos193= yypos, yythunkpos193= yythunkpos;  if (!yy_eol()) goto l193;  goto l192;
  l193:;	  yypos= yypos193; yythunkpos= yythunkpos193;
  }  if (!yy_wikitext()) goto l192;  goto l191;
  l192:;	  yypos= yypos192; yythunkpos= yythunkpos192;
  }
  {  int yypos194= yypos, yythunkpos194= yythunkpos;  if (!yy_eol()) goto l194;  goto l195;
  l194:;	  yypos= yypos194; yythunkpos= yythunkpos194;
  }
  l195:;	  yyDo(yy_1_numbered_list_entry, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "numbered_list_entry", yybuf+yypos));
  return 1;
  l188:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "numbered_list_entry", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_bullet()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "bullet"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l196;  if (!yymatchChar('*')) goto l196;
  l197:;	
  {  int yypos198= yypos, yythunkpos198= yythunkpos;  if (!yymatchChar('*')) goto l198;  goto l197;
  l198:;	  yypos= yypos198; yythunkpos= yythunkpos198;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l196;  yyDo(yy_1_bullet, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "bullet", yybuf+yypos));
  return 1;
  l196:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bullet", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_bullet_list_entry()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "bullet_list_entry"));  if (!yy_bullet()) goto l199;
  l200:;	
  {  int yypos201= yypos, yythunkpos201= yythunkpos;  if (!yy_space()) goto l201;  goto l200;
  l201:;	  yypos= yypos201; yythunkpos= yythunkpos201;
  }
  l202:;	
  {  int yypos203= yypos, yythunkpos203= yythunkpos;
  {  int yypos204= yypos, yythunkpos204= yythunkpos;  if (!yy_eol()) goto l204;  goto l203;
  l204:;	  yypos= yypos204; yythunkpos= yythunkpos204;
  }  if (!yy_wikitext()) goto l203;  goto l202;
  l203:;	  yypos= yypos203; yythunkpos= yythunkpos203;
  }
  {  int yypos205= yypos, yythunkpos205= yythunkpos;  if (!yy_eol()) goto l206;  goto l205;
  l206:;	  yypos= yypos205; yythunkpos= yythunkpos205;  if (!yy_eof()) goto l199;
  }
  l205:;	  yyDo(yy_1_bullet_list_entry, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "bullet_list_entry", yybuf+yypos));
  return 1;
  l199:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bullet_list_entry", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_numbered_list()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "numbered_list"));  yyDo(yy_1_numbered_list, yybegin, yyend);  if (!yy_numbered_list_entry()) goto l207;
  l208:;	
  {  int yypos209= yypos, yythunkpos209= yythunkpos;  if (!yy_numbered_list_entry()) goto l209;  goto l208;
  l209:;	  yypos= yypos209; yythunkpos= yythunkpos209;
  }  yyDo(yy_2_numbered_list, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "numbered_list", yybuf+yypos));
  return 1;
  l207:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "numbered_list", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_bullet_list()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "bullet_list"));  yyDo(yy_1_bullet_list, yybegin, yyend);  if (!yy_bullet_list_entry()) goto l210;
  l211:;	
  {  int yypos212= yypos, yythunkpos212= yythunkpos;  if (!yy_bullet_list_entry()) goto l212;  goto l211;
  l212:;	  yypos= yypos212; yythunkpos= yythunkpos212;
  }  yyDo(yy_2_bullet_list, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "bullet_list", yybuf+yypos));
  return 1;
  l210:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bullet_list", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_heading_text()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "heading_text"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l213;
  l214:;	
  {  int yypos215= yypos, yythunkpos215= yythunkpos;
  {  int yypos216= yypos, yythunkpos216= yythunkpos;  if (!yy_heading_marker()) goto l216;  goto l215;
  l216:;	  yypos= yypos216; yythunkpos= yythunkpos216;
  }
  {  int yypos217= yypos, yythunkpos217= yythunkpos;  if (!yy_formatting()) goto l218;  goto l217;
  l218:;	  yypos= yypos217; yythunkpos= yythunkpos217;  if (!yy_link()) goto l219;  goto l217;
  l219:;	  yypos= yypos217; yythunkpos= yythunkpos217;  if (!yy_anything_else()) goto l215;
  }
  l217:;	  goto l214;
  l215:;	  yypos= yypos215; yythunkpos= yythunkpos215;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l213;
  yyprintf((stderr, "  ok   %s @ %s\n", "heading_text", yybuf+yypos));
  return 1;
  l213:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "heading_text", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_heading_marker()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "heading_marker"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l220;  if (!yymatchChar('=')) goto l220;  if (!yymatchChar('=')) goto l220;
  l221:;	
  {  int yypos222= yypos, yythunkpos222= yythunkpos;  if (!yymatchChar('=')) goto l222;  goto l221;
  l222:;	  yypos= yypos222; yythunkpos= yythunkpos222;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l220;  yyDo(yy_1_heading_marker, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "heading_marker", yybuf+yypos));
  return 1;
  l220:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "heading_marker", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_space()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "space"));  if (!yymatchClass((unsigned char *)"\000\002\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l223;
  yyprintf((stderr, "  ok   %s @ %s\n", "space", yybuf+yypos));
  return 1;
  l223:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "space", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_eof()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "eof"));
  {  int yypos225= yypos, yythunkpos225= yythunkpos;  if (!yymatchDot()) goto l225;  goto l224;
  l225:;	  yypos= yypos225; yythunkpos= yythunkpos225;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "eof", yybuf+yypos));
  return 1;
  l224:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eof", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_eol()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "eol"));
  {  int yypos227= yypos, yythunkpos227= yythunkpos;  if (!yymatchChar('\r')) goto l227;  goto l228;
  l227:;	  yypos= yypos227; yythunkpos= yythunkpos227;
  }
  l228:;	  if (!yymatchChar('\n')) goto l226;  yyDo(yy_1_eol, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "eol", yybuf+yypos));
  return 1;
  l226:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eol", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_anything_else()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "anything_else"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l229;
  {  int yypos230= yypos, yythunkpos230= yythunkpos;  if (!yy_eol()) goto l230;  goto l229;
  l230:;	  yypos= yypos230; yythunkpos= yythunkpos230;
  }  if (!yymatchDot()) goto l229;  yyText(yybegin, yyend);  if (!(YY_END)) goto l229;  yyDo(yy_1_anything_else, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "anything_else", yybuf+yypos));
  return 1;
  l229:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "anything_else", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_table()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "table"));  if (!yymatchString("{|")) goto l231;  yyDo(yy_1_table, yybegin, yyend);  if (!yy_eol()) goto l231;  if (!yy_table_body()) goto l231;  if (!yymatchString("|}")) goto l231;
  {  int yypos232= yypos, yythunkpos232= yythunkpos;  if (!yy_eol()) goto l233;  goto l232;
  l233:;	  yypos= yypos232; yythunkpos= yythunkpos232;  if (!yy_eof()) goto l231;
  }
  l232:;	  yyDo(yy_2_table, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "table", yybuf+yypos));
  return 1;
  l231:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "table", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_link()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "link"));
  {  int yypos235= yypos, yythunkpos235= yythunkpos;  if (!yy_local_link()) goto l236;  goto l235;
  l236:;	  yypos= yypos235; yythunkpos= yythunkpos235;  if (!yy_external_link()) goto l234;
  }
  l235:;	  yyDo(yy_1_link, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "link", yybuf+yypos));
  return 1;
  l234:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "link", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_image()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "image"));  if (!yy_open_image()) goto l237;  yyDo(yy_1_image, yybegin, yyend);  if (!yy_file_indicator()) goto l237;
  {  int yypos238= yypos, yythunkpos238= yythunkpos;  if (!yy_arguments()) goto l238;  goto l239;
  l238:;	  yypos= yypos238; yythunkpos= yythunkpos238;
  }
  l239:;	  if (!yy_close_image()) goto l237;  yyDo(yy_2_image, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "image", yybuf+yypos));
  return 1;
  l237:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "image", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_formatting()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "formatting"));
  {  int yypos241= yypos, yythunkpos241= yythunkpos;  if (!yy_bold_italic()) goto l242;  goto l241;
  l242:;	  yypos= yypos241; yythunkpos= yythunkpos241;  if (!yy_bold()) goto l243;  goto l241;
  l243:;	  yypos= yypos241; yythunkpos= yythunkpos241;  if (!yy_italic()) goto l240;
  }
  l241:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "formatting", yybuf+yypos));
  return 1;
  l240:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "formatting", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_list()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "list"));
  {  int yypos245= yypos, yythunkpos245= yythunkpos;  if (!yy_bullet_list()) goto l246;  goto l245;
  l246:;	  yypos= yypos245; yythunkpos= yythunkpos245;  if (!yy_numbered_list()) goto l244;
  }
  l245:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "list", yybuf+yypos));
  return 1;
  l244:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "list", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_indentation()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "indentation"));  yyText(yybegin, yyend);  if (!( start_of_line )) goto l247;  if (!yymatchChar(':')) goto l247;  yyDo(yy_1_indentation, yybegin, yyend);  if (!yy_wikitext()) goto l247;
  yyprintf((stderr, "  ok   %s @ %s\n", "indentation", yybuf+yypos));
  return 1;
  l247:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "indentation", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_heading()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "heading"));  if (!yy_heading_marker()) goto l248;  yyDo(yy_1_heading, yybegin, yyend);
  l249:;	
  {  int yypos250= yypos, yythunkpos250= yythunkpos;  if (!yy_space()) goto l250;  goto l249;
  l250:;	  yypos= yypos250; yythunkpos= yythunkpos250;
  }  if (!yy_heading_text()) goto l248;  if (!yy_heading_marker()) goto l248;
  l251:;	
  {  int yypos252= yypos, yythunkpos252= yythunkpos;  if (!yy_space()) goto l252;  goto l251;
  l252:;	  yypos= yypos252; yythunkpos= yythunkpos252;
  }
  {  int yypos253= yypos, yythunkpos253= yythunkpos;  if (!yy_eol()) goto l254;  goto l253;
  l254:;	  yypos= yypos253; yythunkpos= yythunkpos253;  if (!yy_eof()) goto l248;
  }
  l253:;	  yyDo(yy_2_heading, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "heading", yybuf+yypos));
  return 1;
  l248:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "heading", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_template()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "template"));  if (!yymatchString("{{")) goto l255;
  l256:;	
  {  int yypos257= yypos, yythunkpos257= yythunkpos;  if (!yy_space()) goto l257;  goto l256;
  l257:;	  yypos= yypos257; yythunkpos= yythunkpos257;
  }
  l258:;	
  {  int yypos259= yypos, yythunkpos259= yythunkpos;
  {  int yypos260= yypos, yythunkpos260= yythunkpos;  if (!yymatchString("}}")) goto l260;  goto l259;
  l260:;	  yypos= yypos260; yythunkpos= yythunkpos260;
  }  if (!yymatchDot()) goto l259;  goto l258;
  l259:;	  yypos= yypos259; yythunkpos= yythunkpos259;
  }  if (!yymatchString("}}")) goto l255;  yyDo(yy_1_template, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "template", yybuf+yypos));
  return 1;
  l255:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "template", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_table_of_contents()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "table_of_contents"));
  {  int yypos262= yypos, yythunkpos262= yythunkpos;  if (!yy_notoc()) goto l263;  goto l262;
  l263:;	  yypos= yypos262; yythunkpos= yythunkpos262;  if (!yy_toc()) goto l264;  goto l262;
  l264:;	  yypos= yypos262; yythunkpos= yythunkpos262;  if (!yy_forcetoc()) goto l261;
  }
  l262:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "table_of_contents", yybuf+yypos));
  return 1;
  l261:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "table_of_contents", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_horizontal_line()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "horizontal_line"));  if (!yymatchString("----")) goto l265;
  {  int yypos266= yypos, yythunkpos266= yythunkpos;  if (!yy_eol()) goto l267;  goto l266;
  l267:;	  yypos= yypos266; yythunkpos= yythunkpos266;  if (!yy_eof()) goto l265;
  }
  l266:;	  yyDo(yy_1_horizontal_line, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "horizontal_line", yybuf+yypos));
  return 1;
  l265:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "horizontal_line", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_paragraph()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "paragraph"));  if (!yy_wikitext()) goto l268;  if (!yy_eol()) goto l268;  if (!yy_eol()) goto l268;  yyDo(yy_1_paragraph, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "paragraph", yybuf+yypos));
  return 1;
  l268:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "paragraph", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_wikitext()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "wikitext"));
  {  int yypos270= yypos, yythunkpos270= yythunkpos;  if (!yy_table_of_contents()) goto l271;  goto l270;
  l271:;	  yypos= yypos270; yythunkpos= yythunkpos270;  if (!yy_template()) goto l272;  goto l270;
  l272:;	  yypos= yypos270; yythunkpos= yythunkpos270;  if (!yy_heading()) goto l273;  goto l270;
  l273:;	  yypos= yypos270; yythunkpos= yythunkpos270;  if (!yy_indentation()) goto l274;  goto l270;
  l274:;	  yypos= yypos270; yythunkpos= yythunkpos270;  if (!yy_list()) goto l275;  goto l270;
  l275:;	  yypos= yypos270; yythunkpos= yythunkpos270;  if (!yy_formatting()) goto l276;  goto l270;
  l276:;	  yypos= yypos270; yythunkpos= yythunkpos270;  if (!yy_image()) goto l277;  goto l270;
  l277:;	  yypos= yypos270; yythunkpos= yythunkpos270;  if (!yy_link()) goto l278;  goto l270;
  l278:;	  yypos= yypos270; yythunkpos= yythunkpos270;  if (!yy_table()) goto l279;  goto l270;
  l279:;	  yypos= yypos270; yythunkpos= yythunkpos270;  if (!yy_anything_else()) goto l280;  goto l270;
  l280:;	  yypos= yypos270; yythunkpos= yythunkpos270;  if (!yy_eol()) goto l269;
  }
  l270:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "wikitext", yybuf+yypos));
  return 1;
  l269:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "wikitext", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_wikitext_line()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "wikitext_line"));
  {  int yypos282= yypos, yythunkpos282= yythunkpos;  if (!yy_paragraph()) goto l283;  goto l282;
  l283:;	  yypos= yypos282; yythunkpos= yythunkpos282;  if (!yy_horizontal_line()) goto l281;
  }
  l282:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "wikitext_line", yybuf+yypos));
  return 1;
  l281:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "wikitext_line", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_pre_block()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "pre_block"));  yyText(yybegin, yyend);  if (!( start_of_line )) goto l284;  yyDo(yy_1_pre_block, yybegin, yyend);  if (!yy_pre_line()) goto l284;
  l285:;	
  {  int yypos286= yypos, yythunkpos286= yythunkpos;  if (!yy_pre_line()) goto l286;  goto l285;
  l286:;	  yypos= yypos286; yythunkpos= yythunkpos286;
  }  yyDo(yy_2_pre_block, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "pre_block", yybuf+yypos));
  return 1;
  l284:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "pre_block", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_html()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "html"));  if (!yymatchChar('<')) goto l287;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l287;
  {  int yypos288= yypos, yythunkpos288= yythunkpos;  if (!yymatchChar('/')) goto l288;  goto l289;
  l288:;	  yypos= yypos288; yythunkpos= yythunkpos288;
  }
  l289:;	
  {  int yypos292= yypos, yythunkpos292= yythunkpos;  if (!yymatchChar('>')) goto l292;  goto l287;
  l292:;	  yypos= yypos292; yythunkpos= yythunkpos292;
  }  if (!yymatchDot()) goto l287;
  l290:;	
  {  int yypos291= yypos, yythunkpos291= yythunkpos;
  {  int yypos293= yypos, yythunkpos293= yythunkpos;  if (!yymatchChar('>')) goto l293;  goto l291;
  l293:;	  yypos= yypos293; yythunkpos= yythunkpos293;
  }  if (!yymatchDot()) goto l291;  goto l290;
  l291:;	  yypos= yypos291; yythunkpos= yythunkpos291;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l287;
  {  int yypos294= yypos, yythunkpos294= yythunkpos;  if (!yymatchChar('/')) goto l294;  goto l295;
  l294:;	  yypos= yypos294; yythunkpos= yythunkpos294;
  }
  l295:;	  if (!yymatchChar('>')) goto l287;  yyDo(yy_1_html, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "html", yybuf+yypos));
  return 1;
  l287:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "html", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_nowiki()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "nowiki"));  if (!yymatchString("<nowiki>")) goto l296;
  l297:;	
  {  int yypos298= yypos, yythunkpos298= yythunkpos;
  {  int yypos299= yypos, yythunkpos299= yythunkpos;  if (!yymatchString("</nowiki>")) goto l299;  goto l298;
  l299:;	  yypos= yypos299; yythunkpos= yythunkpos299;
  }  if (!yy_anything_else()) goto l298;  goto l297;
  l298:;	  yypos= yypos298; yythunkpos= yythunkpos298;
  }  if (!yymatchString("</nowiki>")) goto l296;
  yyprintf((stderr, "  ok   %s @ %s\n", "nowiki", yybuf+yypos));
  return 1;
  l296:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "nowiki", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_page()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "page"));
  {  int yypos301= yypos, yythunkpos301= yythunkpos;  if (!yy_nowiki()) goto l302;  goto l301;
  l302:;	  yypos= yypos301; yythunkpos= yythunkpos301;  if (!yy_html()) goto l303;  goto l301;
  l303:;	  yypos= yypos301; yythunkpos= yythunkpos301;  if (!yy_pre_block()) goto l304;  goto l301;
  l304:;	  yypos= yypos301; yythunkpos= yythunkpos301;  if (!yy_wikitext_line()) goto l305;  goto l301;
  l305:;	  yypos= yypos301; yythunkpos= yythunkpos301;  if (!yy_wikitext()) goto l300;
  }
  l301:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "page", yybuf+yypos));
  return 1;
  l300:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "page", yybuf+yypos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)();

YY_PARSE(int) YYPARSEFROM(yyrule yystart)
{
  int yyok;
  if (!yybuflen)
    {
      yybuflen= 1024;
      yybuf= malloc(yybuflen);
      yytextlen= 1024;
      yytext= malloc(yytextlen);
      yythunkslen= 32;
      yythunks= malloc(sizeof(yythunk) * yythunkslen);
      yyvalslen= 32;
      yyvals= malloc(sizeof(YYSTYPE) * yyvalslen);
      yybegin= yyend= yypos= yylimit= yythunkpos= 0;
    }
  yybegin= yyend= yypos;
  yythunkpos= 0;
  yyval= yyvals;
  yyok= yystart();
  if (yyok) yyDone();
  yyCommit();
  return yyok;
  (void)yyrefill;
  (void)yymatchDot;
  (void)yymatchChar;
  (void)yymatchString;
  (void)yymatchClass;
  (void)yyDo;
  (void)yyText;
  (void)yyDone;
  (void)yyCommit;
  (void)yyAccept;
  (void)yyPush;
  (void)yyPop;
  (void)yySet;
  (void)yytextmax;
}

YY_PARSE(int) YYPARSE(void)
{
  return YYPARSEFROM(yy_page);
}

#endif


void set_output_buffer(bstring buffer) {
  output_buffer = buffer;
}

void set_input_buffer(bstring buffer) {
  input_buffer = buffer;
}

void init() {
  current_header_level = 0;
  start_of_line = 1;
  image_attributes = 0;
  toc_attributes = 0;
  in_tag = 0;
  bstring output_buffer = NULL;
  bstring input_buffer = NULL;
  input_buffer_pos = 0;

  list_init(&list);
  tag_content = bfromcstr("");
  ballocmin(tag_content, tag_content_size);

  image_variables = bfromcstr("");
  image_url = bfromcstr("");

  link_path = bfromcstr("");
  link_text = bfromcstr("");

  output_buffer = bfromcstr("");
  input_buffer = bfromcstr("");
  ballocmin(output_buffer, 1 * MBYTE);
}

void cleanup() {
  bdestroy(tag_content);
  bdestroy(image_variables);
  bdestroy(image_url);
  bdestroy(link_path);
  bdestroy(link_text);

  list_free(&list);
}

void parse(bstring inputbuffer, bstring outbuffer) {
  init();
  set_output_buffer(outbuffer);
  set_input_buffer(inputbuffer);

  bprintf("<p>");
  while(yyparse()) {}
  bprintf("</p>");
  handle_toc();

  cleanup();
}

int main() {
  bstring output = bfromcstr("");
  bstring input = bfromcstr("");
  //file_get_contents(input, "spec/fixtures/cnn.com");
  stdin_get_contents(input);
  parse(input, output);
  printf("%s", bdata(output));
  bdestroy(output);
  return 0;
}

