/* A recursive-descent parser generated by peg 0.1.2 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 68

#include <stdio.h>
#include <signal.h>
#include <time.h>
#include <stdarg.h>
#include <stdbool.h>
#include <ctype.h>
#include "bstrlib.h"
#include "list.h"
#include "content.h"
#include "common.h"
#include "io.h"

#define YY_noDEBUG 1

#define IMAGE_FRAME 1
#define IMAGE_THUMB ( 1 << 1 )
#define IMAGE_NOLINK ( 1 << 2 )
#define IMAGE_CUSTOMLINK ( 1 << 3 )
#define IMAGE_HAS_CAPTION ( 1 << 4 )

#define TOC_NOTOC ( 1 << 1 )
#define TOC_FORCETOC ( 1 << 2 )
#define TOC_RELOC ( 1 << 3 )

#define YY_INPUT(buf, result, max_size) handle_input(buf, &result, max_size)

int current_header_level = 0;
int current_bullet_list_level;
int current_numbered_list_level;

int start_of_line = 1;
char protocol[5];

int image_attributes = 0;
bstring image_url;
bstring image_variables;
bstring image_link_url;
bstring image_caption;

bstring link_path;
bstring link_text;

int toc_attributes = 0;

int in_tag = 0;
bstring tag_content;
unsigned int tag_content_size = 2 * MBYTE;

bstring output_buffer = NULL;
bstring input_buffer = NULL;
long input_buffer_pos = 0;

struct list list;

// Render the ToC from a list, output to buffer
void assemble_toc(struct node *item, bstring toc_buffer) {
  if(!item) {
    printf("Bad list passed to assemble_toc\n");
    return;
  }

  struct node *next;
  int previous_level = item->level;
  int total_layers = 0;
  int i;
  bformata(toc_buffer, "%s", "<div id=\"toc\" class=\"toc\">\n<div id=\"toctitle\">Contents</div>\n<ol>\n");
  while(item != NULL) {
    next = item->next;

    // Layer the list deeper as necessary
    if(item->level > previous_level) {
      repeat_append(toc_buffer, ' ', (total_layers + 1) * 2);
      for(i = previous_level; i < item->level; i++) {
        bformata(toc_buffer, "%s", "<ol>\n");
        total_layers++;
      }
    } else if((item->level < previous_level) && (total_layers > 1)) {
      for(i = previous_level; i > item->level; i--) {
        repeat_append(toc_buffer, ' ', (total_layers) * 2);
        bformata(toc_buffer, "%s", "</ol>\n");
        total_layers--;
      }
    }

    // Add the item
    if(item->name && item->content) {
      repeat_append(toc_buffer, ' ', (total_layers + 1) * 2);
      bformata(toc_buffer, "  <li><a href=\"#%s\">%s</a></li>\n", bdata(item->name), bdata(item->content));
    }
    previous_level = item->level;
    item = next;
  }

  // Clean up lists left open
  while(total_layers > 0) {
    bformata(toc_buffer, "%s", "</ol>\n");
    total_layers--;
  }
  bformata(toc_buffer, "%s", "</ol>\n</div>\n");
}

// Insert the ToC into the output buffer in place of the __TOC__ tag
void insert_reloc_toc(bstring toc_buffer) {
  bstring find = bfromcstr("__TOC__");
  if(bfindreplace(output_buffer, find, toc_buffer, 0) == BSTR_ERR) {
    printf("Error inserting toc_buffer into output_buffer\n");
  }
  bdestroy(find);
}

// Main ToC routine
void handle_toc() {
  if(toc_attributes & TOC_NOTOC) {
    return;
  }

  if((list.size > 3) || (toc_attributes & TOC_FORCETOC)) {
    bstring toc_buffer = bfromcstr("");
    assemble_toc(list.head->next, toc_buffer);

    if(toc_attributes & TOC_RELOC) {
      insert_reloc_toc(toc_buffer);
      bdestroy(toc_buffer);
      return;
    }

    if(binsert(output_buffer, 0, toc_buffer, ' ') != BSTR_OK) {
      printf("Error prepending toc_buffer to output_buffer\n");
    }
    bdestroy(toc_buffer);
  }
}

void open_tag(char *tag, char *args) {
  if(args) {
    bprintf("<%s %s>", tag, args);
  } else {
    bprintf("<%s>", tag);
  }

  in_tag = 1;
  if(tag_content) {
    btrunc(tag_content,0 );
  }
}

void close_tag(char *tag) {
  bprintf("</%s>", tag);
  in_tag = 0;
}

void append_to_tag_content(char *fmt, ...) {
  int ret;

  if(!in_tag) {
    bvformata(ret, output_buffer, fmt, fmt);
    return;
  }

  bvformata(ret, tag_content, fmt, fmt);
}


#ifndef YY_VARIABLE
#define YY_VARIABLE(T)	static T
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yybegin= yypos, 1)
#endif
#ifndef YY_END
#define YY_END		( yyend= yypos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif

#ifndef YY_PART

typedef void (*yyaction)(char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

YY_VARIABLE(char *   ) yybuf= 0;
YY_VARIABLE(int	     ) yybuflen= 0;
YY_VARIABLE(int	     ) yypos= 0;
YY_VARIABLE(int	     ) yylimit= 0;
YY_VARIABLE(char *   ) yytext= 0;
YY_VARIABLE(int	     ) yytextlen= 0;
YY_VARIABLE(int	     ) yybegin= 0;
YY_VARIABLE(int	     ) yyend= 0;
YY_VARIABLE(int	     ) yytextmax= 0;
YY_VARIABLE(yythunk *) yythunks= 0;
YY_VARIABLE(int	     ) yythunkslen= 0;
YY_VARIABLE(int      ) yythunkpos= 0;
YY_VARIABLE(YYSTYPE  ) yy;
YY_VARIABLE(YYSTYPE *) yyval= 0;
YY_VARIABLE(YYSTYPE *) yyvals= 0;
YY_VARIABLE(int      ) yyvalslen= 0;

YY_LOCAL(int) yyrefill(void)
{
  int yyn;
  while (yybuflen - yypos < 512)
    {
      yybuflen *= 2;
      yybuf= realloc(yybuf, yybuflen);
    }
  YY_INPUT((yybuf + yypos), yyn, (yybuflen - yypos));
  if (!yyn) return 0;
  yylimit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(void)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  ++yypos;
  return 1;
}

YY_LOCAL(int) yymatchChar(int c)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  if (yybuf[yypos] == c)
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchChar(%c) @ %s\n", c, yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(%c) @ %s\n", c, yybuf+yypos));
  return 0;
}

YY_LOCAL(int) yymatchString(char *s)
{
  int yysav= yypos;
  while (*s)
    {
      if (yypos >= yylimit && !yyrefill()) return 0;
      if (yybuf[yypos] != *s)
        {
          yypos= yysav;
          return 0;
        }
      ++s;
      ++yypos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(unsigned char *bits)
{
  int c;
  if (yypos >= yylimit && !yyrefill()) return 0;
  c= yybuf[yypos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yybuf+yypos));
  return 0;
}

YY_LOCAL(void) yyDo(yyaction action, int begin, int end)
{
  while (yythunkpos >= yythunkslen)
    {
      yythunkslen *= 2;
      yythunks= realloc(yythunks, sizeof(yythunk) * yythunkslen);
    }
  yythunks[yythunkpos].begin=  begin;
  yythunks[yythunkpos].end=    end;
  yythunks[yythunkpos].action= action;
  ++yythunkpos;
}

YY_LOCAL(int) yyText(int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yytextlen < (yyleng - 1))
	{
	  yytextlen *= 2;
	  yytext= realloc(yytext, yytextlen);
	}
      memcpy(yytext, yybuf + begin, yyleng);
    }
  yytext[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(void)
{
  int pos;
  for (pos= 0;  pos < yythunkpos;  ++pos)
    {
      yythunk *thunk= &yythunks[pos];
      int yyleng= thunk->end ? yyText(thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yytext));
      thunk->action(yytext, yyleng);
    }
  yythunkpos= 0;
}

YY_LOCAL(void) yyCommit()
{
  if ((yylimit -= yypos))
    {
      memmove(yybuf, yybuf + yypos, yylimit);
    }
  yybegin -= yypos;
  yyend -= yypos;
  yypos= yythunkpos= 0;
}

YY_LOCAL(int) yyAccept(int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone();
      yyCommit();
    }
  return 1;
}

YY_LOCAL(void) yyPush(char *text, int count)	{ yyval += count; }
YY_LOCAL(void) yyPop(char *text, int count)	{ yyval -= count; }
YY_LOCAL(void) yySet(char *text, int count)	{ yyval[count]= yy; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yythunkpos0)

YY_RULE(int) yy_forcetoc(); /* 68 */
YY_RULE(int) yy_toc(); /* 67 */
YY_RULE(int) yy_notoc(); /* 66 */
YY_RULE(int) yy_table_cell(); /* 65 */
YY_RULE(int) yy_table_heading(); /* 64 */
YY_RULE(int) yy_table_row(); /* 63 */
YY_RULE(int) yy_table_header(); /* 62 */
YY_RULE(int) yy_table_caption(); /* 61 */
YY_RULE(int) yy_table_body(); /* 60 */
YY_RULE(int) yy_thumb(); /* 59 */
YY_RULE(int) yy_frame(); /* 58 */
YY_RULE(int) yy_image_link(); /* 57 */
YY_RULE(int) yy_float(); /* 56 */
YY_RULE(int) yy_image_type(); /* 55 */
YY_RULE(int) yy_value(); /* 54 */
YY_RULE(int) yy_generic_variable(); /* 53 */
YY_RULE(int) yy_special_image_variables(); /* 52 */
YY_RULE(int) yy_close_image(); /* 51 */
YY_RULE(int) yy_image_caption(); /* 50 */
YY_RULE(int) yy_arguments(); /* 49 */
YY_RULE(int) yy_file_indicator(); /* 48 */
YY_RULE(int) yy_open_image(); /* 47 */
YY_RULE(int) yy_link_name(); /* 46 */
YY_RULE(int) yy_link_url(); /* 45 */
YY_RULE(int) yy_url(); /* 44 */
YY_RULE(int) yy_unnamed_link(); /* 43 */
YY_RULE(int) yy_named_link(); /* 42 */
YY_RULE(int) yy_blend(); /* 41 */
YY_RULE(int) yy_link_close(); /* 40 */
YY_RULE(int) yy_rename(); /* 39 */
YY_RULE(int) yy_link_path(); /* 38 */
YY_RULE(int) yy_namespace(); /* 37 */
YY_RULE(int) yy_link_open(); /* 36 */
YY_RULE(int) yy_external_link(); /* 35 */
YY_RULE(int) yy_local_link(); /* 34 */
YY_RULE(int) yy_pre_line(); /* 33 */
YY_RULE(int) yy_italic(); /* 32 */
YY_RULE(int) yy_bold(); /* 31 */
YY_RULE(int) yy_bold_italic(); /* 30 */
YY_RULE(int) yy_numbered(); /* 29 */
YY_RULE(int) yy_numbered_list_entry(); /* 28 */
YY_RULE(int) yy_bullet(); /* 27 */
YY_RULE(int) yy_bullet_list_entry(); /* 26 */
YY_RULE(int) yy_numbered_list(); /* 25 */
YY_RULE(int) yy_bullet_list(); /* 24 */
YY_RULE(int) yy_heading_text(); /* 23 */
YY_RULE(int) yy_heading_marker(); /* 22 */
YY_RULE(int) yy_space(); /* 21 */
YY_RULE(int) yy_eof(); /* 20 */
YY_RULE(int) yy_eol(); /* 19 */
YY_RULE(int) yy_anything_else(); /* 18 */
YY_RULE(int) yy_table(); /* 17 */
YY_RULE(int) yy_link(); /* 16 */
YY_RULE(int) yy_image(); /* 15 */
YY_RULE(int) yy_formatting(); /* 14 */
YY_RULE(int) yy_list(); /* 13 */
YY_RULE(int) yy_indentation(); /* 12 */
YY_RULE(int) yy_heading(); /* 11 */
YY_RULE(int) yy_template(); /* 10 */
YY_RULE(int) yy_table_of_contents(); /* 9 */
YY_RULE(int) yy_horizontal_line(); /* 8 */
YY_RULE(int) yy_paragraph(); /* 7 */
YY_RULE(int) yy_wikitext(); /* 6 */
YY_RULE(int) yy_wikitext_line(); /* 5 */
YY_RULE(int) yy_pre_block(); /* 4 */
YY_RULE(int) yy_html(); /* 3 */
YY_RULE(int) yy_nowiki(); /* 2 */
YY_RULE(int) yy_page(); /* 1 */

YY_ACTION(void) yy_1_anything_else(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_anything_else\n"));
   start_of_line = 0; append_to_tag_content(yytext); ;
}
YY_ACTION(void) yy_1_html(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_html\n"));
   
  if(valid_html_tag(yytext, yyleng)) { 
    bstring b = bfromcstr(yytext);
    btolower(b);
    bprintf("<%s>", bdata(b));
    bdestroy(b);
  } else {
    bprintf("&lt;%s&gt;", yytext); 
  }
  start_of_line = 0;
;
}
YY_ACTION(void) yy_1_toc(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_toc\n"));
   toc_attributes |= TOC_RELOC; bprintf("__TOC__"); // pass-through for later replacement ;
}
YY_ACTION(void) yy_1_forcetoc(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_forcetoc\n"));
   toc_attributes |= TOC_FORCETOC; ;
}
YY_ACTION(void) yy_1_notoc(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_notoc\n"));
   toc_attributes |= TOC_NOTOC; ;
}
YY_ACTION(void) yy_1_template(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_template\n"));
   start_of_line = 0; ;
}
YY_ACTION(void) yy_3_table_heading(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_3_table_heading\n"));
  bprintf("%s</th>", yytext); ;
}
YY_ACTION(void) yy_2_table_heading(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_table_heading\n"));
   bprintf(" %s>", yytext); ;
}
YY_ACTION(void) yy_1_table_heading(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_table_heading\n"));
   bprintf("<th"); ;
}
YY_ACTION(void) yy_2_table_header(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_table_header\n"));
   bprintf("</tr>"); ;
}
YY_ACTION(void) yy_1_table_header(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_table_header\n"));
   bprintf("<tr>"); ;
}
YY_ACTION(void) yy_2_table_cell(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_table_cell\n"));
   bprintf("%s</td>", yytext); ;
}
YY_ACTION(void) yy_1_table_cell(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_table_cell\n"));
   bprintf("<td>"); ;
}
YY_ACTION(void) yy_2_table_row(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_table_row\n"));
   bprintf("</tr>"); ;
}
YY_ACTION(void) yy_1_table_row(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_table_row\n"));
   bprintf("<tr>"); ;
}
YY_ACTION(void) yy_1_table_caption(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_table_caption\n"));
   bprintf("<caption>%s</caption>", yytext); ;
}
YY_ACTION(void) yy_2_table(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_table\n"));
   bprintf("</table>"); ;
}
YY_ACTION(void) yy_1_table(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_table\n"));
   bprintf("<table>"); ;
}
YY_ACTION(void) yy_1_image_caption(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_image_caption\n"));
  
  image_attributes |= IMAGE_HAS_CAPTION;
  bassignformat(image_caption, "%s", yytext);
;
}
YY_ACTION(void) yy_1_value(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_value\n"));
  
  bformata(image_variables, "=\"%s\"", yytext);
;
}
YY_ACTION(void) yy_1_generic_variable(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_generic_variable\n"));
   
  bformata(image_variables, "%s", yytext);
;
}
YY_ACTION(void) yy_1_image_link(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_image_link\n"));
  
  if(strcmp(yytext, "") == 0) {
    image_attributes |= IMAGE_NOLINK;
  } else {
    image_attributes |= IMAGE_CUSTOMLINK;
    bassignformat(image_link_url, "%s", yytext);
  }
;
}
YY_ACTION(void) yy_1_float(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_float\n"));
   
  bformata(image_variables, " class=\"float%s\"", yytext);
;
}
YY_ACTION(void) yy_1_thumb(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_thumb\n"));
   image_attributes |= IMAGE_THUMB; ;
}
YY_ACTION(void) yy_1_frame(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_frame\n"));
   image_attributes |= IMAGE_FRAME; ;
}
YY_ACTION(void) yy_1_file_indicator(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_file_indicator\n"));
   bassignformat(image_url, "%s", yytext); ;
}
YY_ACTION(void) yy_2_image(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_image\n"));
  
  if(image_attributes & IMAGE_FRAME) {
    bprintf("<div class=\"thumb tright\"><div class=\"thumbinner\">");
  }

  if(!(image_attributes & IMAGE_NOLINK)) {
    if(image_attributes & IMAGE_CUSTOMLINK)
      bprintf("<a href=\"%s\" class=\"image\">", bdata(image_link_url));
    else
      if(image_attributes & IMAGE_HAS_CAPTION)
        bprintf("<a href=\"File:%s\" class=\"image\" title=\"%s\">", bdata(image_url), bdata(image_caption));
      else
        bprintf("<a href=\"File:%s\" class=\"image\">", bdata(image_url));
  }

  if(image_attributes & IMAGE_THUMB) {
    bprintf("<img src=\"%s\" width=\"220\" height=\"30\" class=\"thumbimage\"/>", bdata(image_url));
  } else if(image_attributes & IMAGE_FRAME) {
    bprintf("<img src=\"%s\" class=\"thumbimage\"/>", bdata(image_url));
  } else {
    bprintf("<img src=\"%s\" %s/>", bdata(image_url), bdata(image_variables));
  }
  if(!(image_attributes & IMAGE_NOLINK)) {
    bprintf("</a>");
  }

  if(image_attributes & IMAGE_FRAME) {
    bprintf("<div class=\"thumbcaption\">%s</div></div>", bdata(image_caption));
  }
;
}
YY_ACTION(void) yy_1_image(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_image\n"));
   btrunc(image_variables, 0); ;
}
YY_ACTION(void) yy_2_url(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_url\n"));
   append_to_tag_content("<a href=\"%s://%s\">%s://%s</a>", protocol, yytext, protocol, yytext); ;
}
YY_ACTION(void) yy_1_url(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_url\n"));
   strcpy(protocol, yytext); ;
}
YY_ACTION(void) yy_1_unnamed_link(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_unnamed_link\n"));
   append_to_tag_content("<a href=\"%s\">%s</a>", yytext, yytext);;
}
YY_ACTION(void) yy_1_link_name(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_link_name\n"));
   append_to_tag_content(yytext); ;
}
YY_ACTION(void) yy_1_link_url(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_link_url\n"));
   append_to_tag_content(yytext); ;
}
YY_ACTION(void) yy_3_named_link(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_3_named_link\n"));
  append_to_tag_content("</a>"); ;
}
YY_ACTION(void) yy_2_named_link(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_named_link\n"));
   append_to_tag_content("\">");;
}
YY_ACTION(void) yy_1_named_link(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_named_link\n"));
   append_to_tag_content("<a href=\""); ;
}
YY_ACTION(void) yy_1_blend(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_blend\n"));
   bcatcstr(link_text, yytext); ;
}
YY_ACTION(void) yy_1_rename(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_rename\n"));
   btrunc(link_text, 0); bcatcstr(link_text,yytext); ;
}
YY_ACTION(void) yy_1_link_path(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_link_path\n"));
   bcatcstr(link_path, yytext); bcatcstr(link_text, yytext); ;
}
YY_ACTION(void) yy_1_namespace(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_namespace\n"));
   bcatcstr(link_path, yytext); bconchar(link_path, ':'); ;
}
YY_ACTION(void) yy_1_local_link(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_local_link\n"));
  
  strip_html_markup(link_path);
  urlencode(link_path);
  remove_parentheticals(link_text);
  btrimws(link_text);
  append_to_tag_content("<a href=\"/%s\">%s</a>", bdata(link_path), bdata(link_text));
  btrunc(link_path, 0);
  btrunc(link_text, 0);
  ;
}
YY_ACTION(void) yy_1_link(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_link\n"));
   start_of_line = 0; ;
}
YY_ACTION(void) yy_1_pre_line(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_pre_line\n"));
   bprintf("%s", yytext); ;
}
YY_ACTION(void) yy_2_pre_block(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_pre_block\n"));
   bprintf("</pre>"); ;
}
YY_ACTION(void) yy_1_pre_block(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_pre_block\n"));
   bprintf("<pre>"); ;
}
YY_ACTION(void) yy_2_italic(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_italic\n"));
   append_to_tag_content("</i>"); ;
}
YY_ACTION(void) yy_1_italic(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_italic\n"));
   append_to_tag_content("<i>"); ;
}
YY_ACTION(void) yy_2_bold(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_bold\n"));
   append_to_tag_content("</b>"); ;
}
YY_ACTION(void) yy_1_bold(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_bold\n"));
   append_to_tag_content("<b>"); ;
}
YY_ACTION(void) yy_2_bold_italic(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_bold_italic\n"));
   append_to_tag_content("</i></b>"); ;
}
YY_ACTION(void) yy_1_bold_italic(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_bold_italic\n"));
   append_to_tag_content("<b><i>"); ;
}
YY_ACTION(void) yy_1_numbered(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_numbered\n"));
  
  start_of_line = 0;
  if(current_numbered_list_level < yyleng && current_numbered_list_level != 0) {
    bprintf("<ol>");
  } else if(current_numbered_list_level > yyleng) {
    bprintf("</ol>");
  }
  current_numbered_list_level = yyleng; 
  bprintf("<li>"); 
;
}
YY_ACTION(void) yy_1_numbered_list_entry(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_numbered_list_entry\n"));
   bprintf("</li>"); ;
}
YY_ACTION(void) yy_2_numbered_list(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_numbered_list\n"));
   while(current_numbered_list_level--) { bprintf("</ol>"); } ;
}
YY_ACTION(void) yy_1_numbered_list(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_numbered_list\n"));
   bprintf("<ol>"); ;
}
YY_ACTION(void) yy_1_bullet(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_bullet\n"));
  
  start_of_line = 0;
  if(current_bullet_list_level < yyleng && current_bullet_list_level != 0) {
    bprintf("<ul>");
  } else if(current_bullet_list_level > yyleng) {
    bprintf("</ul>");
  }
  current_bullet_list_level = yyleng; 
  bprintf("<li>"); 
;
}
YY_ACTION(void) yy_1_bullet_list_entry(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_bullet_list_entry\n"));
   bprintf("</li>"); ;
}
YY_ACTION(void) yy_2_bullet_list(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_bullet_list\n"));
   
  while((current_bullet_list_level > 0) && current_bullet_list_level--) { 
    bprintf("</ul>"); 
  }
;
}
YY_ACTION(void) yy_1_bullet_list(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_bullet_list\n"));
   bprintf("<ul>"); ;
}
YY_ACTION(void) yy_1_indentation(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_indentation\n"));
   bprintf("&nbsp;&nbsp;"); ;
}
YY_ACTION(void) yy_1_horizontal_line(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_horizontal_line\n"));
   bprintf("<hr/>"); ;
}
YY_ACTION(void) yy_1_paragraph(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_paragraph\n"));
   bprintf("</p><p>"); ;
}
YY_ACTION(void) yy_1_heading_marker(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_heading_marker\n"));
   if(current_header_level == 0) current_header_level = (yyleng > 5) ? 5 : yyleng; ;
}
YY_ACTION(void) yy_2_heading(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_heading\n"));
  
    brtrimws(tag_content);
    bstring tmp = bstrcpy(tag_content);
    strip_html_markup(tmp);
    urlencode(tmp);
    bprintf("<span class=\"editsection\">[<a href=\"edit\">edit</a>]</span><span class=\"mw-headline\" id=\"%s\">", bdata(tmp));
    bdestroy(tmp);

    bprintf("%s</span>", bdata(tag_content));
    char tag[4];
    sprintf(tag, "h%d", current_header_level);
    close_tag(tag);

    struct node *current = list_get_new_tail(&list);

    tmp = bstrcpy(tag_content);
    strip_html_markup(tmp);
    urlencode(tmp);
    bprintf("<a name=\"%s\"></a>", bdata(tmp));
    bassign(current->name, tmp);

    bstring human_name = bstrcpy(tag_content);
    strip_tags(human_name);
    brtrimws(human_name);
    bassign(current->content, human_name);
    current->level = current_header_level;

    bdestroy(tmp);
    bdestroy(human_name);

    btrunc(tag_content, 0);
    current_header_level = 0;
  ;
}
YY_ACTION(void) yy_1_heading(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_heading\n"));
  
    char tag[4];
    sprintf(tag, "h%d", current_header_level);
    open_tag(tag, NULL);
  ;
}
YY_ACTION(void) yy_1_eol(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_eol\n"));
   start_of_line = 1; ;
}

YY_RULE(int) yy_forcetoc()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "forcetoc"));  if (!yymatchString("__FORCETOC__")) goto l1;  yyDo(yy_1_forcetoc, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "forcetoc", yybuf+yypos));
  return 1;
  l1:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "forcetoc", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_toc()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "toc"));  if (!yymatchString("__TOC__")) goto l2;  yyDo(yy_1_toc, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "toc", yybuf+yypos));
  return 1;
  l2:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "toc", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_notoc()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "notoc"));  if (!yymatchString("__NOTOC__")) goto l3;  yyDo(yy_1_notoc, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "notoc", yybuf+yypos));
  return 1;
  l3:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "notoc", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_table_cell()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "table_cell"));
  {  int yypos5= yypos, yythunkpos5= yythunkpos;  if (!yymatchChar('|')) goto l5;  goto l6;
  l5:;	  yypos= yypos5; yythunkpos= yythunkpos5;
  }
  l6:;	  yyDo(yy_1_table_cell, yybegin, yyend);  if (!yymatchChar(' ')) goto l4;
  l7:;	
  {  int yypos8= yypos, yythunkpos8= yythunkpos;  if (!yymatchChar(' ')) goto l8;  goto l7;
  l8:;	  yypos= yypos8; yythunkpos= yythunkpos8;
  }  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l4;
  l9:;	
  {  int yypos10= yypos, yythunkpos10= yythunkpos;
  {  int yypos11= yypos, yythunkpos11= yythunkpos;  if (!yymatchString("||")) goto l11;  goto l10;
  l11:;	  yypos= yypos11; yythunkpos= yythunkpos11;
  }
  {  int yypos12= yypos, yythunkpos12= yythunkpos;  if (!yy_eol()) goto l12;  goto l10;
  l12:;	  yypos= yypos12; yythunkpos= yythunkpos12;
  }  if (!yymatchDot()) goto l10;  goto l9;
  l10:;	  yypos= yypos10; yythunkpos= yythunkpos10;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l4;
  {  int yypos13= yypos, yythunkpos13= yythunkpos;  if (!yy_eol()) goto l14;  goto l13;
  l14:;	  yypos= yypos13; yythunkpos= yythunkpos13;  if (!yymatchString("||")) goto l4;
  }
  l13:;	  yyDo(yy_2_table_cell, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "table_cell", yybuf+yypos));
  return 1;
  l4:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "table_cell", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_table_heading()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "table_heading"));  yyDo(yy_1_table_heading, yybegin, yyend);  if (!yymatchChar('!')) goto l15;  if (!yymatchChar(' ')) goto l15;
  l16:;	
  {  int yypos17= yypos, yythunkpos17= yythunkpos;  if (!yymatchChar(' ')) goto l17;  goto l16;
  l17:;	  yypos= yypos17; yythunkpos= yythunkpos17;
  }  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l15;
  l18:;	
  {  int yypos19= yypos, yythunkpos19= yythunkpos;
  {  int yypos20= yypos, yythunkpos20= yythunkpos;  if (!yymatchString(" |")) goto l20;  goto l19;
  l20:;	  yypos= yypos20; yythunkpos= yythunkpos20;
  }  if (!yymatchDot()) goto l19;  goto l18;
  l19:;	  yypos= yypos19; yythunkpos= yythunkpos19;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l15;  yyDo(yy_2_table_heading, yybegin, yyend);  if (!yymatchString(" |")) goto l15;
  l21:;	
  {  int yypos22= yypos, yythunkpos22= yythunkpos;  if (!yy_space()) goto l22;  goto l21;
  l22:;	  yypos= yypos22; yythunkpos= yythunkpos22;
  }  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l15;
  l23:;	
  {  int yypos24= yypos, yythunkpos24= yythunkpos;
  {  int yypos25= yypos, yythunkpos25= yythunkpos;  if (!yy_eol()) goto l25;  goto l24;
  l25:;	  yypos= yypos25; yythunkpos= yythunkpos25;
  }  if (!yymatchDot()) goto l24;  goto l23;
  l24:;	  yypos= yypos24; yythunkpos= yythunkpos24;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l15;  if (!yy_eol()) goto l15;  yyDo(yy_3_table_heading, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "table_heading", yybuf+yypos));
  return 1;
  l15:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "table_heading", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_table_row()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "table_row"));  if (!yymatchString("|-")) goto l26;  yyDo(yy_1_table_row, yybegin, yyend);
  l27:;	
  {  int yypos28= yypos, yythunkpos28= yythunkpos;  if (!yy_space()) goto l28;  goto l27;
  l28:;	  yypos= yypos28; yythunkpos= yythunkpos28;
  }  if (!yy_eol()) goto l26;
  l29:;	
  {  int yypos30= yypos, yythunkpos30= yythunkpos;  if (!yy_table_heading()) goto l30;  goto l29;
  l30:;	  yypos= yypos30; yythunkpos= yythunkpos30;
  }
  l31:;	
  {  int yypos32= yypos, yythunkpos32= yythunkpos;  if (!yy_table_cell()) goto l32;  goto l31;
  l32:;	  yypos= yypos32; yythunkpos= yythunkpos32;
  }  yyDo(yy_2_table_row, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "table_row", yybuf+yypos));
  return 1;
  l26:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "table_row", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_table_header()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "table_header"));  yyDo(yy_1_table_header, yybegin, yyend);  if (!yy_table_heading()) goto l33;
  l34:;	
  {  int yypos35= yypos, yythunkpos35= yythunkpos;  if (!yy_table_heading()) goto l35;  goto l34;
  l35:;	  yypos= yypos35; yythunkpos= yythunkpos35;
  }  yyDo(yy_2_table_header, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "table_header", yybuf+yypos));
  return 1;
  l33:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "table_header", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_table_caption()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "table_caption"));  if (!yymatchString("|+")) goto l36;  if (!yymatchChar(' ')) goto l36;
  l37:;	
  {  int yypos38= yypos, yythunkpos38= yythunkpos;  if (!yymatchChar(' ')) goto l38;  goto l37;
  l38:;	  yypos= yypos38; yythunkpos= yythunkpos38;
  }  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l36;
  l39:;	
  {  int yypos40= yypos, yythunkpos40= yythunkpos;
  {  int yypos41= yypos, yythunkpos41= yythunkpos;  if (!yy_eol()) goto l41;  goto l40;
  l41:;	  yypos= yypos41; yythunkpos= yythunkpos41;
  }  if (!yymatchDot()) goto l40;  goto l39;
  l40:;	  yypos= yypos40; yythunkpos= yythunkpos40;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l36;  if (!yy_eol()) goto l36;  yyDo(yy_1_table_caption, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "table_caption", yybuf+yypos));
  return 1;
  l36:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "table_caption", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_table_body()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "table_body"));
  {  int yypos43= yypos, yythunkpos43= yythunkpos;  if (!yy_table_caption()) goto l43;  goto l44;
  l43:;	  yypos= yypos43; yythunkpos= yythunkpos43;
  }
  l44:;	
  {  int yypos45= yypos, yythunkpos45= yythunkpos;  if (!yy_table_header()) goto l45;  goto l46;
  l45:;	  yypos= yypos45; yythunkpos= yythunkpos45;
  }
  l46:;	  if (!yy_table_row()) goto l42;
  l47:;	
  {  int yypos48= yypos, yythunkpos48= yythunkpos;  if (!yy_table_row()) goto l48;  goto l47;
  l48:;	  yypos= yypos48; yythunkpos= yythunkpos48;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "table_body", yybuf+yypos));
  return 1;
  l42:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "table_body", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_thumb()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "thumb"));
  {  int yypos50= yypos, yythunkpos50= yythunkpos;  if (!yymatchString("thumbnail")) goto l51;  goto l50;
  l51:;	  yypos= yypos50; yythunkpos= yythunkpos50;  if (!yymatchString("thumb")) goto l49;
  }
  l50:;	  yyDo(yy_1_thumb, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "thumb", yybuf+yypos));
  return 1;
  l49:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "thumb", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_frame()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "frame"));  if (!yymatchString("frame")) goto l52;  yyDo(yy_1_frame, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "frame", yybuf+yypos));
  return 1;
  l52:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "frame", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_image_link()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "image_link"));  if (!yymatchString("link=")) goto l53;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l53;
  l54:;	
  {  int yypos55= yypos, yythunkpos55= yythunkpos;
  {  int yypos56= yypos, yythunkpos56= yythunkpos;  if (!yymatchChar('|')) goto l56;  goto l55;
  l56:;	  yypos= yypos56; yythunkpos= yythunkpos56;
  }
  {  int yypos57= yypos, yythunkpos57= yythunkpos;  if (!yy_close_image()) goto l57;  goto l55;
  l57:;	  yypos= yypos57; yythunkpos= yythunkpos57;
  }  if (!yymatchDot()) goto l55;  goto l54;
  l55:;	  yypos= yypos55; yythunkpos= yythunkpos55;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l53;  yyDo(yy_1_image_link, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "image_link", yybuf+yypos));
  return 1;
  l53:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "image_link", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_float()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "float"));
  {  int yypos59= yypos, yythunkpos59= yythunkpos;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l60;
  {  int yypos61= yypos, yythunkpos61= yythunkpos;  if (!yymatchString("left")) goto l62;  goto l61;
  l62:;	  yypos= yypos61; yythunkpos= yythunkpos61;  if (!yymatchString("right")) goto l63;  goto l61;
  l63:;	  yypos= yypos61; yythunkpos= yythunkpos61;  if (!yymatchString("center")) goto l60;
  }
  l61:;	  yyText(yybegin, yyend);  if (!(YY_END)) goto l60;  yyDo(yy_1_float, yybegin, yyend);  goto l59;
  l60:;	  yypos= yypos59; yythunkpos= yythunkpos59;  if (!yymatchString("none")) goto l58;
  }
  l59:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "float", yybuf+yypos));
  return 1;
  l58:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "float", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_image_type()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "image_type"));
  {  int yypos65= yypos, yythunkpos65= yythunkpos;  if (!yy_frame()) goto l66;  goto l65;
  l66:;	  yypos= yypos65; yythunkpos= yythunkpos65;  if (!yy_thumb()) goto l64;
  }
  l65:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "image_type", yybuf+yypos));
  return 1;
  l64:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "image_type", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_value()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "value"));  if (!yymatchChar('=')) goto l67;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l67;
  l68:;	
  {  int yypos69= yypos, yythunkpos69= yythunkpos;
  {  int yypos70= yypos, yythunkpos70= yythunkpos;  if (!yymatchChar('|')) goto l70;  goto l69;
  l70:;	  yypos= yypos70; yythunkpos= yythunkpos70;
  }
  {  int yypos71= yypos, yythunkpos71= yythunkpos;  if (!yy_close_image()) goto l71;  goto l69;
  l71:;	  yypos= yypos71; yythunkpos= yythunkpos71;
  }  if (!yymatchDot()) goto l69;  goto l68;
  l69:;	  yypos= yypos69; yythunkpos= yythunkpos69;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l67;  yyDo(yy_1_value, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "value", yybuf+yypos));
  return 1;
  l67:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "value", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_generic_variable()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "generic_variable"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l72;
  l73:;	
  {  int yypos74= yypos, yythunkpos74= yythunkpos;
  {  int yypos75= yypos, yythunkpos75= yythunkpos;  if (!yymatchChar('|')) goto l75;  goto l74;
  l75:;	  yypos= yypos75; yythunkpos= yythunkpos75;
  }
  {  int yypos76= yypos, yythunkpos76= yythunkpos;  if (!yymatchChar('=')) goto l76;  goto l74;
  l76:;	  yypos= yypos76; yythunkpos= yythunkpos76;
  }
  {  int yypos77= yypos, yythunkpos77= yythunkpos;  if (!yy_close_image()) goto l77;  goto l74;
  l77:;	  yypos= yypos77; yythunkpos= yythunkpos77;
  }  if (!yymatchDot()) goto l74;  goto l73;
  l74:;	  yypos= yypos74; yythunkpos= yythunkpos74;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l72;  yyDo(yy_1_generic_variable, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "generic_variable", yybuf+yypos));
  return 1;
  l72:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "generic_variable", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_special_image_variables()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "special_image_variables"));
  {  int yypos79= yypos, yythunkpos79= yythunkpos;  if (!yy_image_type()) goto l80;  goto l79;
  l80:;	  yypos= yypos79; yythunkpos= yythunkpos79;  if (!yy_float()) goto l81;  goto l79;
  l81:;	  yypos= yypos79; yythunkpos= yythunkpos79;  if (!yy_image_link()) goto l78;
  }
  l79:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "special_image_variables", yybuf+yypos));
  return 1;
  l78:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "special_image_variables", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_close_image()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "close_image"));
  l83:;	
  {  int yypos84= yypos, yythunkpos84= yythunkpos;  if (!yy_space()) goto l84;  goto l83;
  l84:;	  yypos= yypos84; yythunkpos= yythunkpos84;
  }  if (!yymatchString("]]")) goto l82;
  yyprintf((stderr, "  ok   %s @ %s\n", "close_image", yybuf+yypos));
  return 1;
  l82:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "close_image", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_image_caption()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "image_caption"));  if (!yymatchChar('|')) goto l85;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l85;
  {  int yypos88= yypos, yythunkpos88= yythunkpos;  if (!yy_close_image()) goto l88;  goto l85;
  l88:;	  yypos= yypos88; yythunkpos= yythunkpos88;
  }  if (!yymatchDot()) goto l85;
  l86:;	
  {  int yypos87= yypos, yythunkpos87= yythunkpos;
  {  int yypos89= yypos, yythunkpos89= yythunkpos;  if (!yy_close_image()) goto l89;  goto l87;
  l89:;	  yypos= yypos89; yythunkpos= yythunkpos89;
  }  if (!yymatchDot()) goto l87;  goto l86;
  l87:;	  yypos= yypos87; yythunkpos= yythunkpos87;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l85;  yyDo(yy_1_image_caption, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "image_caption", yybuf+yypos));
  return 1;
  l85:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "image_caption", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_arguments()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "arguments"));  if (!yymatchChar('|')) goto l90;
  {  int yypos91= yypos, yythunkpos91= yythunkpos;  if (!yy_special_image_variables()) goto l92;  goto l91;
  l92:;	  yypos= yypos91; yythunkpos= yythunkpos91;  if (!yy_generic_variable()) goto l90;  if (!yy_value()) goto l90;
  }
  l91:;	
  {  int yypos93= yypos, yythunkpos93= yythunkpos;  if (!yy_arguments()) goto l93;  goto l94;
  l93:;	  yypos= yypos93; yythunkpos= yythunkpos93;
  }
  l94:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "arguments", yybuf+yypos));
  return 1;
  l90:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "arguments", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_file_indicator()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "file_indicator"));
  {  int yypos96= yypos, yythunkpos96= yythunkpos;  if (!yymatchString("File:")) goto l97;  goto l96;
  l97:;	  yypos= yypos96; yythunkpos= yythunkpos96;  if (!yymatchString("Image:")) goto l95;
  }
  l96:;	  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l95;
  l98:;	
  {  int yypos99= yypos, yythunkpos99= yythunkpos;
  {  int yypos100= yypos, yythunkpos100= yythunkpos;  if (!yymatchChar('|')) goto l100;  goto l99;
  l100:;	  yypos= yypos100; yythunkpos= yythunkpos100;
  }
  {  int yypos101= yypos, yythunkpos101= yythunkpos;  if (!yy_close_image()) goto l101;  goto l99;
  l101:;	  yypos= yypos101; yythunkpos= yythunkpos101;
  }  if (!yymatchDot()) goto l99;  goto l98;
  l99:;	  yypos= yypos99; yythunkpos= yythunkpos99;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l95;  yyDo(yy_1_file_indicator, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "file_indicator", yybuf+yypos));
  return 1;
  l95:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "file_indicator", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_open_image()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "open_image"));  if (!yymatchString("[[")) goto l102;
  l103:;	
  {  int yypos104= yypos, yythunkpos104= yythunkpos;  if (!yy_space()) goto l104;  goto l103;
  l104:;	  yypos= yypos104; yythunkpos= yythunkpos104;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "open_image", yybuf+yypos));
  return 1;
  l102:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "open_image", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_link_name()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "link_name"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l105;
  {  int yypos108= yypos, yythunkpos108= yythunkpos;  if (!yymatchChar(']')) goto l108;  goto l105;
  l108:;	  yypos= yypos108; yythunkpos= yythunkpos108;
  }  if (!yymatchDot()) goto l105;
  l106:;	
  {  int yypos107= yypos, yythunkpos107= yythunkpos;
  {  int yypos109= yypos, yythunkpos109= yythunkpos;  if (!yymatchChar(']')) goto l109;  goto l107;
  l109:;	  yypos= yypos109; yythunkpos= yythunkpos109;
  }  if (!yymatchDot()) goto l107;  goto l106;
  l107:;	  yypos= yypos107; yythunkpos= yythunkpos107;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l105;  yyDo(yy_1_link_name, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "link_name", yybuf+yypos));
  return 1;
  l105:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "link_name", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_link_url()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "link_url"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l110;
  {  int yypos113= yypos, yythunkpos113= yythunkpos;  if (!yymatchChar(' ')) goto l113;  goto l110;
  l113:;	  yypos= yypos113; yythunkpos= yythunkpos113;
  }
  {  int yypos114= yypos, yythunkpos114= yythunkpos;  if (!yymatchChar(']')) goto l114;  goto l110;
  l114:;	  yypos= yypos114; yythunkpos= yythunkpos114;
  }  if (!yymatchDot()) goto l110;
  l111:;	
  {  int yypos112= yypos, yythunkpos112= yythunkpos;
  {  int yypos115= yypos, yythunkpos115= yythunkpos;  if (!yymatchChar(' ')) goto l115;  goto l112;
  l115:;	  yypos= yypos115; yythunkpos= yythunkpos115;
  }
  {  int yypos116= yypos, yythunkpos116= yythunkpos;  if (!yymatchChar(']')) goto l116;  goto l112;
  l116:;	  yypos= yypos116; yythunkpos= yythunkpos116;
  }  if (!yymatchDot()) goto l112;  goto l111;
  l112:;	  yypos= yypos112; yythunkpos= yythunkpos112;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l110;  yyDo(yy_1_link_url, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "link_url", yybuf+yypos));
  return 1;
  l110:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "link_url", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_url()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "url"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l117;
  {  int yypos118= yypos, yythunkpos118= yythunkpos;  if (!yymatchString("http")) goto l119;  goto l118;
  l119:;	  yypos= yypos118; yythunkpos= yythunkpos118;  if (!yymatchString("https")) goto l120;  goto l118;
  l120:;	  yypos= yypos118; yythunkpos= yythunkpos118;  if (!yymatchString("ftp")) goto l117;
  }
  l118:;	  yyText(yybegin, yyend);  if (!(YY_END)) goto l117;  yyDo(yy_1_url, yybegin, yyend);  if (!yymatchString("://")) goto l117;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l117;
  l121:;	
  {  int yypos122= yypos, yythunkpos122= yythunkpos;
  {  int yypos123= yypos, yythunkpos123= yythunkpos;  if (!yy_eol()) goto l123;  goto l122;
  l123:;	  yypos= yypos123; yythunkpos= yythunkpos123;
  }
  {  int yypos124= yypos, yythunkpos124= yythunkpos;  if (!yymatchChar(' ')) goto l124;  goto l122;
  l124:;	  yypos= yypos124; yythunkpos= yythunkpos124;
  }  if (!yymatchDot()) goto l122;  goto l121;
  l122:;	  yypos= yypos122; yythunkpos= yythunkpos122;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l117;  yyDo(yy_2_url, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "url", yybuf+yypos));
  return 1;
  l117:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "url", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_unnamed_link()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "unnamed_link"));  if (!yymatchChar('[')) goto l125;
  {  int yypos126= yypos, yythunkpos126= yythunkpos;  if (!yymatchString("javascript:")) goto l126;  goto l125;
  l126:;	  yypos= yypos126; yythunkpos= yythunkpos126;
  }  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l125;
  l127:;	
  {  int yypos128= yypos, yythunkpos128= yythunkpos;
  {  int yypos129= yypos, yythunkpos129= yythunkpos;  if (!yymatchChar(']')) goto l129;  goto l128;
  l129:;	  yypos= yypos129; yythunkpos= yythunkpos129;
  }  if (!yymatchDot()) goto l128;  goto l127;
  l128:;	  yypos= yypos128; yythunkpos= yythunkpos128;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l125;  if (!yymatchChar(']')) goto l125;  yyDo(yy_1_unnamed_link, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "unnamed_link", yybuf+yypos));
  return 1;
  l125:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "unnamed_link", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_named_link()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "named_link"));  if (!yymatchChar('[')) goto l130;
  {  int yypos131= yypos, yythunkpos131= yythunkpos;  if (!yymatchString("javascript:")) goto l131;  goto l130;
  l131:;	  yypos= yypos131; yythunkpos= yythunkpos131;
  }  yyDo(yy_1_named_link, yybegin, yyend);  if (!yy_link_url()) goto l130;  yyDo(yy_2_named_link, yybegin, yyend);  if (!yymatchChar(' ')) goto l130;
  l132:;	
  {  int yypos133= yypos, yythunkpos133= yythunkpos;  if (!yymatchChar(' ')) goto l133;  goto l132;
  l133:;	  yypos= yypos133; yythunkpos= yythunkpos133;
  }  if (!yy_link_name()) goto l130;
  l134:;	
  {  int yypos135= yypos, yythunkpos135= yythunkpos;  if (!yy_link_name()) goto l135;  goto l134;
  l135:;	  yypos= yypos135; yythunkpos= yythunkpos135;
  }
  l136:;	
  {  int yypos137= yypos, yythunkpos137= yythunkpos;  if (!yy_space()) goto l137;  goto l136;
  l137:;	  yypos= yypos137; yythunkpos= yythunkpos137;
  }  if (!yymatchChar(']')) goto l130;  yyDo(yy_3_named_link, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "named_link", yybuf+yypos));
  return 1;
  l130:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "named_link", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_blend()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "blend"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l138;
  l139:;	
  {  int yypos140= yypos, yythunkpos140= yythunkpos;
  {  int yypos141= yypos, yythunkpos141= yythunkpos;  if (!yy_space()) goto l141;  goto l140;
  l141:;	  yypos= yypos141; yythunkpos= yythunkpos141;
  }
  {  int yypos142= yypos, yythunkpos142= yythunkpos;  if (!yymatchChar('=')) goto l142;  if (!yymatchChar('=')) goto l142;
  l143:;	
  {  int yypos144= yypos, yythunkpos144= yythunkpos;  if (!yymatchChar('=')) goto l144;  goto l143;
  l144:;	  yypos= yypos144; yythunkpos= yythunkpos144;
  }  goto l140;
  l142:;	  yypos= yypos142; yythunkpos= yythunkpos142;
  }
  {  int yypos145= yypos, yythunkpos145= yythunkpos;  if (!yymatchChar('[')) goto l145;  goto l140;
  l145:;	  yypos= yypos145; yythunkpos= yythunkpos145;
  }
  {  int yypos146= yypos, yythunkpos146= yythunkpos;  if (!yy_eol()) goto l146;  goto l140;
  l146:;	  yypos= yypos146; yythunkpos= yythunkpos146;
  }
  {  int yypos147= yypos, yythunkpos147= yythunkpos;  if (!yy_eof()) goto l147;  goto l140;
  l147:;	  yypos= yypos147; yythunkpos= yythunkpos147;
  }  if (!yymatchDot()) goto l140;  goto l139;
  l140:;	  yypos= yypos140; yythunkpos= yythunkpos140;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l138;  yyDo(yy_1_blend, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "blend", yybuf+yypos));
  return 1;
  l138:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "blend", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_link_close()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "link_close"));  if (!yymatchString("]]")) goto l148;
  yyprintf((stderr, "  ok   %s @ %s\n", "link_close", yybuf+yypos));
  return 1;
  l148:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "link_close", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_rename()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "rename"));  if (!yymatchChar('|')) goto l149;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l149;
  l150:;	
  {  int yypos151= yypos, yythunkpos151= yythunkpos;
  {  int yypos152= yypos, yythunkpos152= yythunkpos;  if (!yy_link_close()) goto l152;  goto l151;
  l152:;	  yypos= yypos152; yythunkpos= yythunkpos152;
  }  if (!yymatchDot()) goto l151;  goto l150;
  l151:;	  yypos= yypos151; yythunkpos= yythunkpos151;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l149;  yyDo(yy_1_rename, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "rename", yybuf+yypos));
  return 1;
  l149:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "rename", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_link_path()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "link_path"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l153;
  l154:;	
  {  int yypos155= yypos, yythunkpos155= yythunkpos;
  {  int yypos156= yypos, yythunkpos156= yythunkpos;  if (!yy_link_close()) goto l156;  goto l155;
  l156:;	  yypos= yypos156; yythunkpos= yythunkpos156;
  }
  {  int yypos157= yypos, yythunkpos157= yythunkpos;  if (!yymatchChar('|')) goto l157;  goto l155;
  l157:;	  yypos= yypos157; yythunkpos= yythunkpos157;
  }  if (!yymatchDot()) goto l155;  goto l154;
  l155:;	  yypos= yypos155; yythunkpos= yythunkpos155;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l153;  yyDo(yy_1_link_path, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "link_path", yybuf+yypos));
  return 1;
  l153:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "link_path", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_namespace()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "namespace"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l158;
  l159:;	
  {  int yypos160= yypos, yythunkpos160= yythunkpos;
  {  int yypos161= yypos, yythunkpos161= yythunkpos;  if (!yymatchChar(':')) goto l161;  goto l160;
  l161:;	  yypos= yypos161; yythunkpos= yythunkpos161;
  }
  {  int yypos162= yypos, yythunkpos162= yythunkpos;  if (!yy_link_close()) goto l162;  goto l160;
  l162:;	  yypos= yypos162; yythunkpos= yythunkpos162;
  }  if (!yymatchDot()) goto l160;  goto l159;
  l160:;	  yypos= yypos160; yythunkpos= yythunkpos160;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l158;  if (!yymatchChar(':')) goto l158;  yyDo(yy_1_namespace, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "namespace", yybuf+yypos));
  return 1;
  l158:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "namespace", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_link_open()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "link_open"));  if (!yymatchString("[[")) goto l163;
  yyprintf((stderr, "  ok   %s @ %s\n", "link_open", yybuf+yypos));
  return 1;
  l163:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "link_open", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_external_link()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "external_link"));
  {  int yypos165= yypos, yythunkpos165= yythunkpos;  if (!yy_named_link()) goto l166;  goto l165;
  l166:;	  yypos= yypos165; yythunkpos= yythunkpos165;  if (!yy_unnamed_link()) goto l167;  goto l165;
  l167:;	  yypos= yypos165; yythunkpos= yythunkpos165;  if (!yy_url()) goto l164;
  }
  l165:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "external_link", yybuf+yypos));
  return 1;
  l164:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "external_link", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_local_link()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "local_link"));  if (!yy_link_open()) goto l168;
  {  int yypos169= yypos, yythunkpos169= yythunkpos;  if (!yymatchChar(':')) goto l169;  goto l170;
  l169:;	  yypos= yypos169; yythunkpos= yythunkpos169;
  }
  l170:;	
  {  int yypos171= yypos, yythunkpos171= yythunkpos;  if (!yy_namespace()) goto l171;  goto l172;
  l171:;	  yypos= yypos171; yythunkpos= yythunkpos171;
  }
  l172:;	  if (!yy_link_path()) goto l168;
  {  int yypos173= yypos, yythunkpos173= yythunkpos;  if (!yy_rename()) goto l173;  goto l174;
  l173:;	  yypos= yypos173; yythunkpos= yythunkpos173;
  }
  l174:;	  if (!yy_link_close()) goto l168;  if (!yy_blend()) goto l168;  yyDo(yy_1_local_link, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "local_link", yybuf+yypos));
  return 1;
  l168:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "local_link", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_pre_line()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "pre_line"));  if (!yymatchChar(' ')) goto l175;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l175;
  l176:;	
  {  int yypos177= yypos, yythunkpos177= yythunkpos;
  {  int yypos178= yypos, yythunkpos178= yythunkpos;  if (!yy_eol()) goto l178;  goto l177;
  l178:;	  yypos= yypos178; yythunkpos= yythunkpos178;
  }  if (!yymatchDot()) goto l177;  goto l176;
  l177:;	  yypos= yypos177; yythunkpos= yythunkpos177;
  }
  {  int yypos179= yypos, yythunkpos179= yythunkpos;  if (!yy_eol()) goto l180;  goto l179;
  l180:;	  yypos= yypos179; yythunkpos= yythunkpos179;  if (!yy_eof()) goto l175;
  }
  l179:;	  yyText(yybegin, yyend);  if (!(YY_END)) goto l175;  yyDo(yy_1_pre_line, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "pre_line", yybuf+yypos));
  return 1;
  l175:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "pre_line", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_italic()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "italic"));  if (!yymatchString("''")) goto l181;  yyDo(yy_1_italic, yybegin, yyend);
  l182:;	
  {  int yypos183= yypos, yythunkpos183= yythunkpos;
  {  int yypos184= yypos, yythunkpos184= yythunkpos;  if (!yymatchString("''")) goto l184;  goto l183;
  l184:;	  yypos= yypos184; yythunkpos= yythunkpos184;
  }  if (!yy_wikitext()) goto l183;  goto l182;
  l183:;	  yypos= yypos183; yythunkpos= yythunkpos183;
  }  if (!yymatchString("''")) goto l181;  yyDo(yy_2_italic, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "italic", yybuf+yypos));
  return 1;
  l181:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "italic", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_bold()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "bold"));  if (!yymatchString("'''")) goto l185;  yyDo(yy_1_bold, yybegin, yyend);
  l186:;	
  {  int yypos187= yypos, yythunkpos187= yythunkpos;
  {  int yypos188= yypos, yythunkpos188= yythunkpos;  if (!yymatchString("'''")) goto l188;  goto l187;
  l188:;	  yypos= yypos188; yythunkpos= yythunkpos188;
  }  if (!yy_wikitext()) goto l187;  goto l186;
  l187:;	  yypos= yypos187; yythunkpos= yythunkpos187;
  }  if (!yymatchString("'''")) goto l185;  yyDo(yy_2_bold, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "bold", yybuf+yypos));
  return 1;
  l185:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bold", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_bold_italic()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "bold_italic"));  if (!yymatchString("'''''")) goto l189;  yyDo(yy_1_bold_italic, yybegin, yyend);
  l190:;	
  {  int yypos191= yypos, yythunkpos191= yythunkpos;
  {  int yypos192= yypos, yythunkpos192= yythunkpos;  if (!yymatchString("'''''")) goto l192;  goto l191;
  l192:;	  yypos= yypos192; yythunkpos= yythunkpos192;
  }  if (!yy_wikitext()) goto l191;  goto l190;
  l191:;	  yypos= yypos191; yythunkpos= yythunkpos191;
  }  if (!yymatchString("'''''")) goto l189;  yyDo(yy_2_bold_italic, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "bold_italic", yybuf+yypos));
  return 1;
  l189:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bold_italic", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_numbered()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "numbered"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l193;  if (!yymatchChar('#')) goto l193;
  l194:;	
  {  int yypos195= yypos, yythunkpos195= yythunkpos;  if (!yymatchChar('#')) goto l195;  goto l194;
  l195:;	  yypos= yypos195; yythunkpos= yythunkpos195;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l193;  yyDo(yy_1_numbered, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "numbered", yybuf+yypos));
  return 1;
  l193:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "numbered", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_numbered_list_entry()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "numbered_list_entry"));  if (!yy_numbered()) goto l196;
  l197:;	
  {  int yypos198= yypos, yythunkpos198= yythunkpos;  if (!yy_space()) goto l198;  goto l197;
  l198:;	  yypos= yypos198; yythunkpos= yythunkpos198;
  }
  l199:;	
  {  int yypos200= yypos, yythunkpos200= yythunkpos;
  {  int yypos201= yypos, yythunkpos201= yythunkpos;  if (!yy_eol()) goto l201;  goto l200;
  l201:;	  yypos= yypos201; yythunkpos= yythunkpos201;
  }  if (!yy_wikitext()) goto l200;  goto l199;
  l200:;	  yypos= yypos200; yythunkpos= yythunkpos200;
  }
  {  int yypos202= yypos, yythunkpos202= yythunkpos;  if (!yy_eol()) goto l202;  goto l203;
  l202:;	  yypos= yypos202; yythunkpos= yythunkpos202;
  }
  l203:;	  yyDo(yy_1_numbered_list_entry, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "numbered_list_entry", yybuf+yypos));
  return 1;
  l196:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "numbered_list_entry", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_bullet()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "bullet"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l204;  if (!yymatchChar('*')) goto l204;
  l205:;	
  {  int yypos206= yypos, yythunkpos206= yythunkpos;  if (!yymatchChar('*')) goto l206;  goto l205;
  l206:;	  yypos= yypos206; yythunkpos= yythunkpos206;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l204;  yyDo(yy_1_bullet, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "bullet", yybuf+yypos));
  return 1;
  l204:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bullet", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_bullet_list_entry()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "bullet_list_entry"));  if (!yy_bullet()) goto l207;
  l208:;	
  {  int yypos209= yypos, yythunkpos209= yythunkpos;  if (!yy_space()) goto l209;  goto l208;
  l209:;	  yypos= yypos209; yythunkpos= yythunkpos209;
  }
  l210:;	
  {  int yypos211= yypos, yythunkpos211= yythunkpos;
  {  int yypos212= yypos, yythunkpos212= yythunkpos;  if (!yy_eol()) goto l212;  goto l211;
  l212:;	  yypos= yypos212; yythunkpos= yythunkpos212;
  }  if (!yy_wikitext()) goto l211;  goto l210;
  l211:;	  yypos= yypos211; yythunkpos= yythunkpos211;
  }
  {  int yypos213= yypos, yythunkpos213= yythunkpos;  if (!yy_eol()) goto l214;  goto l213;
  l214:;	  yypos= yypos213; yythunkpos= yythunkpos213;  if (!yy_eof()) goto l207;
  }
  l213:;	  yyDo(yy_1_bullet_list_entry, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "bullet_list_entry", yybuf+yypos));
  return 1;
  l207:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bullet_list_entry", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_numbered_list()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "numbered_list"));  yyDo(yy_1_numbered_list, yybegin, yyend);  if (!yy_numbered_list_entry()) goto l215;
  l216:;	
  {  int yypos217= yypos, yythunkpos217= yythunkpos;  if (!yy_numbered_list_entry()) goto l217;  goto l216;
  l217:;	  yypos= yypos217; yythunkpos= yythunkpos217;
  }  yyDo(yy_2_numbered_list, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "numbered_list", yybuf+yypos));
  return 1;
  l215:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "numbered_list", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_bullet_list()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "bullet_list"));  yyDo(yy_1_bullet_list, yybegin, yyend);  if (!yy_bullet_list_entry()) goto l218;
  l219:;	
  {  int yypos220= yypos, yythunkpos220= yythunkpos;  if (!yy_bullet_list_entry()) goto l220;  goto l219;
  l220:;	  yypos= yypos220; yythunkpos= yythunkpos220;
  }  yyDo(yy_2_bullet_list, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "bullet_list", yybuf+yypos));
  return 1;
  l218:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bullet_list", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_heading_text()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "heading_text"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l221;
  l222:;	
  {  int yypos223= yypos, yythunkpos223= yythunkpos;
  {  int yypos224= yypos, yythunkpos224= yythunkpos;  if (!yy_heading_marker()) goto l224;  goto l223;
  l224:;	  yypos= yypos224; yythunkpos= yythunkpos224;
  }
  {  int yypos225= yypos, yythunkpos225= yythunkpos;  if (!yy_formatting()) goto l226;  goto l225;
  l226:;	  yypos= yypos225; yythunkpos= yythunkpos225;  if (!yy_link()) goto l227;  goto l225;
  l227:;	  yypos= yypos225; yythunkpos= yythunkpos225;  if (!yy_anything_else()) goto l223;
  }
  l225:;	  goto l222;
  l223:;	  yypos= yypos223; yythunkpos= yythunkpos223;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l221;
  yyprintf((stderr, "  ok   %s @ %s\n", "heading_text", yybuf+yypos));
  return 1;
  l221:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "heading_text", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_heading_marker()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "heading_marker"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l228;  if (!yymatchChar('=')) goto l228;  if (!yymatchChar('=')) goto l228;
  l229:;	
  {  int yypos230= yypos, yythunkpos230= yythunkpos;  if (!yymatchChar('=')) goto l230;  goto l229;
  l230:;	  yypos= yypos230; yythunkpos= yythunkpos230;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l228;  yyDo(yy_1_heading_marker, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "heading_marker", yybuf+yypos));
  return 1;
  l228:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "heading_marker", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_space()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "space"));  if (!yymatchClass((unsigned char *)"\000\002\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l231;
  yyprintf((stderr, "  ok   %s @ %s\n", "space", yybuf+yypos));
  return 1;
  l231:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "space", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_eof()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "eof"));
  {  int yypos233= yypos, yythunkpos233= yythunkpos;  if (!yymatchDot()) goto l233;  goto l232;
  l233:;	  yypos= yypos233; yythunkpos= yythunkpos233;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "eof", yybuf+yypos));
  return 1;
  l232:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eof", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_eol()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "eol"));
  {  int yypos235= yypos, yythunkpos235= yythunkpos;  if (!yymatchChar('\r')) goto l235;  goto l236;
  l235:;	  yypos= yypos235; yythunkpos= yythunkpos235;
  }
  l236:;	  if (!yymatchChar('\n')) goto l234;  yyDo(yy_1_eol, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "eol", yybuf+yypos));
  return 1;
  l234:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eol", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_anything_else()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "anything_else"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l237;
  {  int yypos238= yypos, yythunkpos238= yythunkpos;  if (!yy_eol()) goto l238;  goto l237;
  l238:;	  yypos= yypos238; yythunkpos= yythunkpos238;
  }  if (!yymatchDot()) goto l237;  yyText(yybegin, yyend);  if (!(YY_END)) goto l237;  yyDo(yy_1_anything_else, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "anything_else", yybuf+yypos));
  return 1;
  l237:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "anything_else", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_table()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "table"));  if (!yymatchString("{|")) goto l239;  yyDo(yy_1_table, yybegin, yyend);  if (!yy_eol()) goto l239;  if (!yy_table_body()) goto l239;  if (!yymatchString("|}")) goto l239;
  {  int yypos240= yypos, yythunkpos240= yythunkpos;  if (!yy_eol()) goto l241;  goto l240;
  l241:;	  yypos= yypos240; yythunkpos= yythunkpos240;  if (!yy_eof()) goto l239;
  }
  l240:;	  yyDo(yy_2_table, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "table", yybuf+yypos));
  return 1;
  l239:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "table", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_link()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "link"));
  {  int yypos243= yypos, yythunkpos243= yythunkpos;  if (!yy_local_link()) goto l244;  goto l243;
  l244:;	  yypos= yypos243; yythunkpos= yythunkpos243;  if (!yy_external_link()) goto l242;
  }
  l243:;	  yyDo(yy_1_link, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "link", yybuf+yypos));
  return 1;
  l242:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "link", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_image()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "image"));  if (!yy_open_image()) goto l245;  yyDo(yy_1_image, yybegin, yyend);  if (!yy_file_indicator()) goto l245;
  {  int yypos246= yypos, yythunkpos246= yythunkpos;  if (!yy_arguments()) goto l246;  goto l247;
  l246:;	  yypos= yypos246; yythunkpos= yythunkpos246;
  }
  l247:;	
  {  int yypos248= yypos, yythunkpos248= yythunkpos;  if (!yy_image_caption()) goto l248;  goto l249;
  l248:;	  yypos= yypos248; yythunkpos= yythunkpos248;
  }
  l249:;	  if (!yy_close_image()) goto l245;  yyDo(yy_2_image, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "image", yybuf+yypos));
  return 1;
  l245:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "image", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_formatting()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "formatting"));
  {  int yypos251= yypos, yythunkpos251= yythunkpos;  if (!yy_bold_italic()) goto l252;  goto l251;
  l252:;	  yypos= yypos251; yythunkpos= yythunkpos251;  if (!yy_bold()) goto l253;  goto l251;
  l253:;	  yypos= yypos251; yythunkpos= yythunkpos251;  if (!yy_italic()) goto l250;
  }
  l251:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "formatting", yybuf+yypos));
  return 1;
  l250:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "formatting", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_list()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "list"));
  {  int yypos255= yypos, yythunkpos255= yythunkpos;  if (!yy_bullet_list()) goto l256;  goto l255;
  l256:;	  yypos= yypos255; yythunkpos= yythunkpos255;  if (!yy_numbered_list()) goto l254;
  }
  l255:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "list", yybuf+yypos));
  return 1;
  l254:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "list", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_indentation()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "indentation"));  yyText(yybegin, yyend);  if (!( start_of_line )) goto l257;  if (!yymatchChar(':')) goto l257;  yyDo(yy_1_indentation, yybegin, yyend);  if (!yy_wikitext()) goto l257;
  yyprintf((stderr, "  ok   %s @ %s\n", "indentation", yybuf+yypos));
  return 1;
  l257:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "indentation", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_heading()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "heading"));  if (!yy_heading_marker()) goto l258;  yyDo(yy_1_heading, yybegin, yyend);
  l259:;	
  {  int yypos260= yypos, yythunkpos260= yythunkpos;  if (!yy_space()) goto l260;  goto l259;
  l260:;	  yypos= yypos260; yythunkpos= yythunkpos260;
  }  if (!yy_heading_text()) goto l258;  if (!yy_heading_marker()) goto l258;
  l261:;	
  {  int yypos262= yypos, yythunkpos262= yythunkpos;  if (!yy_space()) goto l262;  goto l261;
  l262:;	  yypos= yypos262; yythunkpos= yythunkpos262;
  }
  {  int yypos263= yypos, yythunkpos263= yythunkpos;  if (!yy_eol()) goto l264;  goto l263;
  l264:;	  yypos= yypos263; yythunkpos= yythunkpos263;  if (!yy_eof()) goto l258;
  }
  l263:;	  yyDo(yy_2_heading, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "heading", yybuf+yypos));
  return 1;
  l258:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "heading", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_template()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "template"));  if (!yymatchString("{{")) goto l265;
  l266:;	
  {  int yypos267= yypos, yythunkpos267= yythunkpos;  if (!yy_space()) goto l267;  goto l266;
  l267:;	  yypos= yypos267; yythunkpos= yythunkpos267;
  }
  l268:;	
  {  int yypos269= yypos, yythunkpos269= yythunkpos;
  {  int yypos270= yypos, yythunkpos270= yythunkpos;  if (!yymatchString("}}")) goto l270;  goto l269;
  l270:;	  yypos= yypos270; yythunkpos= yythunkpos270;
  }  if (!yymatchDot()) goto l269;  goto l268;
  l269:;	  yypos= yypos269; yythunkpos= yythunkpos269;
  }  if (!yymatchString("}}")) goto l265;  yyDo(yy_1_template, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "template", yybuf+yypos));
  return 1;
  l265:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "template", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_table_of_contents()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "table_of_contents"));
  {  int yypos272= yypos, yythunkpos272= yythunkpos;  if (!yy_notoc()) goto l273;  goto l272;
  l273:;	  yypos= yypos272; yythunkpos= yythunkpos272;  if (!yy_toc()) goto l274;  goto l272;
  l274:;	  yypos= yypos272; yythunkpos= yythunkpos272;  if (!yy_forcetoc()) goto l271;
  }
  l272:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "table_of_contents", yybuf+yypos));
  return 1;
  l271:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "table_of_contents", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_horizontal_line()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "horizontal_line"));  if (!yymatchString("----")) goto l275;
  {  int yypos276= yypos, yythunkpos276= yythunkpos;  if (!yy_eol()) goto l277;  goto l276;
  l277:;	  yypos= yypos276; yythunkpos= yythunkpos276;  if (!yy_eof()) goto l275;
  }
  l276:;	  yyDo(yy_1_horizontal_line, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "horizontal_line", yybuf+yypos));
  return 1;
  l275:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "horizontal_line", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_paragraph()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "paragraph"));  if (!yy_wikitext()) goto l278;  if (!yy_eol()) goto l278;  if (!yy_eol()) goto l278;  yyDo(yy_1_paragraph, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "paragraph", yybuf+yypos));
  return 1;
  l278:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "paragraph", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_wikitext()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "wikitext"));
  {  int yypos280= yypos, yythunkpos280= yythunkpos;  if (!yy_table_of_contents()) goto l281;  goto l280;
  l281:;	  yypos= yypos280; yythunkpos= yythunkpos280;  if (!yy_template()) goto l282;  goto l280;
  l282:;	  yypos= yypos280; yythunkpos= yythunkpos280;  if (!yy_heading()) goto l283;  goto l280;
  l283:;	  yypos= yypos280; yythunkpos= yythunkpos280;  if (!yy_indentation()) goto l284;  goto l280;
  l284:;	  yypos= yypos280; yythunkpos= yythunkpos280;  if (!yy_list()) goto l285;  goto l280;
  l285:;	  yypos= yypos280; yythunkpos= yythunkpos280;  if (!yy_formatting()) goto l286;  goto l280;
  l286:;	  yypos= yypos280; yythunkpos= yythunkpos280;  if (!yy_image()) goto l287;  goto l280;
  l287:;	  yypos= yypos280; yythunkpos= yythunkpos280;  if (!yy_link()) goto l288;  goto l280;
  l288:;	  yypos= yypos280; yythunkpos= yythunkpos280;  if (!yy_table()) goto l289;  goto l280;
  l289:;	  yypos= yypos280; yythunkpos= yythunkpos280;  if (!yy_anything_else()) goto l290;  goto l280;
  l290:;	  yypos= yypos280; yythunkpos= yythunkpos280;  if (!yy_eol()) goto l279;
  }
  l280:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "wikitext", yybuf+yypos));
  return 1;
  l279:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "wikitext", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_wikitext_line()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "wikitext_line"));
  {  int yypos292= yypos, yythunkpos292= yythunkpos;  if (!yy_paragraph()) goto l293;  goto l292;
  l293:;	  yypos= yypos292; yythunkpos= yythunkpos292;  if (!yy_horizontal_line()) goto l291;
  }
  l292:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "wikitext_line", yybuf+yypos));
  return 1;
  l291:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "wikitext_line", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_pre_block()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "pre_block"));  yyText(yybegin, yyend);  if (!( start_of_line )) goto l294;  yyDo(yy_1_pre_block, yybegin, yyend);  if (!yy_pre_line()) goto l294;
  l295:;	
  {  int yypos296= yypos, yythunkpos296= yythunkpos;  if (!yy_pre_line()) goto l296;  goto l295;
  l296:;	  yypos= yypos296; yythunkpos= yythunkpos296;
  }  yyDo(yy_2_pre_block, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "pre_block", yybuf+yypos));
  return 1;
  l294:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "pre_block", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_html()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "html"));  if (!yymatchChar('<')) goto l297;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l297;
  {  int yypos298= yypos, yythunkpos298= yythunkpos;  if (!yymatchChar('/')) goto l298;  goto l299;
  l298:;	  yypos= yypos298; yythunkpos= yythunkpos298;
  }
  l299:;	
  {  int yypos302= yypos, yythunkpos302= yythunkpos;  if (!yymatchChar('>')) goto l302;  goto l297;
  l302:;	  yypos= yypos302; yythunkpos= yythunkpos302;
  }  if (!yymatchDot()) goto l297;
  l300:;	
  {  int yypos301= yypos, yythunkpos301= yythunkpos;
  {  int yypos303= yypos, yythunkpos303= yythunkpos;  if (!yymatchChar('>')) goto l303;  goto l301;
  l303:;	  yypos= yypos303; yythunkpos= yythunkpos303;
  }  if (!yymatchDot()) goto l301;  goto l300;
  l301:;	  yypos= yypos301; yythunkpos= yythunkpos301;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l297;
  {  int yypos304= yypos, yythunkpos304= yythunkpos;  if (!yymatchChar('/')) goto l304;  goto l305;
  l304:;	  yypos= yypos304; yythunkpos= yythunkpos304;
  }
  l305:;	  if (!yymatchChar('>')) goto l297;  yyDo(yy_1_html, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "html", yybuf+yypos));
  return 1;
  l297:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "html", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_nowiki()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "nowiki"));  if (!yymatchString("<nowiki>")) goto l306;
  l307:;	
  {  int yypos308= yypos, yythunkpos308= yythunkpos;
  {  int yypos309= yypos, yythunkpos309= yythunkpos;  if (!yymatchString("</nowiki>")) goto l309;  goto l308;
  l309:;	  yypos= yypos309; yythunkpos= yythunkpos309;
  }  if (!yy_anything_else()) goto l308;  goto l307;
  l308:;	  yypos= yypos308; yythunkpos= yythunkpos308;
  }  if (!yymatchString("</nowiki>")) goto l306;
  yyprintf((stderr, "  ok   %s @ %s\n", "nowiki", yybuf+yypos));
  return 1;
  l306:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "nowiki", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_page()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "page"));
  {  int yypos311= yypos, yythunkpos311= yythunkpos;  if (!yy_nowiki()) goto l312;  goto l311;
  l312:;	  yypos= yypos311; yythunkpos= yythunkpos311;  if (!yy_html()) goto l313;  goto l311;
  l313:;	  yypos= yypos311; yythunkpos= yythunkpos311;  if (!yy_pre_block()) goto l314;  goto l311;
  l314:;	  yypos= yypos311; yythunkpos= yythunkpos311;  if (!yy_wikitext_line()) goto l315;  goto l311;
  l315:;	  yypos= yypos311; yythunkpos= yythunkpos311;  if (!yy_wikitext()) goto l310;
  }
  l311:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "page", yybuf+yypos));
  return 1;
  l310:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "page", yybuf+yypos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)();

YY_PARSE(int) YYPARSEFROM(yyrule yystart)
{
  int yyok;
  if (!yybuflen)
    {
      yybuflen= 1024;
      yybuf= malloc(yybuflen);
      yytextlen= 1024;
      yytext= malloc(yytextlen);
      yythunkslen= 32;
      yythunks= malloc(sizeof(yythunk) * yythunkslen);
      yyvalslen= 32;
      yyvals= malloc(sizeof(YYSTYPE) * yyvalslen);
      yybegin= yyend= yypos= yylimit= yythunkpos= 0;
    }
  yybegin= yyend= yypos;
  yythunkpos= 0;
  yyval= yyvals;
  yyok= yystart();
  if (yyok) yyDone();
  yyCommit();
  return yyok;
  (void)yyrefill;
  (void)yymatchDot;
  (void)yymatchChar;
  (void)yymatchString;
  (void)yymatchClass;
  (void)yyDo;
  (void)yyText;
  (void)yyDone;
  (void)yyCommit;
  (void)yyAccept;
  (void)yyPush;
  (void)yyPop;
  (void)yySet;
  (void)yytextmax;
}

YY_PARSE(int) YYPARSE(void)
{
  return YYPARSEFROM(yy_page);
}

#endif


void set_output_buffer(bstring buffer) {
  output_buffer = buffer;
}

void set_input_buffer(bstring buffer) {
  input_buffer = buffer;
}

void init() {
  current_header_level = 0;
  start_of_line = 1;
  image_attributes = 0;
  toc_attributes = 0;
  in_tag = 0;
  bstring output_buffer = NULL;
  bstring input_buffer = NULL;
  input_buffer_pos = 0;

  list_init(&list);
  tag_content = bfromcstr("");
  ballocmin(tag_content, tag_content_size);

  image_variables = bfromcstr("");
  image_url = bfromcstr("");
  image_link_url = bfromcstr("");
  image_caption = bfromcstr("");

  link_path = bfromcstr("");
  link_text = bfromcstr("");

  output_buffer = bfromcstr("");
  input_buffer = bfromcstr("");
  ballocmin(output_buffer, 1 * MBYTE);
}

void cleanup() {
  bdestroy(tag_content);
  bdestroy(image_variables);
  bdestroy(image_url);
  bdestroy(image_link_url);
  bdestroy(image_caption);
  bdestroy(link_path);
  bdestroy(link_text);

  list_free(&list);
}

void parse(bstring inputbuffer, bstring outbuffer) {
  init();
  set_output_buffer(outbuffer);
  set_input_buffer(inputbuffer);

  bprintf("<p>");
  while(yyparse()) {}
  bprintf("</p>");
  handle_toc();

  cleanup();
}

int main() {
  bstring output = bfromcstr("");
  bstring input = bfromcstr("");
  //file_get_contents(input, "spec/fixtures/cnn.com");
  stdin_get_contents(input);
  parse(input, output);
  printf("%s", bdata(output));
  bdestroy(output);
  return 0;
}

