/* A recursive-descent parser generated by peg 0.1.2 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 62

#include <stdio.h>
#include <signal.h>
#include <time.h>
#include <stdarg.h>
#include <stdbool.h>
#include <ctype.h>
#include "bstrlib.h"
#include "list.h"

#define YY_noDEBUG 1
#define KBYTE 1024
#define MBYTE KBYTE * 1024
#define STR_BUFFER_LEN 1024

#define IMAGE_FRAME 1
#define IMAGE_THUMB ( 1 << 1 )

#define TOC_NOTOC ( 1 << 1 )
#define TOC_FORCETOC ( 1 << 2 )
#define TOC_RELOC ( 1 << 3 )


int current_header_level = 0;
int current_bullet_list_level;
int current_numbered_list_level;

int start_of_line = 1;
char protocol[5];

int image_attributes = 0;
bstring image_url;
bstring image_variables;

int toc_attributes = 0;

int in_tag = 0;
bstring tag_content;
unsigned int tag_content_size = 2 * MBYTE;

bstring output_buffer;

struct list list;

// Buffer printf, buffer output until we're ready
void bprintf(const char *fmt, ...) {
  int ret;
  bvformata(ret, output_buffer, fmt, fmt);
}

// Append a character to a buffer a repeat number of times
void repeat_append(bstring buffer, char chr, int count) {
  int i;
  bstring tmp = bfromcstr("");
  ballocmin(tmp, count);
  for(i = 0; i <= count; i++) {
      tmp->data[i] = chr;
    tmp->slen++;
  }
  bconcat(buffer, tmp);
  bdestroy(tmp);
}

// Render the ToC from a list, output to buffer
void assemble_toc(struct node *item, bstring toc_buffer) {
  if(!item) {
    printf("Bad list passed to assemble_toc\n");
    return;
  }

  struct node *next;
  int previous_level = item->level;
  int total_layers = 0;
  int i;
  bformata(toc_buffer, "%s", "<div id=\"toc\" class=\"toc\">\n<div id=\"toctitle\">Contents</div>\n<ol>\n");
  while(item != NULL) {
    next = item->next;
    
    // Layer the list deeper as necessary
    if(item->level > previous_level) {
      repeat_append(toc_buffer, ' ', (total_layers + 1) * 2);
      for(i = previous_level; i < item->level; i++) {
        bformata(toc_buffer, "%s", "<ol>\n");
        total_layers++;
      }
    } else if((item->level < previous_level) && (total_layers > 1)) {
      for(i = previous_level; i > item->level; i--) {
        repeat_append(toc_buffer, ' ', (total_layers) * 2);
        bformata(toc_buffer, "%s", "</ol>\n");
        total_layers--;
      }
    }
    
    // Add the item
    if(item->name && item->content) {
      repeat_append(toc_buffer, ' ', (total_layers + 1) * 2);
      bformata(toc_buffer, "  <li><a href=\"#%s\">%s</a></li>\n", bdata(item->name), bdata(item->content));
    }
    previous_level = item->level;
    item = next;
  }
 
  // Clean up lists left open
  while(total_layers > 0) {
    bformata(toc_buffer, "%s", "</ol>\n");
    total_layers--;
  }
  bformata(toc_buffer, "%s", "</ol>\n</div>\n");
}

// Insert the ToC into the output buffer in place of the __TOC__ tag
void insert_reloc_toc(bstring toc_buffer) {
  bstring find = bfromcstr("__TOC__");
  if(bfindreplace(output_buffer, find, toc_buffer, 0) == BSTR_ERR) {
    printf("Error inserting toc_buffer into output_buffer\n");
  }
  bdestroy(find);
}

// Main ToC routine
void handle_toc() {
  if(toc_attributes & TOC_NOTOC) {
    return;
  }

  if((list.size > 3) || (toc_attributes & TOC_FORCETOC)) {
    bstring toc_buffer = bfromcstr("");
    assemble_toc(list.head->next, toc_buffer);

    if(toc_attributes & TOC_RELOC) {
      insert_reloc_toc(toc_buffer);
      bdestroy(toc_buffer);
      return;
    }

    if(binsert(output_buffer, 0, toc_buffer, ' ') != BSTR_OK) {
      printf("Error prepending toc_buffer to output_buffer\n");
    }
    bdestroy(toc_buffer);
  }
}

void remove_parentheticals(bstring str) {
  char *temp = bstr2cstr(str, '\0');

  int i, index = 0;
  int in_tag = 0;
  for(i = 0; i < blength(str); i++) {
    if((bdata(str))[i] == '(') {
      in_tag++;
      continue;
    } else if((bdata(str))[i] == ')') {
      in_tag--;
      continue;
    }
    if(in_tag < 1) temp[index++] = (bdata(str))[i];
  }
  temp[index] = '\0';
  bdestroy(str);
  str = bfromcstr(temp);
  bcstrfree(temp);
}

void strip_tags(bstring str) {
  char *temp = bstr2cstr(str, '\0');

  int i, index = 0;
  int in_tag = 0;
  for(i = 0; i < blength(str); i++) {
    if((bdata(str))[i] == '<') {
      in_tag++;
      continue;
    } else if((bdata(str))[i] == '>') {
      in_tag--;
      continue;
    }
    if(in_tag < 1) temp[index++] = (bdata(str))[i];
  }
  temp[index] = '\0';
  bdestroy(str);
  str = bfromcstr(temp);
  bcstrfree(temp);
}

void urlencode(bstring b) {
  char *p;
  int c, e;
  bstring target = bfromcstr("");

  int whitelist[] = {
    /* reserved characters */
    [36] '$',
    [38] '&',
    [43] '+',
    [44] ',',
    [46] '.',
    [47] '/',
    [58] ':',
    [59] ';',
    [61] '=',
    [63] '?',
    [64] '@',
    [95] '_'
  };

  p = bdata(b);
  while ((c = *p++)) { // Double parens to make gcc shut up
    /* [0-9A-Za-z] */
    if (('0' <= c && c <= '9') ||
        ('A' <= c && c <= 'Z') ||
        ('a' <= c && c <= 'z')) {
      bformata(target, "%c", c);
      continue;
    }
    e = whitelist[c];
    if (e) {
      bformata(target, "%c", c);
      continue;
    }
    bformata(target, "%%%02x", c);
  }
  bassign(b, target);
}

void strip_html_markup(bstring str) {
  strip_tags(str);
  brtrimws(str);
  bstring find = bfromcstr(" ");
  bstring replace = bfromcstr("_");
  bfindreplace(str, find, replace, 0);
  bdestroy(find);
  bdestroy(replace);
}

void open_tag(char *tag, char *args) {
  if(args) {
    bprintf("<%s %s>", tag, args);
  } else {
    bprintf("<%s>", tag);
  }

  in_tag = 1;
  if(tag_content) {
    btrunc(tag_content,0 );
  }
}

void close_tag(char *tag) {
  bprintf("</%s>", tag);
  in_tag = 0;
}

void append_to_tag_content(char *fmt, ...) {
  int ret;

  if(!in_tag) {
    bvformata(ret, output_buffer, fmt, fmt);
    return;
  }

  bvformata(ret, tag_content, fmt, fmt);
}

// Number of entries on one line of the valid tag lookup table
#define HTML_MAX_TAG_ENTRIES 5
// Longest allowed tag length
#define HTML_MAX_LENGTH 11

// Validate whether or not a specific HTML tag is allowed.
bool valid_html_tag(char *html_tag, size_t orig_len) {

  // Lookup table based on tag length
  static const char valid_tags[HTML_MAX_LENGTH][HTML_MAX_TAG_ENTRIES][10] = {
    [1]  { "b", "i", "s" },
    [2]  { "br", "hr" },
    [3]  { "big", "del", "div", "pre" },
    [4]  { "code" },
    [5]  { "small" }, 
    [6]  { "strong", "strike", "center" },
    [10] { "blockquote" }
  };

  char *tag = html_tag;
  int len = orig_len;

  if((tag[0] == '/') && (len > 1)) {
    tag++;
    len--;
  }

  if(len == 0) {
    return false;
  }

  // If there are no allowed tags this length
  if(!valid_tags[len]) {
    return false;
  }

  int i;
  char c = tolower(tag[0]);
  for(i = 0; i < HTML_MAX_TAG_ENTRIES; i++) {
    if(tolower(valid_tags[len][i][0]) == c) { // Integer comparison on first character
      if(!strncasecmp(tag, valid_tags[len][i], len)) {
        return true;
      }
    }
  }

  return false;
}


#ifndef YY_VARIABLE
#define YY_VARIABLE(T)	static T
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yybegin= yypos, 1)
#endif
#ifndef YY_END
#define YY_END		( yyend= yypos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif

#ifndef YY_PART

typedef void (*yyaction)(char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

YY_VARIABLE(char *   ) yybuf= 0;
YY_VARIABLE(int	     ) yybuflen= 0;
YY_VARIABLE(int	     ) yypos= 0;
YY_VARIABLE(int	     ) yylimit= 0;
YY_VARIABLE(char *   ) yytext= 0;
YY_VARIABLE(int	     ) yytextlen= 0;
YY_VARIABLE(int	     ) yybegin= 0;
YY_VARIABLE(int	     ) yyend= 0;
YY_VARIABLE(int	     ) yytextmax= 0;
YY_VARIABLE(yythunk *) yythunks= 0;
YY_VARIABLE(int	     ) yythunkslen= 0;
YY_VARIABLE(int      ) yythunkpos= 0;
YY_VARIABLE(YYSTYPE  ) yy;
YY_VARIABLE(YYSTYPE *) yyval= 0;
YY_VARIABLE(YYSTYPE *) yyvals= 0;
YY_VARIABLE(int      ) yyvalslen= 0;

YY_LOCAL(int) yyrefill(void)
{
  int yyn;
  while (yybuflen - yypos < 512)
    {
      yybuflen *= 2;
      yybuf= realloc(yybuf, yybuflen);
    }
  YY_INPUT((yybuf + yypos), yyn, (yybuflen - yypos));
  if (!yyn) return 0;
  yylimit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(void)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  ++yypos;
  return 1;
}

YY_LOCAL(int) yymatchChar(int c)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  if (yybuf[yypos] == c)
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchChar(%c) @ %s\n", c, yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(%c) @ %s\n", c, yybuf+yypos));
  return 0;
}

YY_LOCAL(int) yymatchString(char *s)
{
  int yysav= yypos;
  while (*s)
    {
      if (yypos >= yylimit && !yyrefill()) return 0;
      if (yybuf[yypos] != *s)
        {
          yypos= yysav;
          return 0;
        }
      ++s;
      ++yypos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(unsigned char *bits)
{
  int c;
  if (yypos >= yylimit && !yyrefill()) return 0;
  c= yybuf[yypos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yybuf+yypos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yybuf+yypos));
  return 0;
}

YY_LOCAL(void) yyDo(yyaction action, int begin, int end)
{
  while (yythunkpos >= yythunkslen)
    {
      yythunkslen *= 2;
      yythunks= realloc(yythunks, sizeof(yythunk) * yythunkslen);
    }
  yythunks[yythunkpos].begin=  begin;
  yythunks[yythunkpos].end=    end;
  yythunks[yythunkpos].action= action;
  ++yythunkpos;
}

YY_LOCAL(int) yyText(int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yytextlen < (yyleng - 1))
	{
	  yytextlen *= 2;
	  yytext= realloc(yytext, yytextlen);
	}
      memcpy(yytext, yybuf + begin, yyleng);
    }
  yytext[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(void)
{
  int pos;
  for (pos= 0;  pos < yythunkpos;  ++pos)
    {
      yythunk *thunk= &yythunks[pos];
      int yyleng= thunk->end ? yyText(thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yytext));
      thunk->action(yytext, yyleng);
    }
  yythunkpos= 0;
}

YY_LOCAL(void) yyCommit()
{
  if ((yylimit -= yypos))
    {
      memmove(yybuf, yybuf + yypos, yylimit);
    }
  yybegin -= yypos;
  yyend -= yypos;
  yypos= yythunkpos= 0;
}

YY_LOCAL(int) yyAccept(int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone();
      yyCommit();
    }
  return 1;
}

YY_LOCAL(void) yyPush(char *text, int count)	{ yyval += count; }
YY_LOCAL(void) yyPop(char *text, int count)	{ yyval -= count; }
YY_LOCAL(void) yySet(char *text, int count)	{ yyval[count]= yy; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yythunkpos0)

YY_RULE(int) yy_forcetoc(); /* 62 */
YY_RULE(int) yy_toc(); /* 61 */
YY_RULE(int) yy_notoc(); /* 60 */
YY_RULE(int) yy_table_cell(); /* 59 */
YY_RULE(int) yy_table_heading(); /* 58 */
YY_RULE(int) yy_table_row(); /* 57 */
YY_RULE(int) yy_table_header(); /* 56 */
YY_RULE(int) yy_table_caption(); /* 55 */
YY_RULE(int) yy_table_body(); /* 54 */
YY_RULE(int) yy_thumb(); /* 53 */
YY_RULE(int) yy_frame(); /* 52 */
YY_RULE(int) yy_float(); /* 51 */
YY_RULE(int) yy_image_type(); /* 50 */
YY_RULE(int) yy_generic_variable(); /* 49 */
YY_RULE(int) yy_special_image_variables(); /* 48 */
YY_RULE(int) yy_value(); /* 47 */
YY_RULE(int) yy_variable(); /* 46 */
YY_RULE(int) yy_close_image(); /* 45 */
YY_RULE(int) yy_arguments(); /* 44 */
YY_RULE(int) yy_file_indicator(); /* 43 */
YY_RULE(int) yy_open_image(); /* 42 */
YY_RULE(int) yy_link_name(); /* 41 */
YY_RULE(int) yy_link_url(); /* 40 */
YY_RULE(int) yy_url(); /* 39 */
YY_RULE(int) yy_unnamed_link(); /* 38 */
YY_RULE(int) yy_named_link(); /* 37 */
YY_RULE(int) yy_external_link(); /* 36 */
YY_RULE(int) yy_simple_link(); /* 35 */
YY_RULE(int) yy_renamed_link(); /* 34 */
YY_RULE(int) yy_pre_line(); /* 33 */
YY_RULE(int) yy_italic(); /* 32 */
YY_RULE(int) yy_bold(); /* 31 */
YY_RULE(int) yy_bold_italic(); /* 30 */
YY_RULE(int) yy_numbered(); /* 29 */
YY_RULE(int) yy_numbered_list_entry(); /* 28 */
YY_RULE(int) yy_bullet(); /* 27 */
YY_RULE(int) yy_bullet_list_entry(); /* 26 */
YY_RULE(int) yy_numbered_list(); /* 25 */
YY_RULE(int) yy_bullet_list(); /* 24 */
YY_RULE(int) yy_heading_text(); /* 23 */
YY_RULE(int) yy_heading_marker(); /* 22 */
YY_RULE(int) yy_space(); /* 21 */
YY_RULE(int) yy_eof(); /* 20 */
YY_RULE(int) yy_eol(); /* 19 */
YY_RULE(int) yy_anything_else(); /* 18 */
YY_RULE(int) yy_table(); /* 17 */
YY_RULE(int) yy_link(); /* 16 */
YY_RULE(int) yy_image(); /* 15 */
YY_RULE(int) yy_formatting(); /* 14 */
YY_RULE(int) yy_list(); /* 13 */
YY_RULE(int) yy_indentation(); /* 12 */
YY_RULE(int) yy_heading(); /* 11 */
YY_RULE(int) yy_template(); /* 10 */
YY_RULE(int) yy_table_of_contents(); /* 9 */
YY_RULE(int) yy_horizontal_line(); /* 8 */
YY_RULE(int) yy_paragraph(); /* 7 */
YY_RULE(int) yy_wikitext(); /* 6 */
YY_RULE(int) yy_wikitext_line(); /* 5 */
YY_RULE(int) yy_pre_block(); /* 4 */
YY_RULE(int) yy_html(); /* 3 */
YY_RULE(int) yy_nowiki(); /* 2 */
YY_RULE(int) yy_page(); /* 1 */

YY_ACTION(void) yy_1_anything_else(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_anything_else\n"));
   start_of_line = 0; append_to_tag_content(yytext); ;
}
YY_ACTION(void) yy_1_html(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_html\n"));
   
  if(valid_html_tag(yytext, yyleng)) { 
    bstring b = bfromcstr(yytext);
    btolower(b);
    bprintf("<%s>", bdata(b));
    bdestroy(b);
  } else {
    bprintf("&lt;%s&gt;", yytext); 
  }
  start_of_line = 0;
;
}
YY_ACTION(void) yy_1_toc(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_toc\n"));
   toc_attributes |= TOC_RELOC; bprintf("__TOC__"); // pass-through for later replacement ;
}
YY_ACTION(void) yy_1_forcetoc(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_forcetoc\n"));
   toc_attributes |= TOC_FORCETOC; ;
}
YY_ACTION(void) yy_1_notoc(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_notoc\n"));
   toc_attributes |= TOC_NOTOC; ;
}
YY_ACTION(void) yy_1_template(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_template\n"));
   start_of_line = 0; ;
}
YY_ACTION(void) yy_3_table_heading(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_3_table_heading\n"));
  bprintf("%s</th>", yytext); ;
}
YY_ACTION(void) yy_2_table_heading(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_table_heading\n"));
   bprintf(" %s>", yytext); ;
}
YY_ACTION(void) yy_1_table_heading(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_table_heading\n"));
   bprintf("<th"); ;
}
YY_ACTION(void) yy_2_table_header(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_table_header\n"));
   bprintf("</tr>"); ;
}
YY_ACTION(void) yy_1_table_header(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_table_header\n"));
   bprintf("<tr>"); ;
}
YY_ACTION(void) yy_2_table_cell(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_table_cell\n"));
   bprintf("%s</td>", yytext); ;
}
YY_ACTION(void) yy_1_table_cell(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_table_cell\n"));
   bprintf("<td>"); ;
}
YY_ACTION(void) yy_2_table_row(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_table_row\n"));
   bprintf("</tr>"); ;
}
YY_ACTION(void) yy_1_table_row(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_table_row\n"));
   bprintf("<tr>"); ;
}
YY_ACTION(void) yy_1_table_caption(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_table_caption\n"));
   bprintf("<caption>%s</caption>", yytext); ;
}
YY_ACTION(void) yy_2_table(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_table\n"));
   bprintf("</table>"); ;
}
YY_ACTION(void) yy_1_table(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_table\n"));
   bprintf("<table>"); ;
}
YY_ACTION(void) yy_1_value(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_value\n"));
   
  bformata(image_variables, "=\"%s\"", yytext);
;
}
YY_ACTION(void) yy_1_generic_variable(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_generic_variable\n"));
   
  bformata(image_variables, "%s", yytext);
;
}
YY_ACTION(void) yy_1_float(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_float\n"));
   
  bformata(image_variables, " class=\"float%s\"", yytext);
;
}
YY_ACTION(void) yy_1_thumb(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_thumb\n"));
   image_attributes |= IMAGE_THUMB; ;
}
YY_ACTION(void) yy_1_frame(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_frame\n"));
   image_attributes |= IMAGE_FRAME; ;
}
YY_ACTION(void) yy_1_file_indicator(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_file_indicator\n"));
   bassignformat(image_url, "%s", yytext); ;
}
YY_ACTION(void) yy_2_image(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_image\n"));
  
  if(image_attributes & IMAGE_FRAME) {
    bprintf("<div class=\"thumb tright\"><div class=\"thumbinner\">");
  }

  if(image_attributes & IMAGE_THUMB) {
    bprintf("<a href=\"File:%s\" class=\"image\"><img src=\"%s\" width=\"220\" height=\"30\" class=\"thumbimage\"/></a>", bdata(image_url), bdata(image_url));
  } else if(image_attributes & IMAGE_FRAME) {
    bprintf("<a href=\"File:%s\" class=\"image\"><img src=\"%s\" class=\"thumbimage\"/></a>", bdata(image_url), bdata(image_url));
  } else {
    bprintf("<a href=\"File:%s\" class=\"image\"><img src=\"%s\" %s/></a>", bdata(image_url), bdata(image_url), bdata(image_variables));
  }

  if(image_attributes & IMAGE_FRAME) {
    bprintf("<div class=\"thumbcaption\"></div></div>");
  }
;
}
YY_ACTION(void) yy_1_image(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_image\n"));
   btrunc(image_variables, 0); ;
}
YY_ACTION(void) yy_2_url(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_url\n"));
   append_to_tag_content("<a href=\"%s://%s\">%s://%s</a>", protocol, yytext, protocol, yytext); ;
}
YY_ACTION(void) yy_1_url(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_url\n"));
   strcpy(protocol, yytext); ;
}
YY_ACTION(void) yy_1_unnamed_link(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_unnamed_link\n"));
   append_to_tag_content("<a href=\"%s\">%s</a>", yytext, yytext);;
}
YY_ACTION(void) yy_1_link_name(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_link_name\n"));
   append_to_tag_content(yytext); ;
}
YY_ACTION(void) yy_1_link_url(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_link_url\n"));
   append_to_tag_content(yytext); ;
}
YY_ACTION(void) yy_3_named_link(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_3_named_link\n"));
  append_to_tag_content("</a>"); ;
}
YY_ACTION(void) yy_2_named_link(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_named_link\n"));
   append_to_tag_content("\">");;
}
YY_ACTION(void) yy_1_named_link(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_named_link\n"));
   append_to_tag_content("<a href=\""); ;
}
YY_ACTION(void) yy_2_simple_link(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_simple_link\n"));
   
    append_to_tag_content("%s</a>", yytext); 
    start_of_line = 0; // prevent <pre> block from starting due to the next space 
  ;
}
YY_ACTION(void) yy_1_simple_link(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_simple_link\n"));
  
    bstring path = bfromcstr(yytext);
    strip_html_markup(path);
    urlencode(path);
    bstring name = bfromcstr(yytext);
    remove_parentheticals(name);
    brtrimws(name);
    append_to_tag_content("<a href=\"/%s\">%s", bdata(path), bdata(name));
    bdestroy(path);
    bdestroy(name);
  ;
}
YY_ACTION(void) yy_2_renamed_link(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_renamed_link\n"));
   
    append_to_tag_content("%s</a>", yytext); 
    start_of_line = 0; // prevent <pre> block from starting due to the next space
  ;
}
YY_ACTION(void) yy_1_renamed_link(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_renamed_link\n"));
   
    bstring path = bfromcstr(yytext);
    strip_html_markup(path);
    urlencode(path);
    append_to_tag_content("<a href=\"/%s\">", bdata(path));
    bdestroy(path);
  ;
}
YY_ACTION(void) yy_1_link(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_link\n"));
   start_of_line = 0; ;
}
YY_ACTION(void) yy_1_pre_line(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_pre_line\n"));
   bprintf("%s", yytext); ;
}
YY_ACTION(void) yy_2_pre_block(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_pre_block\n"));
   bprintf("</pre>"); ;
}
YY_ACTION(void) yy_1_pre_block(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_pre_block\n"));
   bprintf("<pre>"); ;
}
YY_ACTION(void) yy_2_italic(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_italic\n"));
  append_to_tag_content("</i>");;
}
YY_ACTION(void) yy_1_italic(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_italic\n"));
  append_to_tag_content("<i>");;
}
YY_ACTION(void) yy_2_bold(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_bold\n"));
  append_to_tag_content("</b>");;
}
YY_ACTION(void) yy_1_bold(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_bold\n"));
  append_to_tag_content("<b>");;
}
YY_ACTION(void) yy_2_bold_italic(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_bold_italic\n"));
  append_to_tag_content("</i></b>");;
}
YY_ACTION(void) yy_1_bold_italic(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_bold_italic\n"));
  append_to_tag_content("<b><i>");;
}
YY_ACTION(void) yy_1_numbered(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_numbered\n"));
  
  start_of_line = 0;
  if(current_numbered_list_level < yyleng && current_numbered_list_level != 0) {
    bprintf("<ol>");
  } else if(current_numbered_list_level > yyleng) {
    bprintf("</ol>");
  }
  current_numbered_list_level = yyleng; 
  bprintf("<li>"); 
;
}
YY_ACTION(void) yy_1_numbered_list_entry(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_numbered_list_entry\n"));
   bprintf("</li>"); ;
}
YY_ACTION(void) yy_2_numbered_list(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_numbered_list\n"));
   while(current_numbered_list_level--) { bprintf("</ol>"); } ;
}
YY_ACTION(void) yy_1_numbered_list(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_numbered_list\n"));
   bprintf("<ol>"); ;
}
YY_ACTION(void) yy_1_bullet(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_bullet\n"));
  
  start_of_line = 0;
  if(current_bullet_list_level < yyleng && current_bullet_list_level != 0) {
    bprintf("<ul>");
  } else if(current_bullet_list_level > yyleng) {
    bprintf("</ul>");
  }
  current_bullet_list_level = yyleng; 
  bprintf("<li>"); 
;
}
YY_ACTION(void) yy_1_bullet_list_entry(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_bullet_list_entry\n"));
   bprintf("</li>"); ;
}
YY_ACTION(void) yy_2_bullet_list(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_bullet_list\n"));
   
  while((current_bullet_list_level > 0) && current_bullet_list_level--) { 
    bprintf("</ul>"); 
  }
;
}
YY_ACTION(void) yy_1_bullet_list(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_bullet_list\n"));
   bprintf("<ul>"); ;
}
YY_ACTION(void) yy_1_indentation(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_indentation\n"));
   bprintf("&nbsp;&nbsp;"); ;
}
YY_ACTION(void) yy_1_horizontal_line(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_horizontal_line\n"));
   bprintf("<hr/>"); ;
}
YY_ACTION(void) yy_1_paragraph(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_paragraph\n"));
   bprintf("</p><p>"); ;
}
YY_ACTION(void) yy_1_heading_marker(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_heading_marker\n"));
   if(current_header_level == 0) current_header_level = (yyleng > 5) ? 5 : yyleng; ;
}
YY_ACTION(void) yy_2_heading(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_2_heading\n"));
  
    brtrimws(tag_content);
    bstring tmp = bstrcpy(tag_content);
    strip_html_markup(tmp);
    urlencode(tmp);
    bprintf("<span class=\"editsection\">[<a href=\"edit\">edit</a>]</span><span class=\"mw-headline\" id=\"%s\">", bdata(tmp));
    bdestroy(tmp);

    bprintf("%s</span>", bdata(tag_content));
    char tag[4];
    sprintf(tag, "h%d", current_header_level);
    close_tag(tag);

    struct node *current = list_get_new_tail(&list);

    tmp = bstrcpy(tag_content);
    strip_html_markup(tmp);
    urlencode(tmp);
    bprintf("<a name=\"%s\" />", bdata(tmp));
    bassign(current->name, tmp);

    bstring human_name = bstrcpy(tag_content);
    strip_tags(human_name);
    brtrimws(human_name);
    bassign(current->content, human_name);
    current->level = current_header_level;

    bdestroy(tmp);
    bdestroy(human_name);

    btrunc(tag_content, 0);
    current_header_level = 0;
  ;
}
YY_ACTION(void) yy_1_heading(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_heading\n"));
  
    char tag[4];
    sprintf(tag, "h%d", current_header_level);
    open_tag(tag, NULL);
  ;
}
YY_ACTION(void) yy_1_eol(char *yytext, int yyleng)
{
  yyprintf((stderr, "do yy_1_eol\n"));
   start_of_line = 1; ;
}

YY_RULE(int) yy_forcetoc()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "forcetoc"));  if (!yymatchString("__FORCETOC__")) goto l1;  yyDo(yy_1_forcetoc, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "forcetoc", yybuf+yypos));
  return 1;
  l1:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "forcetoc", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_toc()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "toc"));  if (!yymatchString("__TOC__")) goto l2;  yyDo(yy_1_toc, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "toc", yybuf+yypos));
  return 1;
  l2:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "toc", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_notoc()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "notoc"));  if (!yymatchString("__NOTOC__")) goto l3;  yyDo(yy_1_notoc, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "notoc", yybuf+yypos));
  return 1;
  l3:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "notoc", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_table_cell()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "table_cell"));
  {  int yypos5= yypos, yythunkpos5= yythunkpos;  if (!yymatchChar('|')) goto l5;  goto l6;
  l5:;	  yypos= yypos5; yythunkpos= yythunkpos5;
  }
  l6:;	  yyDo(yy_1_table_cell, yybegin, yyend);  if (!yymatchChar(' ')) goto l4;
  l7:;	
  {  int yypos8= yypos, yythunkpos8= yythunkpos;  if (!yymatchChar(' ')) goto l8;  goto l7;
  l8:;	  yypos= yypos8; yythunkpos= yythunkpos8;
  }  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l4;
  l9:;	
  {  int yypos10= yypos, yythunkpos10= yythunkpos;
  {  int yypos11= yypos, yythunkpos11= yythunkpos;  if (!yymatchString("||")) goto l11;  goto l10;
  l11:;	  yypos= yypos11; yythunkpos= yythunkpos11;
  }
  {  int yypos12= yypos, yythunkpos12= yythunkpos;  if (!yy_eol()) goto l12;  goto l10;
  l12:;	  yypos= yypos12; yythunkpos= yythunkpos12;
  }  if (!yymatchDot()) goto l10;  goto l9;
  l10:;	  yypos= yypos10; yythunkpos= yythunkpos10;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l4;
  {  int yypos13= yypos, yythunkpos13= yythunkpos;  if (!yy_eol()) goto l14;  goto l13;
  l14:;	  yypos= yypos13; yythunkpos= yythunkpos13;  if (!yymatchString("||")) goto l4;
  }
  l13:;	  yyDo(yy_2_table_cell, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "table_cell", yybuf+yypos));
  return 1;
  l4:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "table_cell", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_table_heading()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "table_heading"));  yyDo(yy_1_table_heading, yybegin, yyend);  if (!yymatchChar('!')) goto l15;  if (!yymatchChar(' ')) goto l15;
  l16:;	
  {  int yypos17= yypos, yythunkpos17= yythunkpos;  if (!yymatchChar(' ')) goto l17;  goto l16;
  l17:;	  yypos= yypos17; yythunkpos= yythunkpos17;
  }  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l15;
  l18:;	
  {  int yypos19= yypos, yythunkpos19= yythunkpos;
  {  int yypos20= yypos, yythunkpos20= yythunkpos;  if (!yymatchString(" |")) goto l20;  goto l19;
  l20:;	  yypos= yypos20; yythunkpos= yythunkpos20;
  }  if (!yymatchDot()) goto l19;  goto l18;
  l19:;	  yypos= yypos19; yythunkpos= yythunkpos19;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l15;  yyDo(yy_2_table_heading, yybegin, yyend);  if (!yymatchString(" |")) goto l15;
  l21:;	
  {  int yypos22= yypos, yythunkpos22= yythunkpos;  if (!yy_space()) goto l22;  goto l21;
  l22:;	  yypos= yypos22; yythunkpos= yythunkpos22;
  }  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l15;
  l23:;	
  {  int yypos24= yypos, yythunkpos24= yythunkpos;
  {  int yypos25= yypos, yythunkpos25= yythunkpos;  if (!yy_eol()) goto l25;  goto l24;
  l25:;	  yypos= yypos25; yythunkpos= yythunkpos25;
  }  if (!yymatchDot()) goto l24;  goto l23;
  l24:;	  yypos= yypos24; yythunkpos= yythunkpos24;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l15;  if (!yy_eol()) goto l15;  yyDo(yy_3_table_heading, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "table_heading", yybuf+yypos));
  return 1;
  l15:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "table_heading", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_table_row()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "table_row"));  if (!yymatchString("|-")) goto l26;  yyDo(yy_1_table_row, yybegin, yyend);
  l27:;	
  {  int yypos28= yypos, yythunkpos28= yythunkpos;  if (!yy_space()) goto l28;  goto l27;
  l28:;	  yypos= yypos28; yythunkpos= yythunkpos28;
  }  if (!yy_eol()) goto l26;
  l29:;	
  {  int yypos30= yypos, yythunkpos30= yythunkpos;  if (!yy_table_heading()) goto l30;  goto l29;
  l30:;	  yypos= yypos30; yythunkpos= yythunkpos30;
  }
  l31:;	
  {  int yypos32= yypos, yythunkpos32= yythunkpos;  if (!yy_table_cell()) goto l32;  goto l31;
  l32:;	  yypos= yypos32; yythunkpos= yythunkpos32;
  }  yyDo(yy_2_table_row, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "table_row", yybuf+yypos));
  return 1;
  l26:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "table_row", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_table_header()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "table_header"));  yyDo(yy_1_table_header, yybegin, yyend);  if (!yy_table_heading()) goto l33;
  l34:;	
  {  int yypos35= yypos, yythunkpos35= yythunkpos;  if (!yy_table_heading()) goto l35;  goto l34;
  l35:;	  yypos= yypos35; yythunkpos= yythunkpos35;
  }  yyDo(yy_2_table_header, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "table_header", yybuf+yypos));
  return 1;
  l33:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "table_header", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_table_caption()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "table_caption"));  if (!yymatchString("|+")) goto l36;  if (!yymatchChar(' ')) goto l36;
  l37:;	
  {  int yypos38= yypos, yythunkpos38= yythunkpos;  if (!yymatchChar(' ')) goto l38;  goto l37;
  l38:;	  yypos= yypos38; yythunkpos= yythunkpos38;
  }  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l36;
  l39:;	
  {  int yypos40= yypos, yythunkpos40= yythunkpos;
  {  int yypos41= yypos, yythunkpos41= yythunkpos;  if (!yy_eol()) goto l41;  goto l40;
  l41:;	  yypos= yypos41; yythunkpos= yythunkpos41;
  }  if (!yymatchDot()) goto l40;  goto l39;
  l40:;	  yypos= yypos40; yythunkpos= yythunkpos40;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l36;  if (!yy_eol()) goto l36;  yyDo(yy_1_table_caption, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "table_caption", yybuf+yypos));
  return 1;
  l36:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "table_caption", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_table_body()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "table_body"));
  {  int yypos43= yypos, yythunkpos43= yythunkpos;  if (!yy_table_caption()) goto l43;  goto l44;
  l43:;	  yypos= yypos43; yythunkpos= yythunkpos43;
  }
  l44:;	
  {  int yypos45= yypos, yythunkpos45= yythunkpos;  if (!yy_table_header()) goto l45;  goto l46;
  l45:;	  yypos= yypos45; yythunkpos= yythunkpos45;
  }
  l46:;	  if (!yy_table_row()) goto l42;
  l47:;	
  {  int yypos48= yypos, yythunkpos48= yythunkpos;  if (!yy_table_row()) goto l48;  goto l47;
  l48:;	  yypos= yypos48; yythunkpos= yythunkpos48;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "table_body", yybuf+yypos));
  return 1;
  l42:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "table_body", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_thumb()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "thumb"));
  {  int yypos50= yypos, yythunkpos50= yythunkpos;  if (!yymatchString("thumbnail")) goto l51;  goto l50;
  l51:;	  yypos= yypos50; yythunkpos= yythunkpos50;  if (!yymatchString("thumb")) goto l49;
  }
  l50:;	  yyDo(yy_1_thumb, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "thumb", yybuf+yypos));
  return 1;
  l49:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "thumb", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_frame()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "frame"));  if (!yymatchString("frame")) goto l52;  yyDo(yy_1_frame, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "frame", yybuf+yypos));
  return 1;
  l52:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "frame", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_float()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "float"));
  {  int yypos54= yypos, yythunkpos54= yythunkpos;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l55;
  {  int yypos56= yypos, yythunkpos56= yythunkpos;  if (!yymatchString("left")) goto l57;  goto l56;
  l57:;	  yypos= yypos56; yythunkpos= yythunkpos56;  if (!yymatchString("right")) goto l58;  goto l56;
  l58:;	  yypos= yypos56; yythunkpos= yythunkpos56;  if (!yymatchString("center")) goto l55;
  }
  l56:;	  yyText(yybegin, yyend);  if (!(YY_END)) goto l55;  yyDo(yy_1_float, yybegin, yyend);  goto l54;
  l55:;	  yypos= yypos54; yythunkpos= yythunkpos54;  if (!yymatchString("none")) goto l53;
  }
  l54:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "float", yybuf+yypos));
  return 1;
  l53:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "float", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_image_type()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "image_type"));
  {  int yypos60= yypos, yythunkpos60= yythunkpos;  if (!yy_frame()) goto l61;  goto l60;
  l61:;	  yypos= yypos60; yythunkpos= yythunkpos60;  if (!yy_thumb()) goto l59;
  }
  l60:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "image_type", yybuf+yypos));
  return 1;
  l59:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "image_type", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_generic_variable()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "generic_variable"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l62;
  l63:;	
  {  int yypos64= yypos, yythunkpos64= yythunkpos;
  {  int yypos65= yypos, yythunkpos65= yythunkpos;  if (!yymatchChar('|')) goto l65;  goto l64;
  l65:;	  yypos= yypos65; yythunkpos= yythunkpos65;
  }
  {  int yypos66= yypos, yythunkpos66= yythunkpos;  if (!yymatchChar('=')) goto l66;  goto l64;
  l66:;	  yypos= yypos66; yythunkpos= yythunkpos66;
  }
  {  int yypos67= yypos, yythunkpos67= yythunkpos;  if (!yy_close_image()) goto l67;  goto l64;
  l67:;	  yypos= yypos67; yythunkpos= yythunkpos67;
  }  if (!yymatchDot()) goto l64;  goto l63;
  l64:;	  yypos= yypos64; yythunkpos= yythunkpos64;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l62;  yyDo(yy_1_generic_variable, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "generic_variable", yybuf+yypos));
  return 1;
  l62:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "generic_variable", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_special_image_variables()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "special_image_variables"));
  {  int yypos69= yypos, yythunkpos69= yythunkpos;  if (!yy_image_type()) goto l70;  goto l69;
  l70:;	  yypos= yypos69; yythunkpos= yythunkpos69;  if (!yy_float()) goto l68;
  }
  l69:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "special_image_variables", yybuf+yypos));
  return 1;
  l68:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "special_image_variables", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_value()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "value"));  if (!yymatchChar('=')) goto l71;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l71;
  l72:;	
  {  int yypos73= yypos, yythunkpos73= yythunkpos;
  {  int yypos74= yypos, yythunkpos74= yythunkpos;  if (!yymatchChar('|')) goto l74;  goto l73;
  l74:;	  yypos= yypos74; yythunkpos= yythunkpos74;
  }
  {  int yypos75= yypos, yythunkpos75= yythunkpos;  if (!yy_close_image()) goto l75;  goto l73;
  l75:;	  yypos= yypos75; yythunkpos= yythunkpos75;
  }  if (!yymatchDot()) goto l73;  goto l72;
  l73:;	  yypos= yypos73; yythunkpos= yythunkpos73;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l71;  yyDo(yy_1_value, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "value", yybuf+yypos));
  return 1;
  l71:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "value", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_variable()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "variable"));
  {  int yypos77= yypos, yythunkpos77= yythunkpos;  if (!yy_special_image_variables()) goto l78;  goto l77;
  l78:;	  yypos= yypos77; yythunkpos= yythunkpos77;  if (!yy_generic_variable()) goto l76;
  }
  l77:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "variable", yybuf+yypos));
  return 1;
  l76:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "variable", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_close_image()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "close_image"));
  l80:;	
  {  int yypos81= yypos, yythunkpos81= yythunkpos;  if (!yy_space()) goto l81;  goto l80;
  l81:;	  yypos= yypos81; yythunkpos= yythunkpos81;
  }  if (!yymatchString("]]")) goto l79;
  yyprintf((stderr, "  ok   %s @ %s\n", "close_image", yybuf+yypos));
  return 1;
  l79:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "close_image", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_arguments()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "arguments"));  if (!yymatchChar('|')) goto l82;  if (!yy_variable()) goto l82;
  {  int yypos83= yypos, yythunkpos83= yythunkpos;  if (!yy_value()) goto l83;  goto l84;
  l83:;	  yypos= yypos83; yythunkpos= yythunkpos83;
  }
  l84:;	
  {  int yypos85= yypos, yythunkpos85= yythunkpos;  if (!yy_arguments()) goto l85;  goto l86;
  l85:;	  yypos= yypos85; yythunkpos= yythunkpos85;
  }
  l86:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "arguments", yybuf+yypos));
  return 1;
  l82:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "arguments", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_file_indicator()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "file_indicator"));
  {  int yypos88= yypos, yythunkpos88= yythunkpos;  if (!yymatchString("File:")) goto l89;  goto l88;
  l89:;	  yypos= yypos88; yythunkpos= yythunkpos88;  if (!yymatchString("Image:")) goto l87;
  }
  l88:;	  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l87;
  l90:;	
  {  int yypos91= yypos, yythunkpos91= yythunkpos;
  {  int yypos92= yypos, yythunkpos92= yythunkpos;  if (!yymatchChar('|')) goto l92;  goto l91;
  l92:;	  yypos= yypos92; yythunkpos= yythunkpos92;
  }
  {  int yypos93= yypos, yythunkpos93= yythunkpos;  if (!yy_close_image()) goto l93;  goto l91;
  l93:;	  yypos= yypos93; yythunkpos= yythunkpos93;
  }  if (!yymatchDot()) goto l91;  goto l90;
  l91:;	  yypos= yypos91; yythunkpos= yythunkpos91;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l87;  yyDo(yy_1_file_indicator, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "file_indicator", yybuf+yypos));
  return 1;
  l87:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "file_indicator", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_open_image()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "open_image"));  if (!yymatchString("[[")) goto l94;
  l95:;	
  {  int yypos96= yypos, yythunkpos96= yythunkpos;  if (!yy_space()) goto l96;  goto l95;
  l96:;	  yypos= yypos96; yythunkpos= yythunkpos96;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "open_image", yybuf+yypos));
  return 1;
  l94:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "open_image", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_link_name()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "link_name"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l97;
  {  int yypos100= yypos, yythunkpos100= yythunkpos;  if (!yymatchChar(']')) goto l100;  goto l97;
  l100:;	  yypos= yypos100; yythunkpos= yythunkpos100;
  }  if (!yymatchDot()) goto l97;
  l98:;	
  {  int yypos99= yypos, yythunkpos99= yythunkpos;
  {  int yypos101= yypos, yythunkpos101= yythunkpos;  if (!yymatchChar(']')) goto l101;  goto l99;
  l101:;	  yypos= yypos101; yythunkpos= yythunkpos101;
  }  if (!yymatchDot()) goto l99;  goto l98;
  l99:;	  yypos= yypos99; yythunkpos= yythunkpos99;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l97;  yyDo(yy_1_link_name, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "link_name", yybuf+yypos));
  return 1;
  l97:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "link_name", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_link_url()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "link_url"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l102;
  {  int yypos105= yypos, yythunkpos105= yythunkpos;  if (!yymatchChar(' ')) goto l105;  goto l102;
  l105:;	  yypos= yypos105; yythunkpos= yythunkpos105;
  }
  {  int yypos106= yypos, yythunkpos106= yythunkpos;  if (!yymatchChar(']')) goto l106;  goto l102;
  l106:;	  yypos= yypos106; yythunkpos= yythunkpos106;
  }  if (!yymatchDot()) goto l102;
  l103:;	
  {  int yypos104= yypos, yythunkpos104= yythunkpos;
  {  int yypos107= yypos, yythunkpos107= yythunkpos;  if (!yymatchChar(' ')) goto l107;  goto l104;
  l107:;	  yypos= yypos107; yythunkpos= yythunkpos107;
  }
  {  int yypos108= yypos, yythunkpos108= yythunkpos;  if (!yymatchChar(']')) goto l108;  goto l104;
  l108:;	  yypos= yypos108; yythunkpos= yythunkpos108;
  }  if (!yymatchDot()) goto l104;  goto l103;
  l104:;	  yypos= yypos104; yythunkpos= yythunkpos104;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l102;  yyDo(yy_1_link_url, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "link_url", yybuf+yypos));
  return 1;
  l102:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "link_url", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_url()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "url"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l109;
  {  int yypos110= yypos, yythunkpos110= yythunkpos;  if (!yymatchString("http")) goto l111;  goto l110;
  l111:;	  yypos= yypos110; yythunkpos= yythunkpos110;  if (!yymatchString("https")) goto l112;  goto l110;
  l112:;	  yypos= yypos110; yythunkpos= yythunkpos110;  if (!yymatchString("ftp")) goto l109;
  }
  l110:;	  yyText(yybegin, yyend);  if (!(YY_END)) goto l109;  yyDo(yy_1_url, yybegin, yyend);  if (!yymatchString("://")) goto l109;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l109;
  l113:;	
  {  int yypos114= yypos, yythunkpos114= yythunkpos;
  {  int yypos115= yypos, yythunkpos115= yythunkpos;  if (!yy_eol()) goto l115;  goto l114;
  l115:;	  yypos= yypos115; yythunkpos= yythunkpos115;
  }
  {  int yypos116= yypos, yythunkpos116= yythunkpos;  if (!yymatchChar(' ')) goto l116;  goto l114;
  l116:;	  yypos= yypos116; yythunkpos= yythunkpos116;
  }  if (!yymatchDot()) goto l114;  goto l113;
  l114:;	  yypos= yypos114; yythunkpos= yythunkpos114;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l109;  yyDo(yy_2_url, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "url", yybuf+yypos));
  return 1;
  l109:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "url", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_unnamed_link()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "unnamed_link"));  if (!yymatchChar('[')) goto l117;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l117;
  l118:;	
  {  int yypos119= yypos, yythunkpos119= yythunkpos;
  {  int yypos120= yypos, yythunkpos120= yythunkpos;  if (!yymatchChar(']')) goto l120;  goto l119;
  l120:;	  yypos= yypos120; yythunkpos= yythunkpos120;
  }  if (!yymatchDot()) goto l119;  goto l118;
  l119:;	  yypos= yypos119; yythunkpos= yythunkpos119;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l117;  if (!yymatchChar(']')) goto l117;  yyDo(yy_1_unnamed_link, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "unnamed_link", yybuf+yypos));
  return 1;
  l117:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "unnamed_link", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_named_link()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "named_link"));  if (!yymatchChar('[')) goto l121;  yyDo(yy_1_named_link, yybegin, yyend);  if (!yy_link_url()) goto l121;  yyDo(yy_2_named_link, yybegin, yyend);  if (!yymatchChar(' ')) goto l121;
  l122:;	
  {  int yypos123= yypos, yythunkpos123= yythunkpos;  if (!yymatchChar(' ')) goto l123;  goto l122;
  l123:;	  yypos= yypos123; yythunkpos= yythunkpos123;
  }  if (!yy_link_name()) goto l121;
  l124:;	
  {  int yypos125= yypos, yythunkpos125= yythunkpos;  if (!yy_link_name()) goto l125;  goto l124;
  l125:;	  yypos= yypos125; yythunkpos= yythunkpos125;
  }
  l126:;	
  {  int yypos127= yypos, yythunkpos127= yythunkpos;  if (!yy_space()) goto l127;  goto l126;
  l127:;	  yypos= yypos127; yythunkpos= yythunkpos127;
  }  if (!yymatchChar(']')) goto l121;  yyDo(yy_3_named_link, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "named_link", yybuf+yypos));
  return 1;
  l121:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "named_link", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_external_link()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "external_link"));
  {  int yypos129= yypos, yythunkpos129= yythunkpos;  if (!yy_named_link()) goto l130;  goto l129;
  l130:;	  yypos= yypos129; yythunkpos= yythunkpos129;  if (!yy_unnamed_link()) goto l131;  goto l129;
  l131:;	  yypos= yypos129; yythunkpos= yythunkpos129;  if (!yy_url()) goto l128;
  }
  l129:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "external_link", yybuf+yypos));
  return 1;
  l128:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "external_link", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_simple_link()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "simple_link"));  if (!yymatchString("[[")) goto l132;
  {  int yypos133= yypos, yythunkpos133= yythunkpos;  if (!yymatchChar(':')) goto l133;  goto l134;
  l133:;	  yypos= yypos133; yythunkpos= yythunkpos133;
  }
  l134:;	  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l132;
  l135:;	
  {  int yypos136= yypos, yythunkpos136= yythunkpos;
  {  int yypos137= yypos, yythunkpos137= yythunkpos;  if (!yymatchString("]]")) goto l137;  goto l136;
  l137:;	  yypos= yypos137; yythunkpos= yythunkpos137;
  }  if (!yymatchDot()) goto l136;  goto l135;
  l136:;	  yypos= yypos136; yythunkpos= yythunkpos136;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l132;  yyDo(yy_1_simple_link, yybegin, yyend);  if (!yymatchString("]]")) goto l132;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l132;
  l138:;	
  {  int yypos139= yypos, yythunkpos139= yythunkpos;
  {  int yypos140= yypos, yythunkpos140= yythunkpos;  if (!yy_space()) goto l140;  goto l139;
  l140:;	  yypos= yypos140; yythunkpos= yythunkpos140;
  }
  {  int yypos141= yypos, yythunkpos141= yythunkpos;  if (!yymatchChar('=')) goto l141;  if (!yymatchChar('=')) goto l141;
  l142:;	
  {  int yypos143= yypos, yythunkpos143= yythunkpos;  if (!yymatchChar('=')) goto l143;  goto l142;
  l143:;	  yypos= yypos143; yythunkpos= yythunkpos143;
  }  goto l139;
  l141:;	  yypos= yypos141; yythunkpos= yythunkpos141;
  }
  {  int yypos144= yypos, yythunkpos144= yythunkpos;  if (!yymatchChar('[')) goto l144;  goto l139;
  l144:;	  yypos= yypos144; yythunkpos= yythunkpos144;
  }
  {  int yypos145= yypos, yythunkpos145= yythunkpos;  if (!yy_eol()) goto l145;  goto l139;
  l145:;	  yypos= yypos145; yythunkpos= yythunkpos145;
  }
  {  int yypos146= yypos, yythunkpos146= yythunkpos;  if (!yy_eof()) goto l146;  goto l139;
  l146:;	  yypos= yypos146; yythunkpos= yythunkpos146;
  }  if (!yymatchDot()) goto l139;  goto l138;
  l139:;	  yypos= yypos139; yythunkpos= yythunkpos139;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l132;  yyDo(yy_2_simple_link, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "simple_link", yybuf+yypos));
  return 1;
  l132:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "simple_link", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_renamed_link()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "renamed_link"));  if (!yymatchString("[[")) goto l147;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l147;
  l148:;	
  {  int yypos149= yypos, yythunkpos149= yythunkpos;
  {  int yypos150= yypos, yythunkpos150= yythunkpos;  if (!yymatchChar('|')) goto l150;  goto l149;
  l150:;	  yypos= yypos150; yythunkpos= yythunkpos150;
  }
  {  int yypos151= yypos, yythunkpos151= yythunkpos;  if (!yymatchString("]]")) goto l151;  goto l149;
  l151:;	  yypos= yypos151; yythunkpos= yythunkpos151;
  }  if (!yymatchDot()) goto l149;  goto l148;
  l149:;	  yypos= yypos149; yythunkpos= yythunkpos149;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l147;  yyDo(yy_1_renamed_link, yybegin, yyend);  if (!yymatchChar('|')) goto l147;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l147;
  l152:;	
  {  int yypos153= yypos, yythunkpos153= yythunkpos;
  {  int yypos154= yypos, yythunkpos154= yythunkpos;  if (!yymatchString("]]")) goto l154;  goto l153;
  l154:;	  yypos= yypos154; yythunkpos= yythunkpos154;
  }  if (!yymatchDot()) goto l153;  goto l152;
  l153:;	  yypos= yypos153; yythunkpos= yythunkpos153;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l147;  yyDo(yy_2_renamed_link, yybegin, yyend);  if (!yymatchString("]]")) goto l147;
  yyprintf((stderr, "  ok   %s @ %s\n", "renamed_link", yybuf+yypos));
  return 1;
  l147:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "renamed_link", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_pre_line()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "pre_line"));  if (!yymatchChar(' ')) goto l155;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l155;
  l156:;	
  {  int yypos157= yypos, yythunkpos157= yythunkpos;
  {  int yypos158= yypos, yythunkpos158= yythunkpos;  if (!yy_eol()) goto l158;  goto l157;
  l158:;	  yypos= yypos158; yythunkpos= yythunkpos158;
  }  if (!yymatchDot()) goto l157;  goto l156;
  l157:;	  yypos= yypos157; yythunkpos= yythunkpos157;
  }
  {  int yypos159= yypos, yythunkpos159= yythunkpos;  if (!yy_eol()) goto l160;  goto l159;
  l160:;	  yypos= yypos159; yythunkpos= yythunkpos159;  if (!yy_eof()) goto l155;
  }
  l159:;	  yyText(yybegin, yyend);  if (!(YY_END)) goto l155;  yyDo(yy_1_pre_line, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "pre_line", yybuf+yypos));
  return 1;
  l155:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "pre_line", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_italic()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "italic"));  if (!yymatchString("''")) goto l161;  yyDo(yy_1_italic, yybegin, yyend);
  l162:;	
  {  int yypos163= yypos, yythunkpos163= yythunkpos;
  {  int yypos164= yypos, yythunkpos164= yythunkpos;  if (!yymatchString("''")) goto l164;  goto l163;
  l164:;	  yypos= yypos164; yythunkpos= yythunkpos164;
  }  if (!yy_wikitext()) goto l163;  goto l162;
  l163:;	  yypos= yypos163; yythunkpos= yythunkpos163;
  }  if (!yymatchString("''")) goto l161;  yyDo(yy_2_italic, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "italic", yybuf+yypos));
  return 1;
  l161:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "italic", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_bold()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "bold"));  if (!yymatchString("'''")) goto l165;  yyDo(yy_1_bold, yybegin, yyend);
  l166:;	
  {  int yypos167= yypos, yythunkpos167= yythunkpos;
  {  int yypos168= yypos, yythunkpos168= yythunkpos;  if (!yymatchString("'''")) goto l168;  goto l167;
  l168:;	  yypos= yypos168; yythunkpos= yythunkpos168;
  }  if (!yy_wikitext()) goto l167;  goto l166;
  l167:;	  yypos= yypos167; yythunkpos= yythunkpos167;
  }  if (!yymatchString("'''")) goto l165;  yyDo(yy_2_bold, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "bold", yybuf+yypos));
  return 1;
  l165:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bold", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_bold_italic()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "bold_italic"));  if (!yymatchString("'''''")) goto l169;  yyDo(yy_1_bold_italic, yybegin, yyend);
  l170:;	
  {  int yypos171= yypos, yythunkpos171= yythunkpos;
  {  int yypos172= yypos, yythunkpos172= yythunkpos;  if (!yymatchString("'''''")) goto l172;  goto l171;
  l172:;	  yypos= yypos172; yythunkpos= yythunkpos172;
  }  if (!yy_wikitext()) goto l171;  goto l170;
  l171:;	  yypos= yypos171; yythunkpos= yythunkpos171;
  }  if (!yymatchString("'''''")) goto l169;  yyDo(yy_2_bold_italic, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "bold_italic", yybuf+yypos));
  return 1;
  l169:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bold_italic", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_numbered()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "numbered"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l173;  if (!yymatchChar('#')) goto l173;
  l174:;	
  {  int yypos175= yypos, yythunkpos175= yythunkpos;  if (!yymatchChar('#')) goto l175;  goto l174;
  l175:;	  yypos= yypos175; yythunkpos= yythunkpos175;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l173;  yyDo(yy_1_numbered, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "numbered", yybuf+yypos));
  return 1;
  l173:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "numbered", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_numbered_list_entry()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "numbered_list_entry"));  if (!yy_numbered()) goto l176;
  l177:;	
  {  int yypos178= yypos, yythunkpos178= yythunkpos;  if (!yy_space()) goto l178;  goto l177;
  l178:;	  yypos= yypos178; yythunkpos= yythunkpos178;
  }
  l179:;	
  {  int yypos180= yypos, yythunkpos180= yythunkpos;
  {  int yypos181= yypos, yythunkpos181= yythunkpos;  if (!yy_eol()) goto l181;  goto l180;
  l181:;	  yypos= yypos181; yythunkpos= yythunkpos181;
  }  if (!yy_wikitext()) goto l180;  goto l179;
  l180:;	  yypos= yypos180; yythunkpos= yythunkpos180;
  }
  {  int yypos182= yypos, yythunkpos182= yythunkpos;  if (!yy_eol()) goto l182;  goto l183;
  l182:;	  yypos= yypos182; yythunkpos= yythunkpos182;
  }
  l183:;	  yyDo(yy_1_numbered_list_entry, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "numbered_list_entry", yybuf+yypos));
  return 1;
  l176:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "numbered_list_entry", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_bullet()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "bullet"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l184;  if (!yymatchChar('*')) goto l184;
  l185:;	
  {  int yypos186= yypos, yythunkpos186= yythunkpos;  if (!yymatchChar('*')) goto l186;  goto l185;
  l186:;	  yypos= yypos186; yythunkpos= yythunkpos186;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l184;  yyDo(yy_1_bullet, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "bullet", yybuf+yypos));
  return 1;
  l184:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bullet", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_bullet_list_entry()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "bullet_list_entry"));  if (!yy_bullet()) goto l187;
  l188:;	
  {  int yypos189= yypos, yythunkpos189= yythunkpos;  if (!yy_space()) goto l189;  goto l188;
  l189:;	  yypos= yypos189; yythunkpos= yythunkpos189;
  }
  l190:;	
  {  int yypos191= yypos, yythunkpos191= yythunkpos;
  {  int yypos192= yypos, yythunkpos192= yythunkpos;  if (!yy_eol()) goto l192;  goto l191;
  l192:;	  yypos= yypos192; yythunkpos= yythunkpos192;
  }  if (!yy_wikitext()) goto l191;  goto l190;
  l191:;	  yypos= yypos191; yythunkpos= yythunkpos191;
  }
  {  int yypos193= yypos, yythunkpos193= yythunkpos;  if (!yy_eol()) goto l194;  goto l193;
  l194:;	  yypos= yypos193; yythunkpos= yythunkpos193;  if (!yy_eof()) goto l187;
  }
  l193:;	  yyDo(yy_1_bullet_list_entry, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "bullet_list_entry", yybuf+yypos));
  return 1;
  l187:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bullet_list_entry", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_numbered_list()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "numbered_list"));  yyDo(yy_1_numbered_list, yybegin, yyend);  if (!yy_numbered_list_entry()) goto l195;
  l196:;	
  {  int yypos197= yypos, yythunkpos197= yythunkpos;  if (!yy_numbered_list_entry()) goto l197;  goto l196;
  l197:;	  yypos= yypos197; yythunkpos= yythunkpos197;
  }  yyDo(yy_2_numbered_list, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "numbered_list", yybuf+yypos));
  return 1;
  l195:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "numbered_list", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_bullet_list()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "bullet_list"));  yyDo(yy_1_bullet_list, yybegin, yyend);  if (!yy_bullet_list_entry()) goto l198;
  l199:;	
  {  int yypos200= yypos, yythunkpos200= yythunkpos;  if (!yy_bullet_list_entry()) goto l200;  goto l199;
  l200:;	  yypos= yypos200; yythunkpos= yythunkpos200;
  }  yyDo(yy_2_bullet_list, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "bullet_list", yybuf+yypos));
  return 1;
  l198:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "bullet_list", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_heading_text()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "heading_text"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l201;
  l202:;	
  {  int yypos203= yypos, yythunkpos203= yythunkpos;
  {  int yypos204= yypos, yythunkpos204= yythunkpos;  if (!yy_heading_marker()) goto l204;  goto l203;
  l204:;	  yypos= yypos204; yythunkpos= yythunkpos204;
  }
  {  int yypos205= yypos, yythunkpos205= yythunkpos;  if (!yy_formatting()) goto l206;  goto l205;
  l206:;	  yypos= yypos205; yythunkpos= yythunkpos205;  if (!yy_link()) goto l207;  goto l205;
  l207:;	  yypos= yypos205; yythunkpos= yythunkpos205;  if (!yy_anything_else()) goto l203;
  }
  l205:;	  goto l202;
  l203:;	  yypos= yypos203; yythunkpos= yythunkpos203;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l201;
  yyprintf((stderr, "  ok   %s @ %s\n", "heading_text", yybuf+yypos));
  return 1;
  l201:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "heading_text", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_heading_marker()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "heading_marker"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l208;  if (!yymatchChar('=')) goto l208;  if (!yymatchChar('=')) goto l208;
  l209:;	
  {  int yypos210= yypos, yythunkpos210= yythunkpos;  if (!yymatchChar('=')) goto l210;  goto l209;
  l210:;	  yypos= yypos210; yythunkpos= yythunkpos210;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l208;  yyDo(yy_1_heading_marker, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "heading_marker", yybuf+yypos));
  return 1;
  l208:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "heading_marker", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_space()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "space"));  if (!yymatchClass((unsigned char *)"\000\002\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l211;
  yyprintf((stderr, "  ok   %s @ %s\n", "space", yybuf+yypos));
  return 1;
  l211:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "space", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_eof()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "eof"));
  {  int yypos213= yypos, yythunkpos213= yythunkpos;  if (!yymatchDot()) goto l213;  goto l212;
  l213:;	  yypos= yypos213; yythunkpos= yythunkpos213;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "eof", yybuf+yypos));
  return 1;
  l212:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eof", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_eol()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "eol"));
  {  int yypos215= yypos, yythunkpos215= yythunkpos;  if (!yymatchChar('\r')) goto l215;  goto l216;
  l215:;	  yypos= yypos215; yythunkpos= yythunkpos215;
  }
  l216:;	  if (!yymatchChar('\n')) goto l214;  yyDo(yy_1_eol, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "eol", yybuf+yypos));
  return 1;
  l214:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "eol", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_anything_else()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "anything_else"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l217;
  {  int yypos218= yypos, yythunkpos218= yythunkpos;  if (!yy_eol()) goto l218;  goto l217;
  l218:;	  yypos= yypos218; yythunkpos= yythunkpos218;
  }  if (!yymatchDot()) goto l217;  yyText(yybegin, yyend);  if (!(YY_END)) goto l217;  yyDo(yy_1_anything_else, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "anything_else", yybuf+yypos));
  return 1;
  l217:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "anything_else", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_table()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "table"));  if (!yymatchString("{|")) goto l219;  yyDo(yy_1_table, yybegin, yyend);  if (!yy_eol()) goto l219;  if (!yy_table_body()) goto l219;  if (!yymatchString("|}")) goto l219;
  {  int yypos220= yypos, yythunkpos220= yythunkpos;  if (!yy_eol()) goto l221;  goto l220;
  l221:;	  yypos= yypos220; yythunkpos= yythunkpos220;  if (!yy_eof()) goto l219;
  }
  l220:;	  yyDo(yy_2_table, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "table", yybuf+yypos));
  return 1;
  l219:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "table", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_link()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "link"));
  {  int yypos223= yypos, yythunkpos223= yythunkpos;  if (!yy_renamed_link()) goto l224;  goto l223;
  l224:;	  yypos= yypos223; yythunkpos= yythunkpos223;  if (!yy_simple_link()) goto l225;  goto l223;
  l225:;	  yypos= yypos223; yythunkpos= yythunkpos223;  if (!yy_external_link()) goto l222;  yyDo(yy_1_link, yybegin, yyend);
  }
  l223:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "link", yybuf+yypos));
  return 1;
  l222:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "link", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_image()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "image"));  if (!yy_open_image()) goto l226;  yyDo(yy_1_image, yybegin, yyend);  if (!yy_file_indicator()) goto l226;
  {  int yypos227= yypos, yythunkpos227= yythunkpos;  if (!yy_arguments()) goto l227;  goto l228;
  l227:;	  yypos= yypos227; yythunkpos= yythunkpos227;
  }
  l228:;	  if (!yy_close_image()) goto l226;  yyDo(yy_2_image, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "image", yybuf+yypos));
  return 1;
  l226:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "image", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_formatting()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "formatting"));
  {  int yypos230= yypos, yythunkpos230= yythunkpos;  if (!yy_bold_italic()) goto l231;  goto l230;
  l231:;	  yypos= yypos230; yythunkpos= yythunkpos230;  if (!yy_bold()) goto l232;  goto l230;
  l232:;	  yypos= yypos230; yythunkpos= yythunkpos230;  if (!yy_italic()) goto l229;
  }
  l230:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "formatting", yybuf+yypos));
  return 1;
  l229:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "formatting", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_list()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "list"));
  {  int yypos234= yypos, yythunkpos234= yythunkpos;  if (!yy_bullet_list()) goto l235;  goto l234;
  l235:;	  yypos= yypos234; yythunkpos= yythunkpos234;  if (!yy_numbered_list()) goto l233;
  }
  l234:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "list", yybuf+yypos));
  return 1;
  l233:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "list", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_indentation()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "indentation"));  yyText(yybegin, yyend);  if (!( start_of_line )) goto l236;  if (!yymatchChar(':')) goto l236;  yyDo(yy_1_indentation, yybegin, yyend);  if (!yy_wikitext()) goto l236;
  yyprintf((stderr, "  ok   %s @ %s\n", "indentation", yybuf+yypos));
  return 1;
  l236:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "indentation", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_heading()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "heading"));  if (!yy_heading_marker()) goto l237;  yyDo(yy_1_heading, yybegin, yyend);
  l238:;	
  {  int yypos239= yypos, yythunkpos239= yythunkpos;  if (!yy_space()) goto l239;  goto l238;
  l239:;	  yypos= yypos239; yythunkpos= yythunkpos239;
  }  if (!yy_heading_text()) goto l237;  if (!yy_heading_marker()) goto l237;
  l240:;	
  {  int yypos241= yypos, yythunkpos241= yythunkpos;  if (!yy_space()) goto l241;  goto l240;
  l241:;	  yypos= yypos241; yythunkpos= yythunkpos241;
  }
  {  int yypos242= yypos, yythunkpos242= yythunkpos;  if (!yy_eol()) goto l243;  goto l242;
  l243:;	  yypos= yypos242; yythunkpos= yythunkpos242;  if (!yy_eof()) goto l237;
  }
  l242:;	  yyDo(yy_2_heading, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "heading", yybuf+yypos));
  return 1;
  l237:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "heading", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_template()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "template"));  if (!yymatchString("{{")) goto l244;
  l245:;	
  {  int yypos246= yypos, yythunkpos246= yythunkpos;  if (!yy_space()) goto l246;  goto l245;
  l246:;	  yypos= yypos246; yythunkpos= yythunkpos246;
  }
  l247:;	
  {  int yypos248= yypos, yythunkpos248= yythunkpos;
  {  int yypos249= yypos, yythunkpos249= yythunkpos;  if (!yymatchString("}}")) goto l249;  goto l248;
  l249:;	  yypos= yypos249; yythunkpos= yythunkpos249;
  }  if (!yymatchDot()) goto l248;  goto l247;
  l248:;	  yypos= yypos248; yythunkpos= yythunkpos248;
  }  if (!yymatchString("}}")) goto l244;  yyDo(yy_1_template, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "template", yybuf+yypos));
  return 1;
  l244:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "template", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_table_of_contents()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "table_of_contents"));
  {  int yypos251= yypos, yythunkpos251= yythunkpos;  if (!yy_notoc()) goto l252;  goto l251;
  l252:;	  yypos= yypos251; yythunkpos= yythunkpos251;  if (!yy_toc()) goto l253;  goto l251;
  l253:;	  yypos= yypos251; yythunkpos= yythunkpos251;  if (!yy_forcetoc()) goto l250;
  }
  l251:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "table_of_contents", yybuf+yypos));
  return 1;
  l250:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "table_of_contents", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_horizontal_line()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "horizontal_line"));  if (!yymatchString("----")) goto l254;
  {  int yypos255= yypos, yythunkpos255= yythunkpos;  if (!yy_eol()) goto l256;  goto l255;
  l256:;	  yypos= yypos255; yythunkpos= yythunkpos255;  if (!yy_eof()) goto l254;
  }
  l255:;	  yyDo(yy_1_horizontal_line, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "horizontal_line", yybuf+yypos));
  return 1;
  l254:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "horizontal_line", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_paragraph()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "paragraph"));  if (!yy_wikitext()) goto l257;  if (!yy_eol()) goto l257;  if (!yy_eol()) goto l257;  yyDo(yy_1_paragraph, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "paragraph", yybuf+yypos));
  return 1;
  l257:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "paragraph", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_wikitext()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "wikitext"));
  {  int yypos259= yypos, yythunkpos259= yythunkpos;  if (!yy_table_of_contents()) goto l260;  goto l259;
  l260:;	  yypos= yypos259; yythunkpos= yythunkpos259;  if (!yy_template()) goto l261;  goto l259;
  l261:;	  yypos= yypos259; yythunkpos= yythunkpos259;  if (!yy_heading()) goto l262;  goto l259;
  l262:;	  yypos= yypos259; yythunkpos= yythunkpos259;  if (!yy_indentation()) goto l263;  goto l259;
  l263:;	  yypos= yypos259; yythunkpos= yythunkpos259;  if (!yy_list()) goto l264;  goto l259;
  l264:;	  yypos= yypos259; yythunkpos= yythunkpos259;  if (!yy_formatting()) goto l265;  goto l259;
  l265:;	  yypos= yypos259; yythunkpos= yythunkpos259;  if (!yy_image()) goto l266;  goto l259;
  l266:;	  yypos= yypos259; yythunkpos= yythunkpos259;  if (!yy_link()) goto l267;  goto l259;
  l267:;	  yypos= yypos259; yythunkpos= yythunkpos259;  if (!yy_table()) goto l268;  goto l259;
  l268:;	  yypos= yypos259; yythunkpos= yythunkpos259;  if (!yy_anything_else()) goto l269;  goto l259;
  l269:;	  yypos= yypos259; yythunkpos= yythunkpos259;  if (!yy_eol()) goto l258;
  }
  l259:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "wikitext", yybuf+yypos));
  return 1;
  l258:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "wikitext", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_wikitext_line()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "wikitext_line"));
  {  int yypos271= yypos, yythunkpos271= yythunkpos;  if (!yy_paragraph()) goto l272;  goto l271;
  l272:;	  yypos= yypos271; yythunkpos= yythunkpos271;  if (!yy_horizontal_line()) goto l270;
  }
  l271:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "wikitext_line", yybuf+yypos));
  return 1;
  l270:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "wikitext_line", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_pre_block()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "pre_block"));  yyText(yybegin, yyend);  if (!( start_of_line )) goto l273;  yyDo(yy_1_pre_block, yybegin, yyend);  if (!yy_pre_line()) goto l273;
  l274:;	
  {  int yypos275= yypos, yythunkpos275= yythunkpos;  if (!yy_pre_line()) goto l275;  goto l274;
  l275:;	  yypos= yypos275; yythunkpos= yythunkpos275;
  }  yyDo(yy_2_pre_block, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "pre_block", yybuf+yypos));
  return 1;
  l273:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "pre_block", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_html()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "html"));  if (!yymatchChar('<')) goto l276;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l276;
  {  int yypos277= yypos, yythunkpos277= yythunkpos;  if (!yymatchChar('/')) goto l277;  goto l278;
  l277:;	  yypos= yypos277; yythunkpos= yythunkpos277;
  }
  l278:;	
  {  int yypos281= yypos, yythunkpos281= yythunkpos;  if (!yymatchChar('>')) goto l281;  goto l276;
  l281:;	  yypos= yypos281; yythunkpos= yythunkpos281;
  }  if (!yymatchDot()) goto l276;
  l279:;	
  {  int yypos280= yypos, yythunkpos280= yythunkpos;
  {  int yypos282= yypos, yythunkpos282= yythunkpos;  if (!yymatchChar('>')) goto l282;  goto l280;
  l282:;	  yypos= yypos282; yythunkpos= yythunkpos282;
  }  if (!yymatchDot()) goto l280;  goto l279;
  l280:;	  yypos= yypos280; yythunkpos= yythunkpos280;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l276;
  {  int yypos283= yypos, yythunkpos283= yythunkpos;  if (!yymatchChar('/')) goto l283;  goto l284;
  l283:;	  yypos= yypos283; yythunkpos= yythunkpos283;
  }
  l284:;	  if (!yymatchChar('>')) goto l276;  yyDo(yy_1_html, yybegin, yyend);
  yyprintf((stderr, "  ok   %s @ %s\n", "html", yybuf+yypos));
  return 1;
  l276:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "html", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_nowiki()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "nowiki"));  if (!yymatchString("<nowiki>")) goto l285;
  l286:;	
  {  int yypos287= yypos, yythunkpos287= yythunkpos;
  {  int yypos288= yypos, yythunkpos288= yythunkpos;  if (!yymatchString("</nowiki>")) goto l288;  goto l287;
  l288:;	  yypos= yypos288; yythunkpos= yythunkpos288;
  }  if (!yy_anything_else()) goto l287;  goto l286;
  l287:;	  yypos= yypos287; yythunkpos= yythunkpos287;
  }  if (!yymatchString("</nowiki>")) goto l285;
  yyprintf((stderr, "  ok   %s @ %s\n", "nowiki", yybuf+yypos));
  return 1;
  l285:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "nowiki", yybuf+yypos));
  return 0;
}
YY_RULE(int) yy_page()
{  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "page"));
  {  int yypos290= yypos, yythunkpos290= yythunkpos;  if (!yy_nowiki()) goto l291;  goto l290;
  l291:;	  yypos= yypos290; yythunkpos= yythunkpos290;  if (!yy_html()) goto l292;  goto l290;
  l292:;	  yypos= yypos290; yythunkpos= yythunkpos290;  if (!yy_pre_block()) goto l293;  goto l290;
  l293:;	  yypos= yypos290; yythunkpos= yythunkpos290;  if (!yy_wikitext_line()) goto l294;  goto l290;
  l294:;	  yypos= yypos290; yythunkpos= yythunkpos290;  if (!yy_wikitext()) goto l289;
  }
  l290:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "page", yybuf+yypos));
  return 1;
  l289:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "page", yybuf+yypos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)();

YY_PARSE(int) YYPARSEFROM(yyrule yystart)
{
  int yyok;
  if (!yybuflen)
    {
      yybuflen= 1024;
      yybuf= malloc(yybuflen);
      yytextlen= 1024;
      yytext= malloc(yytextlen);
      yythunkslen= 32;
      yythunks= malloc(sizeof(yythunk) * yythunkslen);
      yyvalslen= 32;
      yyvals= malloc(sizeof(YYSTYPE) * yyvalslen);
      yybegin= yyend= yypos= yylimit= yythunkpos= 0;
    }
  yybegin= yyend= yypos;
  yythunkpos= 0;
  yyval= yyvals;
  yyok= yystart();
  if (yyok) yyDone();
  yyCommit();
  return yyok;
  (void)yyrefill;
  (void)yymatchDot;
  (void)yymatchChar;
  (void)yymatchString;
  (void)yymatchClass;
  (void)yyDo;
  (void)yyText;
  (void)yyDone;
  (void)yyCommit;
  (void)yyAccept;
  (void)yyPush;
  (void)yyPop;
  (void)yySet;
  (void)yytextmax;
}

YY_PARSE(int) YYPARSE(void)
{
  return YYPARSEFROM(yy_page);
}

#endif


void parse(bstring buffer) {
  list_init(&list);

  tag_content = bfromcstr("");
  ballocmin(tag_content, tag_content_size);

  image_variables = bfromcstr("");
  image_url = bfromcstr("");

  output_buffer = buffer;
  ballocmin(output_buffer, 1 * MBYTE);

  bprintf("<p>");
  while(yyparse()) {}
  bprintf("</p>");
  bdestroy(tag_content);
  bdestroy(image_variables);
  bdestroy(image_url);

  handle_toc();
  list_free(&list);
}

int main() {
  bstring output = bfromcstr("");
  parse(output);
  printf("%s", bdata(output));
  bdestroy(output);
  return 0;
}

